### ISSUE TITLE
Draw interaction type is now mandatory?

### ISSUE THREAD

**Issue by BHDBvde** [openlayers/openlayers#12499] opened 2021-07-12 09:56 UTC
**Describe the bug**
Draw interaction type is now mandatory. 
It is more a question: The type-option was optional, now it gives an error. 
Is that correct behaviour?

**To Reproduce**
1. Create interaction with an empty options object: draw = new Draw({
  });
2. Run
3.  Error: Invalid type: undefined

**Expected behavior**
No error.

**Comment by TDesjardins** [comment] 2021-07-12 10:29
I also noticed this new behaviour by a failing test case (not a OL test). Setting the type solves this. Wouldn't classify this as a bug. Actually a type is required for this interaction. So either there is a default type (suppose this was the case before) or leaving this behaviour as it is (error) could be a solution.

**Comment by EvertEt** [comment] 2021-07-12 10:37
This behaviour was introduced in #11845, more specifically 288fd0b74c37477b6addfd7ec01eeedcd4623f38.

I did a quick test with 6.5.0 and it seems that having type as undefined was ok for the constructor, but gave errors when the interaction was used (no default type it seems). So it makes sense this is now checked in the constructor.

**Comment by ahocevar** [comment] 2021-07-12 11:28
This is indeed not a bug. A `type` was always required, but in previous versions it failed silently and caused unexpected behavior later on.

**Closed by ahocevar** 2021-07-12 11:28 UTC
Labels: bug
