### ISSUE TITLE
Modifying a polygon with a duplicate first/last coordinate produces invalid shapes [Not fixed #7875]

### ISSUE THREAD

**Issue by kochizufan** [openlayers/openlayers#9639] opened 2019-06-03 22:37 UTC
**Describe the bug**
Hi, #7875 looks no proceed and automatically closed.
But it looks same bug in 5.0.0 (Sorry I can't update my OL to latest easily, so I want to know it is already fixed or not).

**To Reproduce**
Steps to reproduce:

Create a polygon that has either the first or last vertex duplicated, so it is of the form:
```
{"type": "Polygon", "coordinates": [[
    [1.0, 1.0],
    [2.0, 2.0],
    [3.0, 3.0],
    [1.0, 1.0],
    [1.0, 1.0],
    [1.0, 1.0],
]]}
```
Use ol.interaction.Modify to try to move that duplicated point, an invalid shape will be produced.

![2019-06-04_07-27-23](https://user-images.githubusercontent.com/2221431/58839075-8cb16680-869b-11e9-8c42-74500e42c0e2.png)
![2019-06-04_07-30-06](https://user-images.githubusercontent.com/2221431/58839082-920eb100-869b-11e9-8e59-dbf7a3b2d1fd.png)

**Expected behavior**
Polygon must be keep it's topology.

**Comment by mike-000** [comment] 2019-06-04 12:34
The same problem is happening in https://github.com/openlayers/openlayers/issues/9463

**Comment by ahocevar** [comment] 2019-06-04 13:33
Duplicate of #9463.

**Closed by ahocevar** 2019-06-04 13:33 UTC
