### ISSUE TITLE
VectorImageLayer constantly refreshing

### ISSUE THREAD

**Issue by Toterbiber** [openlayers/openlayers#9211] opened 2019-02-13 08:17 UTC
**Describe the bug**
I updated my project to Openlayers 6.0.0-beta.1. When I'm using vector image layer with a vector source the layer is constantly refreshing itself which makes the application very slow when having a lot of features. 

**Expected behavior**
The layer should only be rendered once while no interaction with the map happens, as it was before.

**Comment by fredj** [comment] 2019-02-13 08:26
See the upgrade notes about the vector image layer:
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#removal-of-the-rendermode-option-for-vector-layers

**Comment by Toterbiber** [comment] 2019-02-13 10:19
I did follow the description and removed the renderMode option and used the VectorImage layer. Except from that I changed nothing.

![grafik](https://user-images.githubusercontent.com/29564082/52704169-38656800-2f80-11e9-9b67-638e06afe25c.png)

And what's new is that:
![grafik](https://user-images.githubusercontent.com/29564082/52704396-c4778f80-2f80-11e9-9701-d79ff0609eaa.png)

I already have someone looking that this in ol sources because we are pretty sure that we are not causing this problem. Maybe we can give more insight later. Also we are happy about any ideas.

**Comment by ahocevar** [comment] 2019-02-13 16:42
Thanks for reporting this. Actually the VectorImage layer keeps re-rendering in an endless loop.

**Comment by ahocevar** [comment] 2019-02-13 23:13
Pull requests welcome. It seems the problem is that rendered vector images are never marked as loaded, so the map renderer goes into an infinite loop. @tschaub, can you maybe take a look at this? Thanks!

**Comment by ahocevar** [comment] 2019-02-13 23:23
Or @fredj?

**Comment by adraw** [comment] 2019-02-14 11:50
It looks like the problem is related to layer revision always getting incremented after image gets loaded and thus the condition to check for replayGroupChange is always false and everytime a new replaygroup gets created.

![image](https://user-images.githubusercontent.com/47631105/52784952-fbb87000-3056-11e9-944d-385e8f35acd1.png)

**Comment by fredj** [comment] 2019-02-14 12:03
I haven't look at it in details but I think that the loop is caused by the `callback` function in the `prepareFrame` function:
https://github.com/openlayers/openlayers/blob/666c14d1901c333077e511d714d51d5867bda009/src/ol/renderer/canvas/VectorImageLayer.js#L81-L91

This function dispatches a `change` event that calls the `prepareFrame` again and again

**Comment by Toterbiber** [comment] 2019-02-14 12:04
@fredj do you have a quick idea what we can do about it? Just to fix it for the moment?

**Comment by fredj** [comment] 2019-02-14 12:49
@Toterbiber see #9217

**Comment by Toterbiber** [comment] 2019-02-14 13:01
@fredj That really seems to work, great! Thank's a lot!

**Closed** 2019-02-15 07:48 UTC
Labels: pull request accepted
