### ISSUE TITLE
[example]vector-wfs.html  access control checks error

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13408] opened 2022-02-21 18:18 UTC
Hi there
On this example i get a lot of error 'not allowed by Access-Control-Allow-Origin' ... and access control checks ...
https://openlayers.org/en/latest/examples/vector-wfs.html

[Error] Origin https://openlayers.org is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://ahocevar.com/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=osm:water_areas&outputFormat=application/json&srsname=EPSG:3857&bbox=-8932735.630220866,5370452.51819444,-8885038.924570916,5393383.626679991,EPSG:3857 due to access control checks.
[Error] Failed to load resource: Origin https://openlayers.org is not allowed by Access-Control-Allow-Origin. (wfs, line 0) ....
and so on

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/vector-wfs.html'
2. Console
3. See error

Thanks

**Comment by ahocevar** [comment] 2022-02-21 18:24
This was caused by an outage of ahocevar.com/geoserver and is now fixed. Thanks for the report!

**Closed by ahocevar** 2022-02-21 18:24 UTC
Labels: bug

**Comment by jipexu** [comment] 2022-02-21 18:26
yes i just see is good now thanks !
