### ISSUE TITLE
Multiple Typescript errors with OpenLayers 6.6.1

### ISSUE THREAD

**Issue by gozeller** [openlayers/openlayers#12546] opened 2021-07-22 12:59 UTC
We upgraded OpenLayers from 6.5.0 to version 6.6.1 in our Angular 11 project (and removed the @types/ol dependency). Various compile errors occure in the OpenLayers *.d.ts files:

```
Error: node_modules/ol/ImageBase.d.ts:32:48 - error TS2694: Namespace '"./node_modules/ol/ImageState"' has no exported member 'default'.

32     protected state: import("./ImageState.js").default;
                                                  ~~~~~~~


Error: node_modules/ol/Tile.d.ts:131:47 - error TS2694: Namespace '"./node_modules/ol/TileState"' has no exported member 'default'.

131     protected state: import("./TileState.js").default;
                                                  ~~~~~~~


Error: node_modules/ol/geom/SimpleGeometry.d.ts:27:53 - error TS2694: Namespace '"./node_modules/ol/geom/GeometryLayout"' has no exported member 'default'.

27     protected layout: import("./GeometryLayout.js").default;
                                                       ~~~~~~~


Error: node_modules/ol/source/Cluster.d.ts:110:31 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

110     protected features: Array<Feature>;
                                  ~~~~~~~


Error: node_modules/ol/source/Cluster.d.ts:121:23 - error TS2314: Generic type 'VectorSource<Geometry>' requires 1 type argument(s).

121     protected source: VectorSource;
                          ~~~~~~~~~~~~


Error: node_modules/ol/source/Raster.d.ts:309:5 - error TS2416: Property 'getImageInternal' in type 'RasterSource' is not assignable to the same property in base type 'ImageSource'.
  Type '() => null' is not assignable to type '(extent: number[], resolution: number, pixelRatio: number, projection: Projection) => ImageBase'.
    Type 'null' is not assignable to type 'ImageBase'.

309     getImageInternal(): null;
        ~~~~~~~~~~~~~~~~

```

I think the last one is already mentioned in #12532

**Comment by ahocevar** [comment] 2021-07-22 13:06
Duplicate of #12497, which also provides a solution.

**Comment by gozeller** [comment] 2021-07-22 13:20
````"skipLibCheck": true```` as mentoined in #12497 solved my issue.

**Comment by ahocevar** [comment] 2021-07-22 13:37
Thanks for your feedback, @gozeller.

**Closed by ahocevar** 2021-07-22 13:37 UTC
Labels: bug

**Comment by CarlosBayarri** [comment] 2022-01-19 07:14
The flag "skipLibCheck": true in tsconfig is not a solution, it is a bad practice and it shoul be fixed.

**Comment by alexandrubuhoci** [comment] 2022-01-24 17:59
For me "skipLabCheck": true not work. How to resolve?

**Comment by ahocevar** [comment] 2022-01-24 18:16
@alexandrubuhoci It's `"skipLibCheck": true`, not `"skipLabCheck": true`

**Comment by alexandrubuhoci** [comment] 2022-01-24 18:33
@ahocevar I misspelled...."skipLibCheck". How said before..not work

**Comment by ahocevar** [comment] 2022-01-24 18:38
@alexandrubuhoci Make sure you put it in the `compilerOptions` sections of your `tsconfig.json`.

**Comment by alexandrubuhoci** [comment] 2022-01-24 19:22
![image](https://user-images.githubusercontent.com/63406921/150849815-0de3b3e7-1639-4fbf-a6d9-25d0d5052907.png)

**Comment by wlisesrivas** [comment] 2022-01-24 22:45
I have same issue, I'm trying to upgrade all my packages (angular 13, material 13 etc).
![image](https://user-images.githubusercontent.com/1482092/150877557-f259dbe8-9816-4ac0-a1ba-ee33ae73e8be.png)

**Comment by ahocevar** [comment] 2022-01-24 23:08
I created a minimal repository that shows how to add an OpenLayers map to an application created with `ng new ol-ng`: https://github.com/ahocevar/ol-ng.

This commit is the one that adds the map and the required configuration, including the addition of `"skipLibCheck": true` to the `compilerOptions` section of `tsconfig.json`: https://github.com/ahocevar/ol-ng/commit/4c824c9d540549cdb3a100716dfa0eb973f73305

**Comment by alexandrubuhoci** [comment] 2022-01-25 10:46
@ahocevar I've cloned the repo locally in my PC, served the app and everything goes well!
I think that in my project the reason that Angular shows that errors is because (maybe) the version of Angular is 10.0.8 and the OL version is the latest one.

If i use the OL version 6.5.0 (older) in the same project no errors show up!
For deploying the only solution until now is to use the 6.5.0 versione, otherwise I can't do anything
