### ISSUE TITLE
Minor MVT rendering glitch at equator

### ISSUE THREAD

**Issue by christophfriedrich** [openlayers/openlayers#9174] opened 2019-01-31 16:57 UTC
**Describe the bug**
When displaying MVT areas, at the equator additional lines are being rendered that shouldn't be there.

**To Reproduce**
1. Go to https://jsfiddle.net/christophfriedrich/ey6bhac9/2/
2. Click 'Run'
3. See line within the borders of Kenya that runs along the equator
4. Zoom in with your mouse scroll wheel by one step
5. See the previous line more prominent and even another one within the borders of Uganda

![image](https://user-images.githubusercontent.com/17781682/52070242-4d9dc800-2578-11e9-97df-e1c48f94b332.png)

**Expected behavior**
Just the borders being rendered, no additional non-border lines.

**Guess of cause**
I can imagine this is due to vector tile borders?

**Note**
I'm not 100% sure that this is an OL bug -- could this be to blame on the data/the server that produces the MVTs?

**Comment by bartvde** [comment] 2019-01-31 17:37
Imteresting, I just tried to reproduce this in the Boundless SDK with the ol and mapbox GL renderer, and I couldn't, though it's also using ol 5.3.0

![screenshot from 2019-01-31 18-36-41](https://user-images.githubusercontent.com/319678/52073219-4c27cc00-2587-11e9-9e28-a195b4e0fc84.png)
![screenshot from 2019-01-31 18-36-24](https://user-images.githubusercontent.com/319678/52073220-4c27cc00-2587-11e9-8b6d-e22ca4ce1408.png)

**Comment by christophfriedrich** [comment] 2019-01-31 17:53
Glad that you were able to reproduce something similar with a different dataset.

That white line is at 45°E, strengthening my belief in the theory that it has something to do with vector tile boundaries which are probably to be found at these main intervals (0, 45, 90 etc.)

**Comment by bartvde** [comment] 2019-01-31 17:54
The dataset is the same, I am using the tile service you provided

**Comment by bartvde** [comment] 2019-01-31 18:02
@ahocevar any ideas on this one?

**Comment by christophfriedrich** [comment] 2019-01-31 18:02
Oh okay, I thought so due to your conclusion:
> So I don't think it's the data / server

**Comment by ahocevar** [comment] 2019-01-31 19:21
I‘ll take a look.

**Comment by ahocevar** [comment] 2019-01-31 21:45
That dataset seems to have no buffer at the tile boundaries, i.e. polygons in the source data are clipped exactly at the tile boundaries. OpenLayers transforms the integer tile coordinates into view projection coordinates. That process can lead to rounding differences at the subpixel level. In mapbox-gl-js, the rendering is probably done directly in tile pixel space, so it's less likely there to see these artifacts.

My recommendation would be to create vector tile sets with a buffer around each tile. For linestrings and points it's essential anyway. All tile generators I know actually do apply a buffer by default. It would be interesting to know why that particular tile set does not have a buffer.

**Comment by dbauszus-glx** [comment] 2019-02-04 16:37
We are using [ST_AsMVTGeom()](https://postgis.net/docs/ST_AsMVTGeom.html) to generate the tiles.

This function uses the default buffer size (256). Increasing the buffer size does not seem to have an effect on the OL render output.

**Comment by ahocevar** [comment] 2019-02-05 08:45
To debug this further, you could use a tool like https://github.com/mapbox/mvtview to view a single tile and verify that it has a proper buffer.

**Comment by dbauszus-glx** [comment] 2019-02-06 13:14
I changed the buffer and clip settings in the PostgreSQL query and I am pretty sure that these are changed but mvtview does not show the buffer. Given that mvtview uses mapbox-gl wouldn't that mean that the tile render is done in the tile pixel space and never show buffer geometries?

Increasing the stroke width does seem to fix the problem. With a stroke width of 2 the slivers at equator tile bounds are not rendered. This indicates to me that these render artifacts are not due to a missing buffer.

**Comment by ahocevar** [comment] 2019-02-07 13:06
I did some heavy investigation, and found the reason for the problem: your vector tiles do not follow the [specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4344-polygon-geometry-type) - the winding order is wrong, i.e. the outer ring of the polygon in question is oriented clockwise instead of counterclockwise. It returns a negative area when applying the surveyor's formula.

That said, you can either configure your MVT format with
```js
new ol.format.MVT({featureClass: ol.Feature});
```
or make sure that you output polygons with the correct winding order.

I made the experiments in an updated version of your fiddle: https://jsfiddle.net/bu2dy5te/4/. Click on the polygon in question (which renders correctly now because of the `featureClass` configuration), and look at the console output. You will see that the original order is the reverse of the expected oriented order.

I'm closing this issue, and you owe me at least a beer & burger dinner given the time I have spent on this 😉.

**Closed by ahocevar** 2019-02-07 13:06 UTC

**Comment by dbauszus-glx** [comment] 2019-02-07 13:51
@ahocevar Beer, Burger & Dinner at FOSS4G Bucharest are certainly in order.
