### ISSUE TITLE
Very close zoom in of the viewport disables raster layers rendering if the view projection is different than EPSG:3857.

### ISSUE THREAD

**Issue by jmekaelthas** [openlayers/openlayers#10190] opened 2019-10-24 19:14 UTC
**Describe the bug**
I have a map with OSM layer. I zoom in the view really close (up to scale 1:1) and quickly zoom out. Everything works fine when the view's projecttion is EPSG:3857. When I change it to anything else and zoom in and immediately zoom out, the OSM layer stops responding. No more tiles appear on the screen any longer. This affects all raster layers. Vectors still work fine.

**To Reproduce**
1. Open one of the official examples: https://openlayers.org/en/latest/examples/reprojection.html
2. Change view projection to EPSG:4326.
3. Zoom in really really close.
4. Zoom out before the tiles begin to load.

**Expected behavior**
I expect that when I zoom out the tiles will continue to appear on the map.

**Comment by bearman987** [comment] 2019-10-30 08:33
It's a serious bug. Not fixed in the latest version.
Quick use of the mouse wheel to zoom in and then zoom out blocks tile reading.

**Comment by ahocevar** [comment] 2019-10-30 09:34
Duplicate of #10199.

**Closed by ahocevar** 2019-10-30 09:34 UTC
