### ISSUE TITLE
After updating our OL version we're experiencing unwanted clustering

### ISSUE THREAD

**Issue by WilCodeBoer** [openlayers/openlayers#7517] opened 2017-11-27 10:59 UTC
Greetings OL creators, 

I've checked all the issues to see if a similar problem was happening, but found only questions about clustering when using it. 

So here goes. We've recently updated our ol from 4.4.2 to 4.5.0 and after this change we are getting unwanted clustering on our feature layers, which baffles me because our featrue layer setup is quite simple

``` javascript 
var layer = new ol.layer.Image({
            source: new ol.source.ImageVector({
                projection: undefined,
                source: new ol.source.Vector({
                    features: featureCollection
                })
            })
        });
```

And that's it. I cant for the love of me figure out why our features are getting clustered. 

If I change the layer to a Vector later with the vector source directly in it it stops clustering but this also takes up alot more preformace

Is there anything that can be done about this? Is this a bug or?

Best regards, 
WilCodeBoer

**Comment by ahocevar** [comment] 2017-11-27 11:27
Maybe the same issue as #7487?

**Comment by WilCodeBoer** [comment] 2017-11-27 12:31
Looks like it is

**Comment by ahocevar** [comment] 2017-11-27 17:06
Closing as duplicate of #7487. Note that #7501 provides a new way of rendering vector layers as images, which does not have this issue.

**Closed by ahocevar** 2017-11-27 17:06 UTC
