### ISSUE TITLE
Interactive Overview

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [openlayers/openlayers#3753] opened 2015-06-01 13:53 UTC
It would be great if the overview could be used to zoom and navigate the target layer.

Desirable interactions:
- click the overview to center the target layer on that point
- double-click the overview to center and zoom in the target layer
- drag the extent box on the overview to pan the target layer

See example here: http://www.zoomify.com/assets/dynamic/2-View-Preset.htm

**Comment by adube** [comment] 2015-06-01 18:28
This would be very nice indeed.  If you're willing to work on a PR, I'd be happy to review it before any core ol3 dev does.

**Comment by Dissonant-Tech** [comment] 2015-06-05 12:34
This should be possible by added the necessary interactions (drag, click, etc...) to the OverviewMap's `ol.Map`, [initialized here](https://github.com/openlayers/ol3/blob/v3.4.0/src/ol/control/overviewmapcontrol.js#L104-L108). As well as binding the views together. Currently the OverviewMap's view is [bound to the main map's](https://github.com/openlayers/ol3/blob/v3.4.0/src/ol/control/overviewmapcontrol.js#L205) but not vice-versa.

I'm currently having problems building ol3 so I can't really make a pull request, or even test these changes, but if anyone else should attempt this hopefully this information will help.

**Comment by jhwegener** [comment] 2015-06-12 08:33
@Dissonant-Tech what are your problems with building ol3? perhaps you can post a patch anywhere else, so i can test it?

**Comment by Dissonant-Tech** [comment] 2015-06-12 15:21
@jhwegener I was just having a dependency issue. After cloning ol3 a couple times the issue is resolved and I can build just fine.

The only problem now is one of free time. A quick and easy solution would be to add a `getOverviewMap()` API call that will just return `this.ovmap_`. That should allow anyone to add the appropriate interactions and bindings in their own code.

**Comment by jhwegener** [comment] 2015-06-15 06:35
@Dissonant-Tech ok, thx for clarification

**Comment by christopheblin** [comment] 2015-06-16 09:17
I am also interested in this issue and the same functionnalities.
You can see #3809 for a start of implementing dragging directly inside the OverviewMapControl.
Providing only getOverviewMap is not sufficient since you will also need access to the box and eventually to the overlay...

Currently, I have no intention to build OL3 so I started a new control from scratch, without using goog and other fancy stuff. If you are interested, you can contact me.

**Comment by christopheblin** [comment] 2015-06-22 09:37
Also, someone has a pretty working example : http://ol3.qtibia.ro/build/examples/overviewmap-custom-drag.html

**Comment by felixveysseyre** [comment] 2016-07-21 12:51
@adube @Dissonant-Tech @christopheblin 

Hi, I found this issue while I was looking for an interactive OverviewMap for OL3.

It is been a year since the last message on this issue, do you know if things have changed ? Is OL3 will soon provide a native interactive OverviewMap ?

Thanks,

**Comment by jonataswalker** [comment] 2016-09-12 16:40
@geoffroy-noel-ddh @Dissonant-Tech @christopheblin 

I gave it a try and [here's](https://github.com/jonataswalker/ol3-interactive-overview) the start of a future plugin.

**Comment by felixveysseyre** [comment] 2016-09-16 14:27
I have created a pull request for this subject: https://github.com/openlayers/ol3/pull/5887

Feel free to take a look !

**Comment by jhwegener** [comment] 2017-03-08 13:29
Nice work @felixveysseyre 
Hope it will be merged soon!?

**Comment by felixveysseyre** [comment] 2017-03-09 12:42
@jhwegener Thanks !

I hope yes, but it's out of my hands unfortunately :(

**Comment by jhwegener** [comment] 2017-03-27 08:31
I think the pull request is merged?! Perhaps someone can close this issue now?

**Closed** 2017-03-27 08:33 UTC
