### ISSUE TITLE
ol.source.Zoomify based layer is not displayed

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#6519] opened 2017-02-20 11:25 UTC
I have 2 images with different sizes (tile size is the same). Images correspond to each other and I want to display them one on another the way that second image is upscaled to correspond first one.
I use ol.source.Zoomify source for both of them and projections with transformations. But I even can't get second image displaying.

See the the sample code in jsFiddle [here](http://jsfiddle.net/sk5cLj4n/37/)
Short explanation of the fiddle: 
- tiles with blue borders are for primary layer
- tiles with black borders are for secondary layer (overlay)
- only 3 zoom levels are available for zooming
- currently projections transformation does nothing. That's just for simplification. There should be a mupliplication to stretch second image.

**Comment by ahocevar** [comment] 2017-02-20 12:16
Duplicate of #6384.

**Closed by ahocevar** 2017-02-20 12:16 UTC

**Comment by hajjimurad** [comment] 2017-02-20 16:14
Actualy I was using the fresh version 4.0.0 where projection property works fine. 
The problems was about proper setting of the extent for Projection (extent: [0, -height, width, 0])
I found it by your link above. So, thanks anyway.
