### ISSUE TITLE
Missing tiles in WebGLTileLayer with a GeoTiff source

### ISSUE THREAD

**Issue by shandruha** [openlayers/openlayers#15804] opened 2024-05-07 07:20 UTC
**Describe the bug**
After reprojecting GeoTiff tiles into a stereographic projection, tiles near the antimeridian are not rendered. 
The sizes of the resulting black gaps (please see the picture below) depend on the sizes of source tiles and zoom.

![image](https://github.com/openlayers/openlayers/assets/50118328/55d29e8f-0248-4492-b28f-2825f2f6803e)

**To Reproduce**
1. Download the geotiff sample image (zipped): 
[202404152030.zip](https://github.com/openlayers/openlayers/files/15231597/202404152030.zip)

2. Initialize WebGLTileLayer:
```
new WebGLTileLayer({
     source: new GeoTIFF({sources: [{url: url}], crossOrigin: 'anonymous', transition: 0, normalize: true}),
     name: 'segments',
     zIndex: 2,
     cacheSize: 2048,
     preload: 0,
     isActive: true
})
```
3. Register a stereographic projection
```
proj4.defs('stereo-sib', '+proj=stere +lat_0=49 +lat_ts=-73 +lon_0=90 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');
register(proj4);
```
4. Initialize View
```
const view = new View({
  projection: getProjection('stereo-sib'),
  center: fromLonLat([-175.63918171041328, 54.36175564445709], defaultProj),
  zoom: 5.370370380181835,
  minZoom: 4
});
```
5. Observe.

**Expected behavior**
There should be no missing tiles aroung the antimeridian.

**Comment by mike-000** [comment] 2024-05-07 12:08
Your source tiles overflow the tile grid extent and the validity extent of the EPSG:4326 projection which is causing a problem as it is defined as a global projection.

In your application a workaround would be to define the built-in  projection as non-global

    const epsg4326 = getProjectiont('EPSG:4326');
    epsg4326.setGlobal(false);

or hardcode the source projection as a non-global copy of the projection

    projection: new Projection({
      code: epsg4326.getCode(),
      units: epsg4326.getUnits(),
      extent: epsg4326.getExtent(),
      axisOrientation: epsg4326.getAxisOrientation(),
      global: false,
      metersPerUnit: epsg4326.getMetersPerUnit(),
      worldExtent: epsg4326.getWorldExtent(),
      getPointResolution: (resolution, point) => getPointResolution(epsg4326, resolution, point),
    })


Using your source tile grid in a reprojected `ol/source/TileDebug` does not have the same problem, but with DataTiles as in https://openlayers.org/en/latest/examples/data-tiles.html it does, so a fix in DataTile reprojection should be possible.

**Comment by shandruha** [comment] 2024-05-07 15:43
@mike-000, thanks!
I've tried to use the proposed workaround, and indeed the map looks much better now.
However, there are still some minor artifacts. Is there a way to get rid of them quickly?

**Comment by mike-000** [comment] 2024-05-08 09:07
That can also be seen with a canvas layer using your tile grid, and a semi transparent fill - there are transparent artefacts at the reprojection triangulation edges either side of the antemeridian which are not present in the underlying OSM source.  I think it is due to the final source pixel column not being precisely aligned to the antemeridian.

![image](https://github.com/openlayers/openlayers/assets/49240900/8e6e5d5b-b44c-4427-b615-de33a96f19d6)

**Comment by mike-000** [comment] 2024-05-09 22:42
#15815 is a potential fix for this which avoids having to change the projection.

Artefacts are reduced from

![image](https://github.com/openlayers/openlayers/assets/49240900/31a6cb74-71a6-4539-a4b8-61b96f795494)

to

![image](https://github.com/openlayers/openlayers/assets/49240900/68407bea-180b-4acd-ab56-b03e7cfd1a7b)

but not eliminated.  Artefacts can also be seen when using

```
  new GeoTIFF({
    sources: [
      {
        url: 'https://s2downloads.eox.at/demo/EOxCloudless/2020/rgbnir/s2cloudless2020-16bits_sinlge-file_z0-4.tif',
        bands: [1, 2, 3],
        min: 0,
        max: 3000,
      },
    ],
  }),
```

with the same projection.  In that case the tiles exactly fit the projection extent so misaligned pixel columns is not the cause.

**Closed** 2024-05-15 13:14 UTC
Labels: bug
