### ISSUE TITLE
ol6  vector tile  label  flicker

### ISSUE THREAD

**Issue by lzp0070007** [openlayers/openlayers#10169] opened 2019-10-23 02:14 UTC
when  I use ol6 ， zoom the map,  the vector tile label  flicker,why this hapeen,Any help from you will be greatly appreciated!

**Comment by ahocevar** [comment] 2019-10-23 07:05
Can you share your code? I am not seeing this in the official examples, e.g. https://openlayers.org/en/latest/examples/mapbox-style.html.

**Comment by lzp0070007** [comment] 2019-10-23 07:58
![bandicam 2019-10-23 15-13-44-407](https://user-images.githubusercontent.com/5045130/67370822-f6300400-f5ad-11e9-9dc2-f447bb4076c6.gif)

**Comment by ahocevar** [comment] 2019-10-23 09:58
That happens during tile loading. As new higher resolution tiles become available, all labels run through the decluttering process, and the resulting labels may change. There is nothing at the moment you can do about this, but I'll leave this ticket open as your concern is valid.

**Comment by lzp0070007** [comment] 2019-10-23 10:34
but why this not happen in ol5?

**Comment by ahocevar** [comment] 2019-10-23 10:36
In v5 we did not use lower resolution tiles that much. So it should also have happened in v6, but not that frequently.

**Comment by lzp0070007** [comment] 2019-10-24 01:15
Thank you for your response

**Comment by yiwenzhang666999** [comment] 2020-03-19 08:30
hi @ahocevar Is there a solution to this problem? The text flickers when zooming the map, making people feel dizzy.

**Comment by ahocevar** [comment] 2020-03-19 08:48
#10819 may have a solution for you. But it may also be the problem described here. It really depends on the way you style your features.

**Comment by yiwenzhang666999** [comment] 2020-03-19 11:37
hi@hocevar I don't quite understand what you mean, what does this have to do with feature style

**Comment by ahocevar** [comment] 2020-03-19 14:49
@yiwenzhang666999 It *may* have to do with it, if the decluttering algorithm cannot group labels and point symbolizers that belong together.

**Comment by yiwenzhang666999** [comment] 2020-05-18 23:46
hi @ahocevar After I removed all the point symbolizers from the style file, the map labels did not flicker, but I don’t know where to modify the decluttering algorithm, can you give some suggestions  or can you fix this bug?

**Comment by ahocevar** [comment] 2020-05-19 07:51
This might be the same issue as #10819, which I'm currently looking into.

**Comment by yiwenzhang666999** [comment] 2020-06-02 07:27
hi @ahocevar Is this problem likely to be solved? I read the source code and I really don’t know where the problem is.

**Comment by ahocevar** [comment] 2020-06-02 07:58
This is a tough one, but I'm still on it and willing to solve it.

**Comment by yiwenzhang666999** [comment] 2020-06-02 08:10
Thank you for your reply and your outstanding work.

**Comment by yiwenzhang666999** [comment] 2020-06-11 10:53
hi@ahocevar Is there any new progress on this issue？

**Comment by yiwenzhang666999** [comment] 2020-06-11 11:35
hi@ahocevar Does this problem still exist in this development version 6.3.2-dev.1591611972232?
Because I still had the flicker problem when I tested this version, I still want to upgrade ol-mapbox-style at the same time. My current olcs version is 5.0.2

**Comment by MoonE** [comment] 2020-06-11 12:08
#11148 is not merged, so it is not fixed in the dev version yet. If you want to test it you have to get it directly from https://github.com/ahocevar/openlayers/tree/vectortile-label-flicker.

It fixed the flickering issue in my application.

**Closed** 2020-06-13 06:28 UTC
