### ISSUE TITLE
GeoTIFF sources cannot be reprojected

### ISSUE THREAD

**Issue by otfried** [openlayers/openlayers#14313] opened 2022-11-17 16:36 UTC
**Describe the bug**

Openlayers [normally](https://openlayers.org/doc/tutorials/raster-reprojection.html) has the ability to show sources in any projection - the view projection does not need to be related to the source projection.

This does not seem to work at all for GeoTIFF sources, and leads to the following mysterious assertion failure in the console:
```
Uncaught AssertionError: A VectorTile source can only be rendered if it has a projection compatible with the view projection
    AssertionError AssertionError.js:77
    assert asserts.js:12
    getTileCacheForProjection Tile.js:285
```
This is mysterious because no VectorTile sources are involved at all.

**To Reproduce**
Here is a minimal example, using the geotiff file from the [cog-blob](https://openlayers.org/en/latest/examples/cog-blob.html) example:
```
import './style.css';
import {Map, View} from 'ol';
import TileLayer from 'ol/layer/Tile';
import WebGLTileLayer from 'ol/layer/WebGLTile';
import OSM from 'ol/source/OSM';
import GeoTIFF from 'ol/source/GeoTIFF';
import proj4 from 'proj4';
import {register} from 'ol/proj/proj4';

proj4.defs("EPSG:25832",
	   "+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");
proj4.defs("EPSG:32632","+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs +type=crs");
register(proj4);

const viewA = new View({
  projection: "EPSG:32632",
  center: [ 466430, 5762720],
  resolution: 25.6,
});

const viewB = new View({
  projection: "EPSG:25832",
  center: [ 466430, 5762720],
  resolution: 25.6,
});

const viewC = new View({
  projection: "EPSG:3857",
  center: [ 947177, 6802931],
  resolution: 25.6,
});

const map = new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
  ],
  view: viewA,
});

fetch('https://openlayers.org/en/latest/examples/data/example.tif')
    .then((response) => response.blob())
    .then((blob) => {
      const geotiff = new GeoTIFF({
	sources: [
          {
            blob: blob,
          },
	],
      });
      const geolayer = new WebGLTileLayer({
	source: geotiff,
      });
      map.getLayers().push(geolayer);
    });
```
This version works fine - it shows OSM and the image on top of it.

If you change the view in the `Map` constructor to `viewB`, it still shows OSM and the image on top, but spits out lots of assertion errors.

If you then change the view in the `Map` constructor to `viewC`, the image is no longer shown at all (and there is no console output).

**Expected behavior**
I would like this to work as expected, with the GeoTIFF source being reprojected to the view projection.

If the current behavior is the intended behavior, then it needs to be documented in the API documentation for the `GeoTIFF` class that this source will only work when the view projection matches the projection of the GeoTIFF file.   And the error message should be rewritten so that it doesn't refer to `VectorTile`.

**Comment by mike-000** [comment] 2022-11-17 17:52
It will be in the next release and is already available in dev versions
https://openlayers.org/en/main/examples/geotiff-reprojection.html
https://openlayers.org/en/main/examples/multiple-cogs.html

**Comment by pelord** [comment] 2022-11-22 20:51
What is the fix for this issue. I have the same problem but not reproductible in the demo.. (i dont fully understand how it's happening). I do not work with vectortiles.. This assert is raised on wms source image.

**Comment by mike-000** [comment] 2022-11-22 23:49
To use viewC you will need to build with the dev version (currently 7.1.1-dev.1669138178783)
https://codesandbox.io/s/cog-blob-forked-qvmskx?file=/package.json
The GeoTIFF  is reprojected so the message will now only appear if you try to reproject vector tiles.

**Comment by julienrf** [comment] 2023-08-03 13:24
I think this issue should be closed since the fix is now available in stable releases.

**Closed** 2023-08-03 17:01 UTC
Labels: bug
