### ISSUE TITLE
ImageWMS source error after upgrading from v7.5.2 to v8.0.0

### ISSUE THREAD

**Issue by koltai75** [openlayers/openlayers#15097] opened 2023-09-08 18:55 UTC
I have recently tried to upgrade OpenLayers from version 7.5.2 to 8.0.0.

I face an error when OpenLayers tries to load the images from the WMS source. The `load` function in `Image.js` catches an exception in line 190:

```
Image.js:190 DOMException: The source image cannot be decoded.
```

Strange thing is when I look at the request to my GeoServer, it comes back with `200 OK`, and I even see the PNG data in the response. Without changing anything else, and going back to v7.5.2, everything works fine. I also tried v8.1.0, the result is the same.

A have carefully studied the migration notes, and found nothing that could be related to this error.

**Comment by ahocevar** [comment] 2023-09-08 18:58
Duplicate of #15093, and the fix is in `ol@dev` already.

**Comment by koltai75** [comment] 2023-09-08 19:05
@ahocevar thanks, I will try it and get back to you.

**Comment by koltai75** [comment] 2023-09-09 06:52
@ahocevar I tried the fix in [#15094](https://github.com/openlayers/openlayers/commit/4fc0a26edc6bb7e4cafa1d38e4ce3e3d78091ef6). For me, the result is the same, I still get the `DOMException: The source image cannot be decoded`.

**Comment by ahocevar** [comment] 2023-09-09 07:36
Ok @koltai75, then this must be a different issue. Would you be able to share a minimal example to reproduce the problem you're seeing?

**Comment by mike-000** [comment] 2023-09-10 13:47
There is a regression of #13073 which could explain this and is reproduceable with ImageStatic on Windows 10 (64bit 8GB) and Chrome https://codesandbox.io/s/static-image-forked-rcl9wn?file=/main.js  Change `load` to `decode` (or use `ol/source/ImageStatic`) to see the error.  On the same device Firefox works as expected.

**Closed** 2023-09-10 21:43 UTC
Labels: bug

**Comment by koltai75** [comment] 2023-09-11 05:56
@ahocevar @mike-000 Thank you both. I can confirm that the error is gone with the current code and it works as before.
