### ISSUE TITLE
Font Icon rendering still broken

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7885] opened 2018-02-24 02:08 UTC
The Font Icon rendering problems appeared with 4.4.0. I opened https://github.com/openlayers/openlayers/issues/7675 which we thought was fixed by https://github.com/openlayers/openlayers/pull/7676.

Now I had the time to migrate our app to OL5 beta, to find out if the fix works or not, and unfortunately it does not, or it only partially fixed it.

Now, I don't know how can I create a CodePen or something similar for OL5 beta, so I'm sharing the minimal code here for an OL5 example.

```html
<!doctype html>
<html>
<head>
    <link href="https://openlayers.org/en/master/css/ol.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <div id="map"></div>
    <script src="http://localhost:3000/static/js/bundle.js"></script>
</body>

</html>
```

```js
import Feature from 'ol/Feature'
import Point from 'ol/geom/Point'
import TileLayer from 'ol/layer/Tile'
import VectorLayer from 'ol/layer/Vector.js'
import Map from 'ol/Map'
import OSM from 'ol/source/OSM'
import VectorSource from 'ol/source/Vector.js'
import Style from 'ol/style/Style'
import Text from 'ol/style/Text'
import View from 'ol/View'

var iconFeature = new Feature({
  geometry: new Point([0, 0]),
})

iconFeature.setStyle(
  new Style({
    text: new Text({
      text: '\uF013',
      font: 'normal 30px FontAwesome',
    }),
  })
)

var vectorSource = new VectorSource({
  features: [iconFeature],
})

var vectorLayer = new VectorLayer({
  source: vectorSource,
})

var rasterLayer = new TileLayer({
  source: new OSM(),
})

window.map = new Map({
  layers: [rasterLayer, vectorLayer],
  target: 'map',
  view: new View({
    center: [0, 0],
    zoom: 6,
  }),
})
```

This produces the rectangle for me.

However, there is something extremely interesting happening here. If I insert
```
<i class="fa fa-copyright"></i>
```
Anywhere in the HTML, then the OL canvas font rendering also works. Something like if the browser needs to load the font on a DOM element before OL can use it. But before 4.4.0 OL didn't need this.

//cc: @ahocevar

**Comment by ogo-adp** [comment] 2018-02-27 09:51
We have the same problem (please see #7334). This is caused by sync font loading + image caching

We are also stuck with pre 4.4 version

Also the new rendering with images does not improve performance (in my opinion nothing can beat the font renderer of a browser -I gave measures in #7334 but could not convince the OL team to go back-). Also I do think that rendering with images can break font smoothing or cleartype .

**Comment by hyperknot** [comment] 2018-02-27 10:19
@ogo-adp while seems to be a fragile solution (doesn't seem to work 100% of the time), at least I got good results by including any character on the page in HTML. Like

```
<i class="fa fa-copyright"></i>
```

Can you try if this works for you as well? 

But I agree that this bug needs to be ironed out, I think using icon symbols on a map must be quite common.

**Comment by ahocevar** [comment] 2018-02-27 12:25
Issue confirmed. The best way to do something like a CodePen with ES modules is https://codesandbox.io/. I have created a sandbox with the code above: https://codesandbox.io/s/k369kj1pp7.

See #7902 for a fix. I'll publish another beta when that is reviewed and merged.

**Comment by hyperknot** [comment] 2018-02-27 12:39
@ahocevar thanks for the swift solution! CodeSandbox looks really nice, will the examples on the homepage be turned into CodeSandboxes?

**Closed** 2018-02-27 12:39 UTC

**Comment by ahocevar** [comment] 2018-02-27 12:50
CodeSandbox updated to ol 5.0.0-beta.8, to show the fix.

@hyperknot We're looking into ways to make the examples editable in CodeSandbox. It's definitely our preferred option for the 5.x website.

**Comment by hyperknot** [comment] 2018-02-27 13:09
Thanks, I can confirm that beta.8 fix works well!
