### ISSUE TITLE
Move from goog.provide/goog.require to ES modules

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#5623] opened 2016-07-21 11:36 UTC
This ticket is the place to discuss the way forward on the transition to ES2015 (ES6) modules, and continues the discussion from #4128 now that the removal of the Closure Library dependency is (almost) complete.

**Comment by probins** [comment] 2016-07-21 12:12
move via `goog.module`? #5226

**Comment by gberaudo** [comment] 2016-07-21 12:43
Sorry I have been very busy and could not find the time yet to cleanup the work on #5226 and the branch https://github.com/gberaudo/ol3/commits/goog_modules so that we can address the last issues (inheritance, generation of the jsdoc). My intent is to have a small script to easily compare the result of jsdoc with and without goog.module changes.

I have an updated WIP branch at https://github.com/gberaudo/ol3/tree/goog_modules_squashed_rebased/test_doclets; and the scripts are at https://github.com/gberaudo/ol3/tree/goog_modules_squashed_rebased/test_doclets. Run with `test_doclets/run.sh && test_doclets/compare.sh`.

**Comment by tschaub** [comment] 2016-08-03 16:02
Perhaps as a stop-gap (and maybe just a distraction), I've opened #5679 - this would let us have a release that worked with our current build/doc tools *and* worked with mainstream CommonJS tools.

I'm in favor of authoring as ES2015 modules, and there may be work that could be done that is relevant to both this ticket and #5679 (making sure we are consistent with file naming, talking about default exports, considering if we can get rid of some named exports/provides).

**Comment by probins** [comment] 2016-09-02 18:20
what's the general feeling on priorities here? Is there agreement that this is best tackled as part of a new OL4 with a different (though probably similar) API? If so, is this something that should be the focus of development from now on (my preference), or continue to focus on OL3 with OL4 something for the longer term, say in a year or two's time? Concentrate on evergreen browsers, and drop support for IE? Convert the code to ES6? If so, as a general rewrite, or in a more incremental way, changing only when being changed for something else? Continue to use JSDOC comments for types and GCC for checking those types? Continue to define the API in terms of GCC (compile-time) exports, or some other way?

Lots of questions :-)

**Comment by ahocevar** [comment] 2016-09-02 18:35
For quick results that satisfy the majority of today's JavaScript usage, finishing #5679 (i.e. provide a set of CommonJS friendly set of modules with every release) is my preferred option. When that is done, we can move on incrementally as we see fit.

**Comment by probins** [comment] 2016-09-15 10:30
looks to me as though this might be a good use of the new 'Projects' that Github has just introduced

**Comment by marcjansen** [comment] 2016-09-15 13:00
You're talking about [this](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) or [this](https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/), right, @probins?

**Comment by probins** [comment] 2016-09-15 13:12
yes

**Comment by probins** [comment] 2017-08-28 10:36
So what's the plan here?

I've been experimenting with the browser ES-module loaders that are currently being implemented (Safari 11's should be complete, and Chrome's static loader should start moving to the stable channel next week; I assume that FF/Edge won't want to be too far behind). #7181 (and a couple of other recent PRs) seems to be working towards the ES-module goal, so it would be good to have an overview of how people see the project progressing.

I've set up a browser-compatible version of the source and the current examples at https://github.com/probins/oles, and listed the issues as I see them (probably not complete) on that repo. Most of these examples work in module-capable browsers, but not very satisfactorily, as they are all using `Map`, which loads 2 renderers and a lot of other unnecessary code. So most of them should be changed to use `PluggableMap` instead. This still leaves a lot of unnecessary code, so my view is that the code needs restructuring/refactoring so apps can import what they need rather than relying on compile/build tools to remove bits they don't need. ISTM the way to do that is to expand the base class concept to other classes: for example, have a base `View` which does not include `fit()` (and so does not require vectors) or the animation code (which should be an optional extra). The current require of `View` in `PluggableMap` should then be removed so apps can instead import BaseView together with `fit` and/or `animation` modules as needed; `View` can be kept in `Map` for bc.

I can add/move my issues to the OL repo, but I think it's better if they're kept separate from the normal bug reports (either in a separate repo or perhaps using labels/milestones/projects). I want to start work on restructuring the code to improve the browser experience, but there are limits to what I can do with codemods. So it would be better to work on PRs for the OL repo (unless I fork the code). The problem is, once you've got used to the simplicity of using ES modules, it's hard to work up enthusiasm for going back to `goog.require` and the requirements of advanced compilation; OL is the only project I know of which uses this, and it's hard to remember what I have to do to get the compiler to compile correctly.

So I'm thinking that one possibility would be to turn the codemod round: instead of having a script which converts `goog` to ES modules, change the source to ES modules and have a similar script which converts to `goog` namespaces, compatible with current apps. Once the ES version is fully functioning, both in the browser and for those who want to continue building a traditional script, the `goog` version can be deprecated and given an end of life, with developers recommended to use ES instead.

**Closed** 2017-12-12 14:05 UTC
