### ISSUE TITLE
update6.4.3 Problem

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/openlayers#11432] opened 2020-08-12 09:58 UTC
When I upgraded from 6.3.2 to 6.4.3 and rebuilt the index file of ol.js, the package /ol/render/canvas/hitdetet could not be found. I don't know what went wrong?
![QQ图片20200812175122](https://user-images.githubusercontent.com/31643589/90002568-65095580-dcc5-11ea-9859-abec6068517c.png)

**Comment by M393** [comment] 2020-08-12 10:33
Looks like there is a typo in the module, should be called `hitdetect` with a `c`:
https://github.com/openlayers/openlayers/blob/f0170f378f2f4b2f6811087f88e9417386644010/src/ol/render/canvas/hitdetect.js#L1-L3

**Comment by yiwenzhang666999** [comment] 2020-08-13 01:27
hi @M393 ,thanks you very much,There is indeed a typo in the module

**Comment by fredj** [comment] 2020-08-13 08:50
Thanks for the bug report and having found the issue; will be fixed with #11433

**Comment by yiwenzhang666999** [comment] 2020-08-14 07:26
After upgrading to v6.4.3, an error is reported when loading vector tiles
![QQ图片20200814152148](https://user-images.githubusercontent.com/31643589/90224584-762ba100-de42-11ea-9043-73002e8da895.png)

**Comment by M393** [comment] 2020-08-14 07:41
Looks like you are using https://github.com/openlayers/ol-mapbox-style ?
You need to make sure it is compiled against openlayers 6.4, The getScaleArray function is new with this version.
Are you including ol.js and olms.js in your website?

**Comment by yiwenzhang666999** [comment] 2020-08-14 10:47
I use ol6.4.3 and ol-mapbox-style6.1.2, i including ol.js and olms.js in my application

**Comment by M393** [comment] 2020-08-14 11:21
Try changing the required ol version in package.json of ol-mapbox-style, then run `npm install` again to get an updated olms.js

```js
  "peerDependencies": {
    "ol": "^6.4.3"
  },
  "devDependencies": {
    ...
    "ol": "^6.4.3",
```

**Comment by yiwenzhang666999** [comment] 2020-08-14 11:27
thank you,i try it

**Comment by ahocevar** [comment] 2020-08-14 18:47
This is a version mismatch problem, in this case probably caused by the legacy build of ol-mapbox-style. We recommend not to use the legacy build of OpenLayers or ol-mapbox-style. I'll comment on https://github.com/openlayers/ol-mapbox-style/issues/290 about the cause for this problem, and am closing this issue because it is not an OpenLayers issue.

**Closed by ahocevar** 2020-08-14 18:47 UTC
