### ISSUE TITLE
Fallback value for GET style expression

### ISSUE THREAD

**Issue by tomasgreen** [openlayers/openlayers#15699] opened 2024-04-03 11:04 UTC
**Is your feature request related to a problem? Please describe.**
Without a fallback value the GET expression has a tendency to break the whole application, especially if features are being added in multiple places in your code without being properly vetted by the layer rendering them.

**Describe the solution you'd like**
I would like to be able to perform the following:

```js
{
   'fill-color': ['match', ['get', 'hover', 'I guess we cant remove the typehint?', 0], 1, '#ff3f3f', '#006688']
}
```

**Comment by tschaub** [comment] 2024-04-03 13:05
Check out [the vector layer example](https://openlayers.org/en/latest/examples/vector-layer.html).  It makes use of the `string` expression that evaluates to its first string argument.  The [OSM vector tiles example] (https://openlayers.org/en/latest/examples/osm-vector-tiles.html) uses the `number` expression that does the same thing for numeric values.  You can also make use of the `coalesce` expression if you don’t know the type that might be returned.

This is a duplicate of https://github.com/openlayers/openlayers/issues/15490.  The remaining work to be done is to improve the documentation (`string` and `number` are missing).

**Comment by tomasgreen** [comment] 2024-04-03 19:46
Thanks! I tried using a number of different expressions before I posten but found none to work. Perhaps I'm missing something, but the following expression should work, right? :)

```js
{
	'fill-color': ['coalesce', ['get', 'COLOR'], [255, 255, 255, 0.6]],
}
```
I get `Uncaught Error: No compiler defined for this operator: "coalesce"`

**Comment by tschaub** [comment] 2024-04-03 20:13
@tomasgreen - Unfortunately there is not parity across the renderers in terms of style expression support.  The `coalesce`, `string`, and `number` operators are currently only supported in the Canvas 2d renderer.  I've noted this in the documentation changes in #15700.  I've created #15701 to track support for these operators in WebGL.

**Closed** 2024-04-04 12:03 UTC
Labels: feature request
