### ISSUE TITLE
Missing removeFeatures to remove  array of selected features?

### ISSUE THREAD

**Issue by kramcore** [openlayers/openlayers#8274] opened 2018-06-15 18:52 UTC
Where did the removeFeatures([]) go from OL2? Is there an alternative way of removing all selected features from the source? Like the example below.
```
var removeF = [];
Features.forEach(function(feature){
 if(feature.values_.name == tSelectedFeatureToRemove)
 {
   // push every features that needs to be removed..
    removeF.push(feature);
 }
});
// Remove it in one go..
// .removeFeatures() is an e.g (no longer exist in OL4)
Feature.removeFeatures(removeF );
```

Doing something like this doesn't seems right specially when removing lots of features/markers from the source.

```
Features.forEach(function(feature){
      if(feature.values_.name == tSelectedFeatureToRemove)
      {
        // slow removing process as it removes a single feature from the source...
        Feature.removeFeature(feature);
      }
    });
```

**Comment by fredj** [comment] 2018-06-18 10:38
Duplicate of #2011

**Closed by fredj** 2018-06-18 10:38 UTC
