### ISSUE TITLE
iOS: Canvas area exceeds the maximum limit

### ISSUE THREAD

**Issue by ninaDeimos** [openlayers/openlayers#9166] opened 2019-01-29 13:56 UTC
We are developing an application with multiple layers with quite a lot of data on each layer.

We have a mechanism in place which increases the amount of tiles loaded and cached when rendering the map. This mechanism just increases the extent for which tiles are loaded by a factor between 1 and 3 in order to create a smoother panning experience.

But the higher the mentioned factor is, the more often when rotating the map, I get the message:
**'Canvas area exceeds the maximum limit (width * height > 16'777'216)'**
even though the canvas size (height/width) is always the same and less than the number in the warning (I checked that via Safari debugging).
And sometimes when I get this message, I get a white screen. Sometimes all WMS layers disappear instantly, sometimes they disappear one after the other, all within half a second.
It also happens sometimes when zooming, although less frequently.

Sometimes I'm able to get the layers back quickly by zooming in or out, sometimes I'm not.

If the mentioned factor is 1 (loaded extent is not increased), I don't experience any problems.

I tested this only on iPads.

Unfortunately our WMS sources are not public, so I can't setup a jsfiddle or anything like that.

**Comment by mprins** [comment] 2019-01-29 15:52
seems a duplicate of #8956

**Comment by ahocevar** [comment] 2019-01-29 16:41
No, that's a different issue. Browsers have a limit for the maximum canvas size. OpenLayers until after v5.3 used to have a target canvas that all layers were composed to.

However, we have changed the renderer to use DOM composition, so we do not need a target canvas anymore. The target canvas was the one that exceeded the size, so what you tried to do should work with master.

**Comment by ninaDeimos** [comment] 2019-01-30 07:35
Thanks for the quick response! I will give it a try.

**Comment by ninaDeimos** [comment] 2019-01-31 13:37
Ok, I tried it, and it's working so far.
Only thing is that I had to decrease the cacheSize of my WMS-layers quite a lot (to 32) as I was getting some "Total canvas **memory** use exceeds the maximum limit" warnings that I'm not getting currently with v5.3.0 and a cacheSize of 512.

Is there any ETA on the next release?

**Comment by ahocevar** [comment] 2019-02-01 08:12
v6.0.0 is scheduled for February.

**Comment by ahocevar** [comment] 2019-02-01 08:13
Can we close this issue?

**Closed** 2019-02-01 08:14 UTC

**Comment by esseb** [comment] 2019-03-05 13:20
@ahocevar I believe this issues should be reopened. I hit this issue easily with the map I'm developing on https://www.yr.no/en/map/radar/1-72837/Norway/Oslo/Oslo/Oslo

In the next version of our map (https://beta.yr.no/nb/kart/v%C3%A6r/1-72837/Norge/Oslo/Oslo/Oslo) I've done my best to optimize our usage of OpenLayers, preferring e.g. `ol/source/ImageCanvas` over multiple `ol/source/ImageStatic` when drawing the precipitation images and reusing ol features and canvas elements as much as possible on the new weather map.

I believe the problem OpenLayers sees with iOS 12 is that canvas elements do not get garbage collected immediately unless you explicitly set width and height to 0.

I've created a testcase showing this issue on https://output.jsbin.com/ganafaketa/1

I've also reported this issue to webkit: https://bugs.webkit.org/show_bug.cgi?id=195325

It might take a while for webkit to fix this issue, however, and for a new version of iOS to be released with this fix, so it would be nice if OpenLayers could explicitly set width and height to 0 when discarding canvas elements.

I can attempt a pull request but I'm not sure where to begin, the canvas code in OpenLayers is not easy to understand.

**Comment by fredj** [comment] 2019-03-05 13:58
Hi @esseb, I've quickly checked https://beta.yr.no/en/map/weather/1-72837/Norway/Oslo/Oslo/Oslo and I don't think you are using the right OpenLayers version.
The memory fix will be available in v6.0.0, you can already try the beta version 6.0.0-beta.2 : https://www.npmjs.com/package/ol/v/6.0.0-beta.2

**Comment by esseb** [comment] 2019-03-05 14:32
@fredj the same page with openlayers version 6.0.0-beta.2 can be tested on https://frontend-feature-openlayers-version-6.app-we.yr.no/nb/kart/v%C3%A6r/1-72837/Norge/Oslo/Oslo/Oslo

I can't tell if the canvas issue has disappeared or not because of another issue (see the top of that screenshot, below the address field:
![yr-oslo-this-web-page-was-reloaded](https://user-images.githubusercontent.com/207794/53812273-69bbcd00-3f5b-11e9-865e-1c9a50c078ba.png)

I'm not sure if the canvas issue could cause Safari to show this error message in ol 6.0.0-beta.2 or if this is something else. I can't see any issues reported about this Safari message on https://github.com/openlayers/openlayers/issues

**Comment by esseb** [comment] 2019-03-05 14:40
Safari devtools closes automatically when this error occurs I try to debug by tethering my iPhone to my Mac so I can't tell if there are any error messages in the console or not when this new issue occurs.

**Comment by esseb** [comment] 2019-03-05 15:13
When using the iPhone simulator in xcode with devtools open and testing https://frontend-feature-openlayers-version-6.app-we.yr.no/nb/kart/v%C3%A6r/1-72837/Norge/Oslo/Oslo/Oslo I was able to reproduce the issue.

![skjermbilde 2019-03-05 kl 16 12 34](https://user-images.githubusercontent.com/207794/53815219-8b1fb780-3f61-11e9-80c1-c122f15cda64.png)

I'm not sure why I get a different error on real hardware.

**Comment by esseb** [comment] 2019-03-06 14:04
I've created a reduced testcase for the issue I described and have opened a [new bug report](https://github.com/openlayers/openlayers/issues/9291) since it appears to be a bit different than the renderer DOM composition fix that caused this bug to be closed.
