### ISSUE TITLE
Running in prod mode does not work when having set optimization to true

### ISSUE THREAD

**Issue by JulidaRocks** [openlayers/openlayers#8859] opened 2018-10-25 07:13 UTC
We are using 

```
"ol": "^5.2.0",
"ol-geocoder": "^3.2.0",
"ol-popup": "^4.0.0"
```

with Angular 7.  Works fine in dev mode, but leads to the following error when running with **prod build with optimization: true:** (ng serve --prod)

> ERROR TypeError: Cannot read property 'getExtent' of null
    at 3.js:1
    at e.applyOptions_ (3.js:1)
    at new e (3.js:1)
    at l.initOpenLayerMap (11.js:1)
    at l.ngOnInit (11.js:1)
    at main.js:1
    at main.js:1
    at _s (main.js:1)
    at Vs (main.js:1)
    at Object.updateDirectives (11.js:1)

Code snippet:

```
import OlTileLayer from 'ol/layer/Tile';
import OlMap from 'ol/Map';
import OlView from 'ol/View';
import OlOsmSource from 'ol/source/OSM';
import Geocoder from 'ol-geocoder/dist/ol-geocoder';
import OlPopup from 'ol-popup';

initOpenLayerMap() {
    const olview = new OlView({ center: [0, 0], zoom: 2 }),
      baseLayer = new OlTileLayer({ source: new OlOsmSource() }),
      map = new OlMap({
        target: document.getElementById('map'),
        view: olview,
        layers: [baseLayer]
      });

    const popup = new OlPopup();
    map.addOverlay(popup);

    const geocoder = new Geocoder('nominatim', {
      provider: 'osm',
      lang: 'de-DE',
      placeholder: 'Wohnort suchen...',
      limit: 5,
      debug: false,
      autoComplete: true,
      keepOpen: false
    });
    map.addControl(geocoder);

    geocoder.on('addresschosen', this.setResidenceForm());
  }
```

Template snippet:
```
<div mat-dialog-content>
  <div id="map" class="map"></div>
  <div id="popup"></div>
</div>
```

We also use the ol map to show locations at another component of the app that also leads to the same error.

Any ideas?
Thanks a lot

**Comment by JulidaRocks** [comment] 2018-10-25 13:40
Update: When testing locally with ng serve --prod and optimization: false the map is showed correctly.
In our Azure application with prod build and optimization: false, the above mentioned stills occurs

**Comment by marcjansen** [comment] 2018-10-25 15:55
Are you sure openlayers is the problem? can you try without zhe third party components?

**Comment by JulidaRocks** [comment] 2018-10-26 17:44
accidentally closed

**Comment by flackdl** [comment] 2018-10-29 18:08
I am experiencing the same issue.  My setup is

- Angular 7
- OL 5.2.0

[Full Source](https://github.com/CWWED/cwwed/blob/open-layers/frontend/src/app/psa/psa.component.ts)

```
vendor.js:1 ERROR TypeError: Cannot read property 'getExtent' of null
    at Y (vendor.js:1)
    at e [as constructor] (vendor.js:1)
    at new e (vendor.js:1)
    at l._buildMap (main.js:1)
    at l.ngOnInit (main.js:1)
    at vendor.js:1
    at vendor.js:1
    at Os (vendor.js:1)
    at Ws (vendor.js:1)
    at Object.updateDirectives (main.js:1)
```

I can confirm this issue only appears when building with `ng build --prod`, as `ng build --aot --optimization` work fine.  `angular-cli`'s help about `--prod` say it does tree shaking via uglify so I'm assuming it's related to that somehow.

```
ng build --help

  --prod 
    When true, sets the build configuration to the production environment.
All builds make use of bundling and limited tree-shaking, A production build also runs limited dead code elimination using UglifyJS.

```

@JulidaRocks your demo repository link points to OL's issues page. just fyi.

**Comment by flackdl** [comment] 2018-10-29 18:15
Update: disabling the `build-optimizer` setting in the `ng` command remedied the problem.

    ng build  --prod  --build-optimizer=false

That's all I know.

**Comment by JulidaRocks** [comment] 2018-10-30 14:50
> @JulidaRocks your demo repository link points to OL's issues page. just fyi.

Thank you for the hint. Fixed the link.

As you say: Setting optimization to false is a workaround.
But I hope the bug will be fixed soon so that we can run our app with optimization=true again

**Comment by shenchaoran** [comment] 2018-11-03 12:43
In `angular@7.0.4, ol@5.2.0`, my situation is the same with @flackdl , disabling the `build-optimizer` solve this problem.

**Comment by fredj** [comment] 2018-11-08 10:45
Duplicate of #8815

**Closed by fredj** 2018-11-08 10:45 UTC
