### ISSUE TITLE
cacheSize problem of ol/source/TileImage

### ISSUE THREAD

**Issue by Casey-cdq** [openlayers/openlayers#9087] opened 2018-12-26 01:27 UTC
I found that loading the base map under IOS made the map blank after zooming in and out for a while. If I did not set the base map or set the cacheSize of ol/source/TileImage to 0, there would be no problem, but there would be no bottom map. I tried to set the cacheSize to a very small value, but there were still problems. I suspect it's a caching problem, but I don't know how to solve it.

**Comment by ahocevar** [comment] 2018-12-26 19:47
Duplicate of #8956.

**Closed by ahocevar** 2018-12-26 19:47 UTC
