### ISSUE TITLE
Legacy build fails

### ISSUE THREAD

**Issue by data-ux** [openlayers/openlayers#8603] opened 2018-09-07 07:15 UTC
I'm trying to build the lecagy `ol.js` file with `npm run build-legacy`.

I'm getting the error:
```
ERROR: Unable to parse a tag's type expression for source file /Users/jan/openlayers/src/ol/Collection.js in line 26 with tag title "param" and text "{import("./CollectionEventType.js").default} type Type.": Invalid type expression "import("./CollectionEventType.js").default": Expected "!", "=", "?", "[]", "|" or end of input but "(" found.
```

And a dozen similar errors. Finally the build exits with:
```
/Users/jan/openlayers/config/jsdoc/info/publish.js:98
          paramInfo.types = getTypes(param.type.names);
                                                ^
TypeError: Cannot read property 'names' of undefined
    at /Users/jan/openlayers/config/jsdoc/info/publish.js:98:49
    at Array.forEach (<anonymous>)
```

Steps to reproduce:
```
git clone git@github.com:openlayers/openlayers.git
cd openlayers
npm i
npm run build-legacy
```

OS: macOS 10.12.6
Node/npm: v10.10.0/6.4.1

**Comment by bartvde** [comment] 2018-09-07 07:17
duplicate of #8601

**Closed by bartvde** 2018-09-07 07:17 UTC
