### ISSUE TITLE
Cannot select webgl PointsLayer

### ISSUE THREAD

**Issue by long3009** [openlayers/openlayers#9501] opened 2019-05-07 07:55 UTC
Dear all.
I'm using ol/renderer/webgl/PointsLayer to display a mount of data (over 1 million features).
I want to select each feature with click or pointmove iteraction. 
I'm using ol/interaction/Select.js to do this fuction, but I cannot select these features.
When I change ol/renderer/webgl/PointsLayer to ol/layer/Vector, select function work normally.
This is my code:
```ts
import OlMap from 'ol/Map';
import OlView from 'ol/View';
import OlLayerTile from 'ol/layer/Tile';
import OlLayerVector from 'ol/layer/Vector';

var WebglPointsLayer = /*@__PURE__*/(function (OlLayerVector) {
  function WebglPointsLayer () {
    OlLayerVector.apply(this, arguments);
  }

  if ( OlLayerVector ) WebglPointsLayer.__proto__ = OlLayerVector;
  WebglPointsLayer.prototype = Object.create( OlLayerVector && OlLayerVector.prototype );
  WebglPointsLayer.prototype.constructor = WebglPointsLayer;

  WebglPointsLayer.prototype.createRenderer = function createRenderer () {
    return new WebGLPointsLayerRenderer(this, {
      texture: image,
      colorCallback: function(feature, vertex, component) {
        // component at index 3 is alpha
        if (component === 3) {
          return 1;
        }

        // color is interpolated based on year (min is 1910, max is 2013)
        // please note: most values are between 2000-2013
        var ratio = (2010 - 1950) / (2013 - 1950);
        return lerp(oldColor[component], newColor[component], ratio * ratio) / 255;
      },
      texCoordCallback: function(feature, component) {
        var coords = shapeTextureCoords[feature.get('shape')];
        if (!coords) {
          coords = shapeTextureCoords['light'];
        }
        return coords[component];
      },
      sizeCallback: function() {
        return 20;
      }
    });
  };

  return WebglPointsLayer;
}(OlLayerVector));

this.vectorSource = new OlSourceVector({
      features: [new OlFeature({
        geometry: new OlGeomPoint([105.822410, 21.047324])
      })]
    });
 this.featureLayer = new WebglPointsLayer({
      source: this.vectorSource
    });

this.map = new OlMap({
      target: null,
      view: new OlView({
        center: [105.822410, 21.047324],
        zoom: 1,
        projection: 'EPSG:4326'
      }),
      // target: document.getElementById('map'),
      layers: [this.layer,
        this.featureLayer]
    });
    // this.map.on('prerender', this.map.updateSize);


      // select interaction working on "singleclick"
    var select = new Select({
      layers:[this.featureLayer]
    })
    this.map.addInteraction(select);


    select.on('select', function(e) {
        console.log("onSelect");
    });
```

Could you tell me how to resolve this bug.
Thanks you very much.

**Comment by jahow** [comment] 2019-05-07 08:37
Hi,

The webgl points renderer simply does not handle feature selection (`forEachFeatureAtCoordinate` is not implemented). This is admittedly not documented though.

I guess this could be tagged as a PR candidate...

**Comment by long3009** [comment] 2019-05-08 01:56
Thank you very much for quick reply. I hope openlayers will support interacting with webgl features in the future

**Comment by jahow** [comment] 2019-06-28 09:22
Resolved by #9655

**Closed by jahow** 2019-06-28 09:22 UTC

**Comment by flors** [comment] 2020-06-03 10:36
Hi @jahow maybe not the right place to ask... but, I'm using WebglPointsLayer and everything is working perfect. 

The thing is I need to change the source from this WebglPointsLayer but using layer.setSource(otherSource) nothing happens... is it possible to change the source of this kind of layers?

**Comment by jahow** [comment] 2020-06-04 07:53
You're right @flors, this is an undocumented limitation of this type of layer. Since the renderer keeps track of the number of features in the source it binds event handlers on it at initialization time, and this is not done again if the source changes. See:
https://github.com/openlayers/openlayers/blob/e21725888f2050be8ff41f685c158b71c03f663e/src/ol/renderer/webgl/PointsLayer.js#L318-L355

Could you please create a separate issue for this, ideally with a reproduction case using codesandbox?
