### ISSUE TITLE
Bézier curve supports for vector layer

### ISSUE THREAD

**Issue by schedul-xor** [openlayers/openlayers#896] opened 2013-08-10 03:15 UTC
Why don't vector layers support Bézier curves? I would like to know if there is/was a critical reason.

**Comment by ChouGary** [comment] 2016-08-26 02:45
ol3 have turf.along  example
http://openlayers.org/en/latest/examples/turf.html?q=turf
you can try turf.bezier
http://jsfiddle.net/ntkuqe2a/

http://turfjs.org/docs/#buffer

**Comment by fredj** [comment] 2018-06-20 14:33
Duplicate of #5582

**Closed by fredj** 2018-06-20 14:33 UTC
