### ISSUE TITLE
ImageWMS does not work with imageLoadFunction with fetch

### ISSUE THREAD

**Issue by keepitrealsimple** [openlayers/openlayers#15311] opened 2023-11-09 07:23 UTC
**Describe the bug**
ImageWMS does not work with imageLoadFunction with fetch and URL.createObjectURL. Similar approach works with TileWMS. This seems to be issue with decoding since setting Image.prototype.decode = null; fixes the issue. (Related issue https://github.com/openlayers/openlayers/issues/10868).

**To Reproduce**
1. Go to https://codesandbox.io/s/wms-image-forked-l8kz8z?file=/main.js:762-781 which does not work (ImageWMS)
2. Compare to https://codesandbox.io/s/wms-tiled-forked-vlsf83 which works (TileWMS)
3. Code Sandbox console only shows blank exception but browser console shows DOMException: Invalid image request.

**Expected behavior**
ImageWMS should also work with imageLoadFunction with fetch and URL.createObjectURL since it enables us to access resources with authentication (By providing headers to image requests)

**Comment by ahocevar** [comment] 2023-11-09 09:17
Duplicate of #15307. Please `npm install ol@dev`. I'm also going to publish a new version tomorrow, since this issue has been popping up so frequently recently.

**Closed by ahocevar** 2023-11-09 09:17 UTC
Labels: bug
