### ISSUE TITLE
Memory leak adding and removing layers from a map

### ISSUE THREAD

**Issue by npgeomap** [openlayers/openlayers#8141] opened 2018-04-30 09:49 UTC
**Adding and removing layers from a map increases constantly the memory usage depending on the size of the layer.** 

_Tested Environments
Openlayers Version: 4.6.5
Browser: Chrome, Firefox
OS: Windows 7, Windows Server 2016_

[Codepen sample](https://codepen.io/anon/pen/aGpgJM)
Description:
The function "replace" removes and adds 1000 random placed features on each call. Memory usage increases by approx 90-100 MByte when adding and removing layer 20 times.
_(Using more features or use polygons instead of points will increase the memory leak far more!)_

Chrome: Press (shift + escape) and watch as the memory usage increases each time "replace" is called.

**Comment by ahocevar** [comment] 2018-04-30 10:46
At this point I'm unable to reproduce. Garbage collection worked fine for me (latest Chrome on MacOS).

**Comment by npgeomap** [comment] 2018-04-30 11:42
Did you use the provided [codepen sample](https://codepen.io/anon/pen/aGpgJM)? And please hit the button at least 20 times and more to see the memory increasing. In the meantime we could reproduce the behaviour also on MacOS.

After 20 hits > two heap snapshots showing the vector layer nevers get's released.
![image](https://user-images.githubusercontent.com/4803504/39425494-06fb7896-4c7c-11e8-8840-86e75d48f6b5.png)

**Start: memory usage: 77MByte**
![image](https://user-images.githubusercontent.com/4803504/39424847-ea95ed6a-4c78-11e8-999e-84e30bcb7652.png)

**After 20 hits memory usage: 272MByte**
![image](https://user-images.githubusercontent.com/4803504/39424893-1b87f1f2-4c79-11e8-9f4a-5562fb292baa.png)

**After 80 hits memory usage: 500MByte**
![image](https://user-images.githubusercontent.com/4803504/39424915-2f43018c-4c79-11e8-8254-3d223eb89134.png)

**Comment by npgeomap** [comment] 2018-04-30 11:45
Sorry I closed the issue by misstake!

**Comment by ahocevar** [comment] 2018-04-30 11:50
I could reproduce it now. Thanks for the additional instructions.

Question: why aren't you calling `clear()` on the old vector source? Doing so will release everything for the garbage collector, and there won't be a memory leak.

**Comment by npgeomap** [comment] 2018-04-30 12:01
I did call clear() on the old vector source in the first place. Unfortunatelly it does not release the memory so i commented the _`oldLayer.getSource().clear();`_ line 27 in the sample.

**Comment by ahocevar** [comment] 2018-04-30 12:04
@npgeomap In addition, you have to unlink the source from the layer:
```js
oldLayer.setSource(undefined);
```

**Comment by ahocevar** [comment] 2018-04-30 12:47
The features and their point geometries cannot be released, because your application holds them in its `features` array.

**Comment by ahocevar** [comment] 2018-04-30 13:57
This issue is a duplicate of #7954, which has already been fixed with #7960. See https://codesandbox.io/s/82655y95z9 for your example with v5.0.0-beta.10, with no memory leak.

**Closed by ahocevar** 2018-04-30 13:57 UTC

**Comment by jalik** [comment] 2019-02-01 05:40
Hello @ahocevar, I found that there may be a memory leak in the 5.3.0 release.
I can still find references to `Feature` objects in Chrome Profiling tool, however I am pretty sure I have no left references (no global vars or uncleaned timeouts/intervals) in my app when the map is not displayed anymore on another page.
I'll try to investigate more because I have no real clues, only findings.

**Comment by fredj** [comment] 2019-02-01 07:44
@jalik can you open a new issue? ideally with a minimal example
