### ISSUE TITLE
Text style backgroundFill not honored when selection occurs

### ISSUE THREAD

**Issue by tuscland** [openlayers/openlayers#8702] opened 2018-09-24 17:18 UTC
Hello,

We have this annoying problem with OpenLayers 4.6.5, that we can reproduce always. We are not sure how to test with OpenLayers 5.2.0 at the moment because we use TypeScript.

We have a vector layer configured with a style function that computes a style array for each feature. The effective style is used to draw an anchor, a leader line and a text label.

A select interaction is also present, which changes the style of the selected feature.

We call `addFeatures on the layer source with an array of features. When the first feature of this array is selected on the map, all other features lose their backgroundFill property on the Text styles. Weirdly enough this behavior is also present when any feature is selected, but then it depends on the count of currently visible features (by adjusting the current resolution), with more chance of triggering it as the index of the selected feature is low.

We have no code that would conditionalize the display of the Text's backgroundFill, which explains why we are pretty sure something is wrong.

We found a workaround by drawing an image to account for the defective text background, but it has two drawbacks: it is a serious performance hit, and text overlapping is not handled as nicely.

I would be more than appreciative if someone could shed some light on this issue.

Thanks!

**Comment by ahocevar** [comment] 2018-09-25 06:40
This is a duplicate of #8150, and was fixed in v5.0.0.

**Closed by ahocevar** 2018-09-25 06:40 UTC

**Comment by tuscland** [comment] 2018-09-25 06:46
Thank you Andreas, and sorry for the noise.
