### ISSUE TITLE
Openlayers6 cannot drag/scroll map

### ISSUE THREAD

**Issue by orpheus** [openlayers/openlayers#11228] opened 2020-06-29 19:39 UTC
https://codesandbox.io/s/open-layers-drag-fix-2prs0?file=/src/Map.js

Note that you cannot drag/scroll map with mouse or trackpad.

I found that if you unset `position: absolute` from `class=ol-unselectable ol-layers` (the first div under the viewport div) it'll become draggable.

Is this a bug in the way the map is set up? Is there a way to override that style if necessary? Or am I doing something wrong?

[Edit] it seems that if you remove `position: absolute` from any of the child divs of `class=ol-viewport` it'll become draggable

**Comment by jeroenvheel** [comment] 2020-06-29 19:48
@orpheus Did you add ol.css this is needed.

**Comment by orpheus** [comment] 2020-06-29 20:05
> @orpheus Did you add ol.css this is needed.

I have not. Is this new to v6? I don’t recall doing such in v5.

**Comment by ahocevar** [comment] 2020-06-29 20:49
In the examples we import `ol.css` as first line in `index.js`:
```js
import 'ol/ol.css';
```

That said, including `ol.css` will be optional again in the upcoming 6.4 release. See #10932, which this issue is a duplicate of.

**Closed by ahocevar** 2020-06-29 20:49 UTC

**Comment by jeroenvheel** [comment] 2020-06-29 20:50
@orpheus I don’t know why we need to add it.is saw this issue a few times in the issues after v6.2.1 and the maintainers said they needed to add the ol.css.

**Comment by orpheus** [comment] 2020-06-29 20:56
> In the examples we import `ol.css` as first line in `index.js`:
> 
> ```js
> import 'ol/ol.css';
> ```
> 
> That said, including `ol.css` will be optional again in the upcoming 6.4 release. See #10932, which this issue is a duplicate of.

Ah I see, I was looking for the link in `index.html` thank you.
