### ISSUE TITLE
Geotif module problem in openlayers (GeotiffIamage - Txml)

### ISSUE THREAD

**Issue by ElfDio** [openlayers/openlayers#12852] opened 2021-10-04 08:59 UTC
Hi, I have a problem with the latest version of the library. The geotiff module used in the library received an update 11 days ago. There have been significant changes related to the txml module. But OL-geotiff is not working correctly with its current update. The old version remains. It does not see the txml module. For your information. 
Can you please provide an urgent feedback related to this topic ?

**Comment by ahocevar** [comment] 2021-10-04 10:00
See geotiffjs/geotiff.js#243. The issue is fixed in geotiff.js's main branch, but there has been no new release yet.

**Comment by ElfDio** [comment] 2021-10-05 06:52
> Bkz [geotiffjs / geotiff.js # 243](https://github.com/geotiffjs/geotiff.js/pull/243) . Sorun geotiff.js'nin ana dalında düzeltildi, ancak henüz yeni bir sürüm yayınlanmadı.

We have same problem too. we can fix our local development environment by manual fix but we can't deploy to prdocution environment for almost 1 week. Because of using kubernetes, gitlab ci/cd tools and something else. We need an urgent release from you or solution offer to fix the problem. Can you please help about this situation? Thanks with best regards

**Closed** 2021-10-06 17:32 UTC
Labels: bug
