### ISSUE TITLE
Query parameters in WMS URLs encode commas

### ISSUE THREAD

**Issue by jburtge** [openlayers/openlayers#8635] opened 2018-09-14 14:24 UTC
Query parameters in Tiles WMS requests are being encoded in the function ol.TileWMS.getRequestUrl(). The last line of the function calls ol.uri.appendParams(). This function will encode all of the Query Parameters, such as BBOX and LAYERS parameters.

This example:
http://tsauerwein.github.io/ol3/mapbox-gl-js/examples/wms-tiled.html?q=WMS

Generates the followng URL:
https://ahocevar.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&TILED=true&WIDTH=320&HEIGHT=320&CRS=EPSG%3A3857&STYLES=&FORMAT_OPTIONS=dpi%3A113&BBOX=-12523442.714243278%2C2504688.542848654%2C-10018754.171394622%2C5009377.08569731

The WMS 1.3.0 specification section 6.3.2 - Reserverd characters in HTTP Get URLs specifically states:

The URL specification (IETF RFC 2396) reserves particular characters as significant and requires that these be escaped when they might conflict with their defined usage. This International Standard explicitly reserves several of those characters for use in the query portion of WMS requests. When the characters “?”, “&”, “=”, “,” and “+” appear in one of the roles defined in Table 1, they shall appear literally in the URL.

Some servers, such as the Cubewerx Demo server, do not accept encoded commas in the query parameters.

**Comment by fredj** [comment] 2018-09-19 11:42
Duplicate of #3092

**Closed by fredj** 2018-09-19 11:42 UTC

**Comment by marcjansen** [comment] 2018-09-19 18:16
... which points to #1441, which basically ends with 'PR accepted'.
