### ISSUE TITLE
Problem in renderMode: "image"

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#8216] opened 2018-05-23 14:27 UTC
In the past (Version 4.5.0), I used to have code as below to draw clipped region of the map.  This used to work 100%, except in latest version (4.6.5, even 4.6.4) of OL, it does not draw anything (blank):

**OLD CODE Version 4.5.0**
```
        var style = new ol.style.Style({
            fill: new ol.style.Fill({
                color: 'black'
            })
        });
        var clipLayer = new ol.layer.Vector({
            renderMode: 'image',
            style: style,
            source: new ol.source.Vector({
                url: "getmunfeature/" + munid,
                format: new ol.format.GeoJSON()
            })
        });
        clipLayer.on('postcompose', function (e) {
            e.context.globalCompositeOperation = 'source-over';
        });
        clipLayer.on('precompose', function (e) {
            e.context.globalCompositeOperation = 'destination-in';
        });
        map.addLayer(clipLayer);
```

If I remove renderMode, then it draws the map, but panning around does not work as expected (It shows background (buffer that was outside the map) then draws the clip over it)

**MODIFIED CODE Version 4.6.5**
```
        var style = new ol.style.Style({
            fill: new ol.style.Fill({
                color: 'black'
            })
        });
        var clipLayer = new ol.layer.Vector({
            style: style,
            source: new ol.source.Vector({
                url: "getmunfeature/" + munid,
                format: new ol.format.GeoJSON()
            })
        });
        clipLayer.on('postcompose', function (e) {
            e.context.globalCompositeOperation = 'source-over';
        });
        clipLayer.on('precompose', function (e) {
            e.context.globalCompositeOperation = 'destination-in';
        });
        map.addLayer(clipLayer);
```

What am I doing wrong?  Or what has changed?

**Comment by ahocevar** [comment] 2018-05-23 14:35
The `renderMode` option was introduced in v4.6.0, so v4.5.0 simply ignores that setting. For the other issue (background shown for buffer outside the map), it would be good to see it in a CodePen.

**Comment by 1Map** [comment] 2018-05-23 14:40
Thanks, I fixed the issue by using ol.layer.Image and not ol.layer.Vector like:

```
        var clipLayer = new ol.layer.Image({
            renderMode: 'image',
            source: new ol.source.ImageVector({
                style: style,
                source: new ol.source.Vector({
                    url: "getmunfeature/" + munid,
                    format: new ol.format.GeoJSON()
                })
            })
        });
```

**Comment by ahocevar** [comment] 2018-05-23 14:43
`ol.source.ImageVector` is deprecated and no longer in master.

**Comment by 1Map** [comment] 2018-05-23 14:49
What does this mean?  Will all my ol.source.ImageVector code fail in future releases?  I am currently on 4.6.5 and it does not complain with the working code above.

**Comment by ahocevar** [comment] 2018-05-23 14:54
Yes, v5.0.0 will not have an ImageVector source any more. See the v4.6.0 [release notes](https://github.com/openlayers/openlayers/releases/tag/v4.6.0).

It would be good to investigate your original issue. Can you create a CodePen that shows what you did in v4.5.0?

**Comment by 1Map** [comment] 2018-05-23 16:39
Ok, I created 3 Codepens

**4.5.0 - Working (Although when you pan around it is creating funny effect)**
https://codepen.io/1map/pen/VxNopP

**4.6.5 - Same Code as 4.5.0 above - Not Working (Because of renderMode: "image")**
https://codepen.io/1map/pen/zjXVYj

**4.6.5 - Deprecated ol.source.ImageVector Code - Working 100% as needed even with panning**
https://codepen.io/1map/pen/GdLVdQ

**Comment by ahocevar** [comment] 2018-05-23 16:55
Thanks for taking the time. I'd recommend to use `ol/layer/Vector` with standard render mode and with `renderBuffer: window.screen.width` to ensure buffering even when dragging very fast.

I have created a codepen for v4.6.5 with that solution: https://codepen.io/anon/pen/zjQOOK.

I'm closing the issue because of the aforementioned fact that v4.5.0 had no `renderMode: 'image'` and the clipping technique used in your code cannot work with that mode by design.

**Comment by ahocevar** [comment] 2018-05-24 11:28
Actually there is indeed a bug. The image renderer used for the vector layer with `renderMode: 'image'` calls the vector renderer's `composeFrame()` method within its own `prepareFrame()` method. That causes extra `'precompose'` and `'postcompose'` events to be triggered. To fix this, the vector renderer should get a new `compose()` method, which holds all the code between `preCompose()` and `postCompose()` in its `composeFrame()` method. The image renderer should then call `compose()` instead of `composeFrame()`.

Pull request welcome.

**Closed** 2018-05-25 12:46 UTC
Labels: pull request accepted

**Comment by 1Map** [comment] 2018-05-28 10:00
Thanks @ahocevar 

I have loaded your last codepen.  And it works 100%, except when I want to load a MultiPolygon it does not work.  What can be wrong with this:

New codepen:

https://codepen.io/1map/pen/YvKNrj

**Comment by ahocevar** [comment] 2018-05-29 07:49
@1Map Interesting. I have no explanation for that, but it works with `renderMode: 'image'` if you use a version with the #8225 fixes.
