### ISSUE TITLE
Measure tooltip disappearing (Google Chrome update)

### ISSUE THREAD

**Issue by cartochris** [openlayers/openlayers#9290] opened 2019-03-06 10:38 UTC
**Describe the bug**
When using the measure interaction in the most recent Google Chrome browser update (version 72.0.3626.121), the tooltip intermittently disappears when moving the cursor around the map.

**To Reproduce**
1. Open the [Measure OpenLayers example](https://openlayers.org/en/latest/examples/measure.html) in Google Chrome v72.0.3626.121.

**Expected behavior**
The tooltip should persist as in previous versions of Google Chrome and other web browsers. Clearly this is a result of changes to the Google Chrome browser and could affect other functionality which uses tooltips or labels.

**Comment by ahocevar** [comment] 2019-03-06 10:59
I'm unable to reproduce this. Can you verify on a different machine that it happens there too? Issues like this are sometimes caused by graphics card driver problems.

**Comment by cartochris** [comment] 2019-03-06 11:16
I can confirm the same issue happens on two other machines I have tested with the stated Chrome version (screen record attached of the issue).

![2bzjkn2asj](https://user-images.githubusercontent.com/13568601/53877527-52cfb600-4001-11e9-99d4-5e7ef2123fc9.gif)

**Comment by ThomasG77** [comment] 2019-03-06 15:16
I'm able to reproduce too. The following solves the issue (PS: dumb fix, didn't dive why it behaves this way...)

```
.ol-overlay-container {
  z-index: 1;
}
```

**Comment by ahocevar** [comment] 2019-03-06 15:45
Does https://openlayers.org/en/master/examples/measure.html expose the same issue? We have changed z-index handling since the last release, so I think this issue should be fixed.

**Comment by cartochris** [comment] 2019-03-06 15:50
> Does https://openlayers.org/en/master/examples/measure.html expose the same issue? We have changed z-index handling since the last release, so I think this issue should be fixed.

On initial load it appears to display correctly, but on changing measurement type or measuring more than one feature it has the same intermittent display issue.

**Comment by ahocevar** [comment] 2019-03-06 15:59
Can this be worked around by changing the `.tooltip` css in the example? If so, a pull request would be appreciated.

**Comment by ThomasG77** [comment] 2019-03-06 17:05
> Can this be worked around by changing the .tooltip css in the example?

Unable to solve it from my attempts (PS: I'm weak in CSS). Only solved the issue by playing at parent level of `.tooltip` hence the previous `.ol-overlay-container` use.

**Closed** 2019-03-11 13:37 UTC
