### ISSUE TITLE
Custom build failing

### ISSUE THREAD

**Issue by illogicz** [openlayers/openlayers#7215] opened 2017-09-04 08:56 UTC
I just upgraded from 4.2.0 to 4.3.2 and my custom build is no longer working. I get this error:
```
ERR! Trouble generating info: ERROR: Unable to find the plugin "../../config/jsdoc/info/api-plugin"
ERROR: Unable to find the plugin "../../config/jsdoc/info/define-plugin"
ERROR: Unable to find the plugin "../../config/jsdoc/info/virtual-plugin"
FATAL: Unable to load template: Cannot find module '../../config/jsdoc/info/publish'
```

**Comment by illogicz** [comment] 2017-09-04 09:00
Just found discussion on this error in pull request https://github.com/openlayers/openlayers/pull/7003. Sorry if this is considered a duplicate.

**Comment by ahocevar** [comment] 2017-09-06 13:00
Thanks for creating the ticket, it's not a duplicate of #7003. See #7229 for a fix.

**Closed** 2017-09-07 07:06 UTC
