### ISSUE TITLE
Bug when clicking and dragging the mouse outside the HTML map element

### ISSUE THREAD

**Issue by stephenhenckaerts** [openlayers/openlayers#10770] opened 2020-03-06 08:34 UTC
**Describe the bug**
When you have to navigate the map you do this by clicking and dragging the map around. This works fine until you drag your mouse outside of the HTML map div and release it. Then the next time you navigate the map jumps back to it's previous position. So you click your left mouse button and keep it down and drag your mouse outside the map. If you then release our mouse the map doesn't recognise this reposition and next time you reposition it jumps back to it's original position. 

**To Reproduce**
1. Go to an example project e.g. https://openlayers.org/en/latest/examples/canvas-tiles.html
2. Click on a position within the map
3. Keep your mouse button down
4. Drag the mouse outside the map
5. Release your mouse
6. Try to navigate again
7. Error: The map repositions to the position before step 2

**Expected behavior**
The map registers it's new position after releasing in step 5 and you can simple start repositioning from there.

**Comment by mike-000** [comment] 2020-03-06 10:27
I cannot reproduce the issue in the master (6.2.2 dev) version https://openlayers.org/en/master/examples/canvas-tiles.html
There are also issues in 6.2.1 with vector layers not rendering when the mouse is dragged outside the browser window which appear to be fixed in master.

**Comment by fredj** [comment] 2020-03-26 14:26
Cannot reproduce with the latest version:
https://openlayers.org/en/v6.2.1/examples/canvas-tiles.html

**Closed by fredj** 2020-03-26 14:26 UTC
