### ISSUE TITLE
Openlayer tiles do not render on build

### ISSUE THREAD

**Issue by JAEHOON-1993** [openlayers/openlayers#14295] opened 2022-11-12 07:45 UTC
I am using React 18, Next 13, OL 7.1.0

It works when I execute the code "yarn run dev" like this

![image](https://user-images.githubusercontent.com/40525201/201463360-8b946b28-6f4d-4f5a-af27-4153d1fc51ab.png)

But when I deploy on Vercel which is Next.js fron-end server. The tile don't load like this. 

![image](https://user-images.githubusercontent.com/40525201/201463385-dccc1e81-6d0d-4a50-a93c-ba3c200cd5b5.png)

How can I solve it?

Link: https://stackoverflow.com/questions/74411056/openlayer-tile-dont-render-on-next-js-vercel-server
Link: https://stackoverflow.com/questions/74396848/openlayer-tiles-do-not-render-on-build

**Comment by ahocevar** [comment] 2022-11-12 08:13
It looks like you're using quite an involved setup, using Next.js. To increase chances that you get help here, I'd suggest providing a link to a public git repository with the setup that does not work, and a minimal map application that shows the problem.

**Comment by JAEHOON-1993** [comment] 2022-11-12 15:20
> It looks like you're using quite an involved setup, using Next.js. To increase chances that you get help here, I'd suggest providing a link to a public git repository with the setup that does not work, and a minimal map application that shows the problem.

Ok I see, I will make another simple project!

**Comment by JAEHOON-1993** [comment] 2022-11-12 16:34
Here's the code


```
import React, { useEffect, useState } from 'react';
import Container from 'components/Container';

import Map from 'ol/Map';
import OSM from 'ol/source/OSM';
import TileLayer from 'ol/layer/Tile';
import View from 'ol/View';
import styled from 'styled-components';

interface Props {
  fixed?: boolean;
  style?: any;
}

const SimpleMapContainer: React.FC<Props> = () => {
  const [checkRender, setCheckRender] = useState<boolean>(false);

  useEffect(() => {
    setCheckRender(true);
  }, []);
  const map = new Map({
    layers: [
      new TileLayer({
        source: new OSM(),
      }),
    ],
    target: 'map',
    view: new View({
      center: [0, 0],
      zoom: 1,
    }),
  });

  console.log(map);
  console.log(checkRender);
  return (
    <div style={{ flexDirection: 'column' }}>
      <Container>
        <MapBox id="map" className="map"></MapBox>
      </Container>
    </div>
  );
};

export default SimpleMapContainer;

const MapBox = styled.div`
  position: absolute;
  left: 0px;
  right: 0px;
  top: 0px;
  bottom: 0px;

  width: 100%;
  height: 100%;

  z-index: 0;

  /* -webkit-overflow-scrolling: touch; */
`;
```


And I use 

```
"@material-ui/core": "^4.12.4",
    "@paypal/react-paypal-js": "^7.8.1",
    "@types/js-cookie": "^3.0.2",
    "@types/lodash": "^4.14.188",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.8",
    "@types/react-lottie": "^1.2.6",
    "@types/react-query": "^1.2.9",
    "@types/react-select": "^5.0.1",
    "@types/react-slick": "^0.23.10",
    "antd": "^4.24.1",
    "axios": "^1.1.3",
    "i18next": "^22.0.4",
    "js-cookie": "^3.0.1",
    "mobx": "^6.6.2",
    "mobx-react": "^7.5.3",
    "next": "^13.0.3",
    "next-pwa": "^5.6.0",
    "ol": "^7.1.0",
    "react": "^18.2.0",
    "react-device-detect": "^2.2.2",
    "react-dom": "^18.2.0",
    "react-flip-toolkit": "^7.0.17",
    "react-i18next": "^12.0.0",
    "react-is": "^18.2.0",
    "react-lottie": "^1.2.3",
    "react-query": "^3.39.2",
    "react-select": "^5.6.0",
    "react-slick": "^0.29.0",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.3.6"
```

When I type "yarn run dev", it works on localhost like this

<img width="895" alt="image" src="https://user-images.githubusercontent.com/40525201/201484407-11dc5e9f-abc0-4305-aee8-260268e967b0.png">

But when I deploy the build on Vercel, It doesn't work like this

<img width="897" alt="image" src="https://user-images.githubusercontent.com/40525201/201484441-2d92a0ee-4091-4ac7-8b30-2ec0e2052bda.png">

How can I solve this issue?

I think there're some other people suffering from same issue.

**Comment by ahocevar** [comment] 2022-11-12 16:42
Please, provide a link to a git repository that people can clone and set up locally.

**Comment by JAEHOON-1993** [comment] 2022-11-12 23:57
> Please, provide a link to a git repository that people can clone and set up locally.

OK, I see!

**Comment by enisze** [comment] 2022-11-13 00:32
I got the same problem:
https://stackoverflow.com/questions/74396848/openlayer-tiles-do-not-render-on-build

**Comment by enisze** [comment] 2022-11-13 00:49
https://github.com/enisze/ol-on-build

**Comment by MeRahulAhire** [comment] 2022-11-14 16:58
Even I'm experiencing the same issue on netlify build for my nexjs - https://gis.stackexchange.com/q/444829/213228
Should I downgrade OpenLayers to **version 6**?

```js
import Map from "ol/Map";
import View from "ol/View";
import TileLayer from "ol/layer/Tile";
import XYZ from "ol/source/XYZ";
import { useEffect } from "react";
export default function OpenLayers() {
  useEffect(() => {
    new Map({
      target: "map",
      layers: [
        new TileLayer({
          source: new XYZ({
            url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
            crossOrigin: "anonymous",
          }),
        }),
      ],
      view: new View({
        projection: "EPSG:4326",
        extent: [-180, -90, 180, 90],
        center: [0, 0],
        zoom: 2,
      }),
    });
  }, []);

  return (
    <>
      <div id="container" >
        <div id="map" style={{ height: "500px", width: "1000px"}}></div>
      </div>
    </>
  );
}
```

**Comment by elamandeep** [comment] 2022-11-15 17:15
Try this. It will work. 
https://codesandbox.io/s/openlayer-tailwind-mey8ij

**Comment by ahocevar** [comment] 2022-11-15 18:16
Could it be that next.js is trying to render the map using Server Side Rendering (SSR)? That will not work, and would not make sense because you'd loose all interactivity with the map.

**Comment by enisze** [comment] 2022-11-15 21:25
I tried using dynamic import and preventing ssr @ahocevar like: 
```
const DynamicMap = dynamic<MapProps>(
  () => import("../Map").then((module) => module.Map),
  {
    ssr: false,
  }
);
```

But it did not change anything

**Comment by elamandeep** [comment] 2022-11-16 02:46
> Could it be that next.js is trying to render the map using Server Side Rendering (SSR)? That will not work, and would not make sense because you'd loose all interactivity with the map.

I think so because it's working perfectly in react. But the downside is that React uses `VDOM`, which will somehow interfere with OpenLayers. Read the limitation segment carefully https://react-leaflet.js.org/docs/start-introduction/. I think using React with OpenLayers is not the right choice. But I don't know which framework suits OpenLayers most other than Angular. That's why I have asked in a discussion. Maybe I am wrong but I tried it. That's why I am here in this discussion.

**Comment by ahocevar** [comment] 2022-11-16 07:36
OpenLayers does support virtual DOM, and it is being used successfully in thousands of React applications. But as stated elsewhere, it does not work in classic SSR (server side rendering) scenarios. Which does not mean that you cannot use OpenLayers on the server side to create static map images.

@elamandeep, it would be interesting to hear where you're facing issues with an OpenLayers map in a VDOM. I'm not aware of any.

**Comment by MeRahulAhire** [comment] 2022-11-16 22:00
It's sad, looks like I'll need to shift back to react.

**Comment by lawrencejob** [comment] 2022-11-18 20:51
I'm experiencing the same issue - I can get it to work fine with Next 12; the dynamic(() => {}) API seems to have been broken in Next 13. Interestingly, their docs show a 404 for the beta next/dynamic docs, so I suspect they're changing something under the hood.

I've spent all week trying to get Next13+"app dir" to work with OpenLayers. Everything works fine apart from the tile layer.

I'm investigating further but what I've learned is that the tile layer believes that the map view is 0px x 0px. It's definitely to do with server rendering.

I suspect that the bug is in Next/SSR, but the problem _only_ manifests in this one component of this one library (and even then, only when in production mode, not in debug mode), which makes it very very hard to diagnose. The onus is on implementors to fix this, not necessarily the library, but if there is an expert from OpenLayers who knows what could cause this, we'd be very grateful!

I suspect a LOT of people are going to have this issue as they upgrade over the coming months.

**Comment by lawrencejob** [comment] 2022-11-19 21:36
Having done some more work on this, I'm more convinced that there is a hard-to-replicate bug in the OpenLayers tile renderer that is one of two things:

- Officially unsupported behaviour (wont-fix)
- Exacerbated by the renderer hand-off in React 18 and Next 13

The bug in the Tile layer (or renderer as it may be) is that it doesn't seem to understand the extents of the map view. It seems to initialise the view at 0x0 and not acknowledge the change. This _could_ be because of devicePixelRatio or viewport client dimensions.

The end result is that it only loads the following tiles (corresponding to the requested zoom):

https://tileserver/{zoom}/0/0.png

Hereon is me trying to run through the code to understand what is motivating it to only load tiles at (0,0):

My hypothesis is that the map initiates with a certain value in the pixel-to-coordinate system and never adjusts after the change. The problem could be alleviated by the tile renderer noticing the change and updating.

I (bearing in mind that I have no experience with this codebase, so I'd be happy to hear that I'm wrong) notice that tilerange is always set to [0,0,0,0], which is affecting which tiles are loaded.

I notice that TileGrid's fullTileRanges_ is an array[z:20] of {minX:0, maxX:0, minY:0, maxY:0}, which doesn't seem right. calculateTileRanges() returns real numbers on the examples on the OpenLayers website, which suggests the problem lays here.

Will update this comment if I find anything else.

**Comment by ahocevar** [comment] 2022-11-19 22:24
@lawrencejob Did you investigate this with https://github.com/enisze/ol-on-build, or a different repository/setup?

**Comment by enisze** [comment] 2022-11-19 22:57
setting `swcMinify` in the next.config to `false`fixed it for me.

**Comment by lawrencejob** [comment] 2022-11-19 23:30
@ahocevar I am trying to debug in my codebase (which is similar but I have a lot of instrumentation around it) - if I'm still working on this after tomorrow (which would mark a week), I'll check out that repository and try to replicate my research in it.

`swcMinify: false` did not work in my codebase with Next 13.0.4 (using appDir)

**Comment by lawrencejob** [comment] 2022-11-19 23:40
I was being lazy - checked out the repo and validated my findings in @enisze's repo.

This is a screenshot of the value of `fullTileRanges_` in `dev`
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1598811/202875780-5c60a8a3-3f55-4b3d-875a-3c94fe8b7ac6.png">

And with `pnpm run build`, `pnpm run start`, the value is:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/1598811/202875834-6ea61c0a-1ec4-41cf-b649-26b8bbb62a89.png">

**Comment by ahocevar** [comment] 2022-11-20 08:59
Try `npm install ol@dev`. Maybe this is fixed by #14305.

**Comment by ahocevar** [comment] 2022-11-20 09:58
the problem is definitely caused by swcMinify. With `swcMinify: false`, it works. And the reason why it fails with `swcMinify: true` is OpenLayers's reuse of arrays in `src/ol/TileGrid.js`, which swcMinify does not seem to understand. There we specify a `tmpTileCoord`, which we pass around to avoid creating an array over and over. If I change the `getTileRangeForExtentAndZ()` method to not use and pass on that `tmpTileCoord`, the problem does not occur any more.

@lawrencejob, maybe you can create a reproducible test case from this information, and create an https://github.com/swc-project/swc issue. In the meantime, I'd recommend configuring next.js with `swcMinify: false` in `next.config.js`. This will result in terser being used for minification.

**Comment by ahocevar** [comment] 2022-11-20 16:02
Thanks for your thorough investigation and report, @lawrencejob. Without this, it would have been impossible to come up with a solution. I created #14320, which works around this swc minify problem.

However, it would be good to isolate this issue and file a bug report against swc. Would be great if you could do that, @lawrencejob.

**Comment by lawrencejob** [comment] 2022-11-21 01:36
Hi! Thanks for your reply and the insight -- I'm back at my day job today, but it's at the top of my list for my next weekend.

I'm so glad that my ramblings were useful to someone. At the time I just needed somewhere to put my notes. I had an idea that it could be the minifier (especially after reading the discussion thread about compatibility on their repo) but it was hard to prove it through all the layers.

Thanks so much for the patch. 

I'm not sure why `swcMinify` to `false` isn't working for me, but I suspect it's because I'm using the new appDir features and the flag isn't implemented yet. There are a lot of bugs (which is why this was hard to diagnose).

I think I can piece together where swcMinifier gets confused by the reuse from your code but I won't know until I have time to read it.

Thank you so much again.

**Comment by MeRahulAhire** [comment] 2022-11-21 12:53
This worked for me in `next.config.js`
```js
const nextConfig = {
  reactStrictMode: true,
  swcMinify: false
};
```
But, I want to know that what does `swcMinify` do and is it ok to disable it globally as mentioned above?

**Comment by lawrencejob** [comment] 2022-11-21 16:14
> But, I want to know that what does `swcMinify` do and is it ok to disable it globally as mentioned above?

It's a library that Nextjs uses to make your code small (and hard to read). Check out [Minification on Next Docs](https://nextjs.org/docs/advanced-features/compiler#minification) for more information. It's safe to disable because when you do, they use a different library (Terser) instead.

**Closed** 2022-11-21 18:11 UTC
Labels: bug
