### ISSUE TITLE
Issue with latest version (6.7.0) : cannot modify the cursor over the map

### ISSUE THREAD

**Issue by Dominique92** [openlayers/openlayers#12754] opened 2021-09-15 09:21 UTC
As you can see on https://openlayers.org/en/latest/examples/custom-interactions.html
(this worked with 6.6.1)
The issue is on all the canvas area, even for external mapElement.style.cursor = 'xxx'
Not better with css style

**Comment by mike-000** [comment] 2021-09-15 09:57
Duplicate of #12735, already fixed in the dev version.

**Closed** 2021-09-15 10:13 UTC
Labels: bug
