### ISSUE TITLE
map.singleClick return a wrong  data when the page scale

### ISSUE THREAD

**Issue by a18750799019** [openlayers/openlayers#13677] opened 2022-05-16 09:26 UTC
**Describe the bug**
when the page scale to 200%,singleClick retuan cordinate [13013796.428707648, 2831434.2613389804]
![image](https://user-images.githubusercontent.com/85674591/168561187-c3f7e809-d21c-4d6b-98ba-150e91685a6b.png)
then the mouse not move, with ctrl+0 to the scale reset at 100%,singleClick event return [13149701.46499869, 2819204.3368133525]
![image](https://user-images.githubusercontent.com/85674591/168561559-67b50e8c-dd3d-4ee5-9a8f-fa7eae48b014.png)
when i use wmsSource.getFeatureInfoUrl,it depend on paramater cordinate,but when scale the page,the wrong
data make the bbox(in the url) wong.

**To Reproduce**
click the map on anywhere,then scale the page with ctrl + '+' or ctrl + '-', the sigleClick event return different cordinate.

**Expected behavior**
when the page scale is 100%,the response is right,i hope whether the page scale to any other else,it can returen the same or correct data

**Comment by ahocevar** [comment] 2022-05-16 18:52
Duplicate of #13283. Please report additional findings tehre.

**Closed as completed** 2022-05-16 18:52 UTC
Labels: bug
