### ISSUE TITLE
Map prevents default on all click events

### ISSUE THREAD

**Issue by gpantic** [openlayers/openlayers#10232] opened 2019-10-31 10:05 UTC
**Describe the bug**
Map prevents default behavior on all click events. 
* If I have an input field over map, and I need it to loose focus when I click on map, that doesn't happen. 
* If I wanted to implement a middle click to reset the map zoom, it's not possible since map only captures left and right clicks on "singleclick" and "click" events.

**To Reproduce**
1. Set a mousedown or click handler on document
2. Click on map
3. Document click or mousedown handlers don't fire because map stops these events

**Expected behavior**
* If I have an input field over map I need it to loose focus when I click on map. 
* If I want to implement a middle click to reset the map zoom, "singleclick" and "click" events should capture middle clicks.

**Additional info**
This used to work correctly on version 5.1.3

**Comment by knabar** [comment] 2019-12-10 09:17
Running into the same issue, still looking for a workaround.

**Comment by ahocevar** [comment] 2019-12-10 09:23
Can someone provide an example in a https://codesandbox.io that shows the issue? I think this should be fixed in the latest dev version.

**Comment by knabar** [comment] 2019-12-10 10:01
Here is the expected behavior with 5.1.3, I get mouseclick events everywhere on the document, including clicking on the map: https://codesandbox.io/s/simple-35r68

Switching to 5.2.0 or newer,  I no longer get events when clicking on the map.

I initially thought this was an issue with 6.x, since I upgraded straight from an older version to 6.1.1, but the behavior seems to have changed in 5.2 already.

**Comment by ahocevar** [comment] 2019-12-10 11:32
Thanks for the example @knabar. #10402 fixes this issue.

**Closed** 2019-12-10 12:40 UTC

**Comment by knabar** [comment] 2019-12-10 12:42
Thank you @ahocevar
