### ISSUE TITLE
WFS / GML readFeatures not detecting srs

### ISSUE THREAD

**Issue by cyrilchapon** [openlayers/openlayers#8455] opened 2018-07-27 16:49 UTC
When reading features from a GML / WFS document, with the following options :

```
  const foundFeatures = wfs.readFeatures(wfsFeatureCollectionString, {
    dataProjection: undefined,
    featureProjection: 'EPSG:4326'
  })

  const foundFeatureCollection = geoJSON.writeFeaturesObject(foundFeatures, {
    dataProjection: 'EPSG:4326',
    featureProjection: 'EPSG:4326'
  })
```

If the document have features with `srsName`s, that srs is not detected, and the data is not reprojected.

The documentations says :

> Projection of the data we are reading. If not provided, **the projection will be derived from the data (where possible)** or the dataProjection of the format is assigned (where set). If the projection can not be derived from the data and if no dataProjection is set for a format, the features will not be reprojected.

"*where possible*" condition is met here, since srsName is a standard for specifying projection.
Am I doing something wrong ?

**Comment by cyrilchapon** [comment] 2018-07-27 16:54
This is probably due to [this (8456)](https://github.com/openlayers/openlayers/issues/8456)

**Comment by ahocevar** [comment] 2018-08-01 07:09
Duplicate of #8456.

**Closed by ahocevar** 2018-08-01 07:09 UTC
