### ISSUE TITLE
OL v8 No Longer Properly Decodes Large Images for Static ImageLayer

### ISSUE THREAD

**Issue by ryanweiler92** [openlayers/openlayers#15332] opened 2023-11-14 17:39 UTC
Prior to migrating to OL v8, we were conditionally displaying a [Static ImageLayer](https://openlayers.org/en/latest/examples/static-image.html) of a very large jpeg with dimensions of 21600 x 10800 to be projected to a large screen. After migrating to OL v8, this Static ImageLayer seems to no longer work with images of this size. Now these ImageLayers throw a DOMException error saying `This image cannot be decoded.` and a reference to line 190 of the `Image.js` OL module.

I was able to narrow down the problem to the dimensions because I altered the original image we were using to much smaller dimensions of 1000 x 500 and it worked just fine. Taking a look through the ol/Image module and I don't see anything related to the image size.

Is there any workaround for this or is there a way to find the maximum dimensions that we can use with the Static ImageLayer with OL 8? Here is a [link](https://github.com/nasa-gibs/worldview/blob/main/web/js/map/layerbuilder.js) to our layer builder file where we conditionally create the Static ImageLayer.

![image](https://github.com/openlayers/openlayers/assets/89816230/a559d07f-8d11-42b2-a70e-5cd6c7c0ff21)

**Comment by ahocevar** [comment] 2023-11-14 18:59
This should have been fixed with #15103. Please try to `npm install ol@dev` to see if the issue is resolved.

**Comment by ryanweiler92** [comment] 2023-11-14 20:22
> This should have been fixed with #15103. Please try to `npm install ol@dev` to see if the issue is resolved.

Ah yes it does work with `ol@dev`

**Comment by ahocevar** [comment] 2023-11-14 20:26
And I just published v8.2.0, so you can now also `npm install ol@latest`.

**Closed** 2023-11-14 20:26 UTC
Labels: bug
