### ISSUE TITLE
Testing react components that uses OL

### ISSUE THREAD

**Issue by kbroncel** [openlayers/openlayers#7401] opened 2017-10-30 13:21 UTC
I'm trying to test a map component in my application (created with 'create-react-app' starter).
Tests are crashing at `"node_modules\ol\map.js:1"` with an error `"SyntaxError: Unexpected token import"` because of the  ol beign es2015 modules, and not beign transformed with babel.

Someone posted a similar case in create-react-app repo:
[link](https://github.com/facebookincubator/create-react-app/issues/2943)
They stated that: 

> Packages should always be pre-compiled to their lowest target environment.
> In CRA apps, we enforce an IE 9+ compatibility requirement.
> 
> Compiling dependencies is slow and unreliable; code should be shipped in both common js and esmodules, or only common js.
> There are fields in package.json specifying the differing builds.

Can you consider adding a common js build? What is Your position in that matter?

**Comment by Ksoso** [comment] 2017-11-17 13:24
I'm at the beginning of starting quite big enterprise solution based on React and Openlayers 4.x and also got problems with testing my modules with Jest which contains OL4 solutions in it. The problem is caused by node.js which doesn't support es2015 module system and tests are running on node.js

**Comment by jalik** [comment] 2017-11-23 01:31
The `ol` npm package should be transpiled to ES5.
I'am also using `Jest` to create unit tests, but the only fact that I import the ol lib is causing the tests to fail and I don't see how to solve this..

**Comment by bartvde** [comment] 2017-11-23 09:04
This jest config works for me in my package.json:

```
  "jest": {
    "setupFiles": [
      "<rootDir>/env-setup.js"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!(ol|labelgun|mapbox-to-ol-style|ol-mapbox-style)/).*/"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "env-setup.js"
    ]
  }
```

**Comment by kbroncel** [comment] 2017-11-23 13:24
Isn't it, that you have to "eject" from create-react-app to make this config work?

**Comment by jalik** [comment] 2017-11-23 19:43
Thanks @bartvde for giving a working solution, but would'nt it be nice if Jest + OpenLayers were working out of the box as @kbroncel said ?

I dug into the ol npm sources and in the github repo and saw that it was compiled using a makefile, it's not very common right ? I mean usually there are tools like gulp, grunt, webpack... that allow to execute complex tasks (transpiling, renaming, stripping comments, bundling...), I am already doing such things with one of my npm package that is exploded into multiple files and is ES5 compatible, have a look at the small gulpfile : https://github.com/jalik/cuic.js/blob/master/gulpfile.js

**Comment by bartvde** [comment] 2017-11-23 20:08
I personally agree on publishing as ES5 see also Dan Abramov from Facebook here: https://twitter.com/dan_abramov/status/923600212798722051

**Comment by kbroncel** [comment] 2017-11-24 08:21
I'm a bit puzzled right now. Is OL published as ES5 right now or I am imagining things?
What can we do to make a NPM package published as ES5 to work with Jest without ejecting from CreateReactAapp? Is it even possible?

**Comment by bartvde** [comment] 2017-11-24 08:25
AFAIK the ol package is ES2015

**Comment by jalik** [comment] 2017-11-25 21:37
@kbroncel the released code of `ol` is ES2015 also known as ES6, don't mix ES5 and ES2015, there're not the same, ES5 was released in 2009 while ES6 was released in 2015. To say things simply, ES5 is the old classic JavaScript that everyone know and ES6 is the new one.

**Comment by kbroncel** [comment] 2017-11-26 07:57
@jalik @bartvde Ok, sorry. I mixed up ES2015 with ES5. 
So OL is published as ES2015.

By this was not the point of this thread. What can we do to run Jest tests while using OL with CreateReactApp?

**Comment by Primajin** [comment] 2018-03-21 10:35
It only works if you use the `transformIgnorePatterns` but that will raise the following error:

![bildschirmfoto 2018-03-21 um 11 29 36](https://user-images.githubusercontent.com/1742115/37705133-499cec0c-2cfb-11e8-918c-18c093d644c9.png)

so you need to eject - then you can use the advanced jest config and it will run through.

That's how it worked for us at least.

For further reading:

- https://github.com/facebook/create-react-app/issues/2537

**Comment by kbroncel** [comment] 2018-03-21 12:01
We managed to get around it with:
[https://github.com/timarney/react-app-rewired](react-app-rewired)
May help someone.

**Comment by lduros** [comment] 2018-05-31 16:44
@kbroncel Do you have detail of what you added in the config-overrides.js file and package.json to get this working? I'm suspecting you only have to change the "test" entry of your scripts in package.json to get this working, correct?

**Comment by kbroncel** [comment] 2018-06-07 06:54
In package.json change 
```
  "scripts": {
    - "test": "react-scripts test --env=jsdom",
    + "test": "react-app-rewired test --env=jsdom"
  },
```
And in config-overrides.js

```
module.exports = {
  webpack: function (config, env) {
    return config;
  },
  jest: function (config) {
    config.testEnvironment = "node";

    config.transformIgnorePatterns = [
      "/node_modules/(?!(ol|labelgun|mapbox-to-ol-style|ol-mapbox-style)/).*/"
    ];

    config.coveragePathIgnorePatterns = [
      "/node_modules/",
      "env-setup.js"
    ];

    config.snapshotSerializers = [
        "enzyme-to-json/serializer"
    ];
    return config;
  }
}
```

**Comment by sookoll** [comment] 2018-06-07 14:46
it is more general issue that just react/jest. Jes, in jest we can hack problem away, but we can't it every other test frameworks. I use tape, and I haven't found sane working solution (currently I build test bundle with webpack and then run it). I tried to teach babel to transpile ol without any success.

**Comment by ahocevar** [comment] 2018-06-12 06:45
Closing this issue, because using the `transformIgnorePatterns` config option is well established practice and more and more npm packages are published as ES modules.

**Closed by ahocevar** 2018-06-12 06:45 UTC

**Comment by sookoll** [comment] 2018-06-12 06:51
Without any general solution? Or Your solution is that everybody have to use Jest as testing framework?

**Comment by ahocevar** [comment] 2018-06-12 09:45
Solutions will be different for each test framework/bundler. For tape, you could take a look at https://www.npmjs.com/package/babel-tape-runner.

**Comment by jalik** [comment] 2018-06-12 17:31
@ahocevar excuse me, you said that `transformIgnorePatterns` is well established practice but as @sookoll pointed it's a **Jest** related configuration and there are tons of testing libs out there. I personally use Jest, but not everybody use it. It's a bit sad that such a great JS lib is not usable "out of the box" with testing lib without digging the internet to find how to fix the conflict...
Is it to much work to precompile to ES5 using tools like Babel ?
At least, could it be mentionned somewhere in the doc that testing libs may cause error, and how to fix this for the most known libs ?
Thank you.

**Comment by jktravis** [comment] 2018-12-10 13:42
I'm having the same problem, months later it seems, and simply cannot get the provided solution to work. I'm not using CRA or an ejected version of CRA. 

The error: 

    Details:

    /path/to/Projects/project/node_modules/ol/Map.js:4
    import PluggableMap from './PluggableMap.js';
    ^^^^^^

    SyntaxError: Unexpected token import

      1 | import React, { Component, createRef } from "react";
      2 | import { compose, map, find, equals, prop } from "ramda";
    > 3 | import OlMap from "ol/Map";
        | ^
      4 | import View from "ol/View";
      5 | import OL_STATE from "ol/source/State";
      6 | import OSM from "ol/source/OSM";

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (Scripts/Controllers/Tools/Map/Components/Map.tsx:3:1)
      at Object.<anonymous> (Scripts/Controllers/Tools/Map/Components/__tests__/Map.test.tsx:3:1)


My config:
```javascript
module.exports = {
  setupFiles: [
    "./testConfig/test-shim.js",
    "./testConfig/test-setup.js"
  ],
  transform: {
    "^.+\\.tsx?$": "ts-jest"
  },
  transformIgnorePatterns: [
    "/node_modules/(?!(ol)/).*/",
    "node_modules/(?!(ol)/)"
  ],
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
  moduleNameMapper: {
    "^(Controllers|Api|Utilities)/(.*)$": "<rootDir>Scripts/$1/$2"
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  coverageReporters: ["text", "text-summary", "html"],
  coverageDirectory: "testConfig/coverageReport",
  collectCoverageFrom: ["**/Scripts/{App,Controllers,Utilities,Localization,EntryPoints}/**/*.{ts,tsx}"],
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0
    }
  }
};

```

**Comment by Primajin** [comment] 2018-12-10 16:57
We basically could only work around it in the end by overwriting the OL components in the testrunner with blank functions returning either undefined or another empty function (based on what was expected)

**Comment by jktravis** [comment] 2018-12-11 13:35
Thanks, @Primajin. I started down this path this morning, and things were going okay. But I noticed on the first mock that I created it as a `.js` file instead of a `.ts` file, and got a similar error, but the output was slightly different. And then it hit me that I'm probably not transforming _any_ `.js` files. 

Long story short, I added `babel-jest` and `jest-canvas-mock` to the project. Here are the changes I made to the config.

```javascript
  setupFiles: [
    "./testConfig/test-shim.js",
    "jest-canvas-mock", // <- mocking lib so your console won't bleed
    "./testConfig/test-setup.js"
  ],
  transform: {
    "^.+\\.tsx?$": "ts-jest",
    "^.+\\.jsx?$": "babel-jest", // <- transform JS files
  },
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
  transformIgnorePatterns: [
    "node_modules/(?!(ol)/)", // <- exclude the ol library from not being transformed
  ],
```

**Comment by Primajin** [comment] 2018-12-11 16:14
I was more about adding lines like these to your test file (ugly but works):

```js
jest.mock('../../../../node_modules/ol/format/GeoJSON', () => function() {});
jest.mock('../../../../node_modules/ol/geom/LineString', () => {});
// more stuff here whatever you need....
```

**Comment by ale-cristofori** [comment] 2018-12-18 11:11
Here's my two cents...

https://medium.com/@compatt84/how-to-test-open-layers-react-components-with-mocha-part-i-9a2ca0458ba1

https://medium.com/@compatt84/how-to-test-open-layers-react-components-with-mocha-part-ii-d91d65145bce

**Comment by bartvde** [comment] 2018-12-24 12:11
yeah it indeed looks like the solution I provided does not work with newer jest versions

**Comment by sanderdesnaijer** [comment] 2019-02-15 15:55
The solution of @jktravis worked for me, thanks! I only had to rename .babelrc to babel.config.js to make it work.

**Comment by orpheus** [comment] 2019-07-16 16:22
> The solution of @jktravis worked for me, thanks! I only had to rename .babelrc to babel.config.js to make it work.

when I did this and added:
```
 "transformIgnorePatterns": [
      "node_modules/(?!(ol)/)"
    ],
```

it worked... but I have no idea why. If I go back to .babelrc with the transformIgnorePatterns it won't work ??

**Comment by aloulouamine** [comment] 2019-07-26 09:16
> ```
>  "transformIgnorePatterns": [
>       "node_modules/(?!(ol)/)"
>     ],
> ```


After adding this block test time get increased by 5 minutes for every file.

**Comment by jktravis** [comment] 2019-07-26 11:15
I had the same issue. I thought it was just my implementation. But yeah. It’s super slow.

**Comment by nikolas** [comment] 2020-01-07 17:20
I'm running into this problem even with the `transformIgnorePatterns` fix. Here's the jest section of my package.json:
```
   "jest": {
     "testMatch": [
       "<rootDir>/media/js/src/**/?(*.)(spec|test).js?(x)"
     ],
     "testEnvironment": "node",
     "testURL": "http://localhost",
     "transform": {
       "^.+\\.jsx?$": "babel-jest"
     },
     "transformIgnorePatterns": [
       "/node_modules/(?!(ol)/)"
     ]
   }
```

And my jest output:
```
$ npm run test

> mediathread@0.1.0 test /home/nik/src/d/mediathread
> jest

 FAIL  media/js/src/GridAsset.test.jsx
  ● Test suite failed to run

    /home/nik/src/d/mediathread/node_modules/ol/Feature.js:29
    import { assert } from './asserts.js';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import AnnotationScroller from './AnnotationScroller';
      5 | 
    > 6 | import Feature from 'ol/Feature';
        | ^
      7 | import Map from 'ol/Map';
      8 | import View from 'ol/View';
      9 | import GeoJSON from 'ol/format/GeoJSON';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (media/js/src/GridAsset.jsx:6:1)

Test Suites: 1 failed, 1 total
```

```

**Comment by nikolas** [comment] 2020-01-07 17:46
Okay well, using this babel.config.js fixed my problem:
```
module.exports = {
  "presets": [
    ['@babel/preset-env', { targets: { node: 'current' } }],
    "@babel/preset-react"
  ]
}
```
from https://github.com/facebook/jest/issues/6229#issuecomment-551916758

**Comment by smtalha** [comment] 2020-10-05 14:48
Since CLI options take precedence over custom jest config, adding the `--transformIgnorePatterns` option to the test script command worked for me without ejecting the create-react-app
```
...
"test": "CI=true react-scripts test --transformIgnorePatterns \"node_modules/(?!ol)/\"",
...
```

**Comment by findawayer** [comment] 2021-01-17 06:02
I came up with a different approach, which is to transpile the whole package to commonjs once then use this version for testing. Below is the minimal reproduction of my settings in `package.json`.

```json
{
  "scripts": {
    "test": "jest",
    "test:watch": "jest --watch",
    "test:prepare": "babel node_modules/ol --extensions .js --out-dir node_modules/.compiled/ol --presets @babel/preset-env  --source-maps"
  },
  "dependencies": {
    "ol": "^6.4.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.12.10",
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "jest": "^26.6.3",
  },
  "jest": {
    "moduleDirectories": [
      "node_modules/.compiled",
      "node_modules"
    ],
  }
} 
```

Run `test:prepare` to make a test-ready version of OpenLayers in `node_modules/.compiled` and your node will not complain about ES module syntax.


**Pros**
- OpenLayers does not get transformed on the fly. -> It's faster

**Cons**
- You need to manually run `test:prepare` when you move to a different version of OpenLayers.

**Comment by aalbericio** [comment] 2023-01-27 08:29
Thank you, @iStefo 

I really prefer your solution over the babel based one. It's faster and simpler to configure but I'm getting this configuration error now:

`Could not locate module ol/format mapped as:
 C:\Projects\Source\html5-console\packages\core\node_modules\.compiled\ol\ol.js.`

This comes from an utility importing Openlayers stuff, of course (import { GeoJSON, WKT } from 'ol/format').

I mean, the .compiled/ol/ol.js is there but it keeps reporting that configuration error.

Thanks

**Comment by aalbericio** [comment] 2023-02-03 12:27
Hello @iStefo ,

First of all, thanks for your solution. ESBUILD is really fast and I thought it was all fixed using this approach but then some other errors started to arise:

They were all related to the ol/style package that could not find constructors for classes like: Fill, Stroke, etc

I decided to move to:

`babel node_modules/ol --extensions .js --out-dir node_modules/.compiled/ol --presets @babel/preset-env`

and a jest module mapper:

`'^ol/(.*)$': 'node_modules/.compiled/ol/$1.js',`

**And that made the trick**. However, I still want to use ESBUILD but I think that my tests don't like its single-file output or something inside that ol.js file is not really compliant with Jest.

I've been reading wether ESBUILD can keep file structure but I think it can not.

I'd appreciate if you have any other tip I can use.

Thanks in advance.
