### ISSUE TITLE
Modify interaction on the Mobile WebView Can not move point with continuous.

### ISSUE THREAD

**Issue by Haozi0456** [openlayers/openlayers#11167] opened 2020-06-10 07:25 UTC
**Describe the bug**
Modify interaction in the Android Mobile WebView can not moving point with continuous.  can moved point a little distance very once.  How to moving point with continuous ?? Thanks!

**Comment by ahocevar** [comment] 2020-06-11 08:17
Duplicate of #10940, already fixed.

**Closed by ahocevar** 2020-06-11 08:17 UTC

**Comment by Haozi0456** [comment] 2020-06-12 02:36
Thanks
