### ISSUE TITLE
Blend Example not working

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#11020] opened 2020-05-08 00:22 UTC
**Describe the bug**
https://openlayers.org/en/latest/examples/blend-modes.html does not work

**To Reproduce**
Go to https://openlayers.org/en/latest/examples/blend-modes.html

**Expected behavior**
Example needs to work

**Comment by fredj** [comment] 2020-05-08 07:02
Duplicate of #10505

**Comment by ahocevar** [comment] 2020-05-09 09:39
Removed old assets from https://openlyers.org/en/latest/

**Closed by ahocevar** 2020-05-09 09:39 UTC
