### ISSUE TITLE
When adding draw interaction, it flickers while zooming in and out (Version 9.0.0)

### ISSUE THREAD

**Issue by hydrogen2oxygen** [openlayers/openlayers#15644] opened 2024-03-16 10:49 UTC
This happens only with the newest version 9.0.0. Adding a draw interaction, like drawing polygon, the map flickers while zooming.
The polygon is still visible, but the map under it disappears and flickers. Sometimes it even is blank when I stop zooming.

Style:

```ts
  styleRedOutline: Style = new Style({
    fill: new Fill({
      color: [0, 0, 0, 0.1]
    }),
    stroke: new Stroke({
      color: [255, 0, 0, 0.5],
      width: 5
    })
  }
```

Initialization:

```ts
   const osmLayer = new TileLayer({
      source: new OSM()
    });

    let that = this;

    this.vectorLayer = new VectorLayer({
      source: this.source,
      style: function (feature) {
        return that.styleRedOutline;
      }
    });

    this.view = new View({
      center: [-472202, 7530279],
      zoom: 12
    });
    this.map = new olMap({
      layers: [
        osmLayer,
        this.vectorLayer
      ],
      view: this.view,
      controls: []
    });
```

Adding drawing interaction:

```ts
this.interaction = new Draw({
      type: 'Polygon',
      source: this.source
    });

    let draw: Draw = this.interaction;

    draw.on('drawend', evt => {
      console.log("drawEnd")
      this.lastSelectedFeature = evt.feature;
    });

    this.map?.addInteraction(this.interaction);
```

I tried to trigger layer change and other stuff, but it seems to be a problem with the version 9.0.0. With 8.2.0 it does not happen.

**Comment by ahocevar** [comment] 2024-03-17 18:30
Can you please try if the problem goes away when you `npm install ol@dev`?

**Comment by radokostelnik** [comment] 2024-03-18 09:56
Reproducible in 9.0.0 version of *Draw and Modify Features* example: https://openlayers.org/en/v9.0.0/examples/draw-and-modify-features.html

The same example in 8.2.0 is OK: https://openlayers.org/en/v8.2.0/examples/draw-and-modify-features.html

**Comment by ahocevar** [comment] 2024-03-18 10:51
@radokostelnik What exactly are the steps to reproduce? Also, does it work as expected in https://openlayers.org/en/main/examples/draw-and-modify-features.html

**Comment by radokostelnik** [comment] 2024-03-18 11:27
@ahocevar Steps: 
- Open the page
- Zoom in/out using mouse wheel or the zoom -+ buttons or "zoom to area" interaction.

The OSM map flickers and randomly ends up blank. I can reproduce the same also in the _main_ version.

Further info: I tried to build the example locally, but I could not reproduce it in that _trimmed_ version.

**Comment by ahocevar** [comment] 2024-03-18 12:59
Thanks @radokostelnik. So you‘re saying when running the example from a local clone of OpenLayers with `npm start`, it works as expected?

**Comment by radokostelnik** [comment] 2024-03-18 14:34
@ahocevar Not exactly a local clone. I created the 3 files from the example on the disk, ran 'npm start'. In this case, the behavior is not reproducible with ol@9.0.0.

When running `npm run serve-examples` from a local clone, the behavior is reproducible.

**Comment by wjoel** [comment] 2024-03-18 17:23
I saw flickering when upgrading to 9.0.0 as well. A possible workaround (works for me) is to use the WebGL renderer, `import TileLayer from "ol/layer/WebGLTile"`.

I tried the "Draw and Modify Features" example on my laptop at work, and it did not flicker. At home, it flickers, and goes blank at some zoom levels, but after I've drawn a circle it stops flickering and doesn't go blank. Very odd.

The page linked by @karussell flickers constantly and "reliably" ends up with a blank map (I can try it at work tomorrow).

Using Chromium (at home, didn't try it at work), both pages work fine.

Maybe it has something to do with Nvidia drivers?

Desktop at home, flickers: Fedora, Sway, Wayland, Firefox Nightly, Nvidia proprietary drivers.
Laptop at work, doesn't flicker: Fedora, Sway, Wayland, Firefox, Intel graphics.

**Comment by ahocevar** [comment] 2024-03-18 18:38
Thanks for all the reports so far. I suspect this is a duplicate of #15593.

I'm still not sure whether the issue has been fixed since v9.0.0 or not. Can anyone who experiences the flickering please try https://deploy-preview-15620--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html ?. Thanks!

**Comment by wjoel** [comment] 2024-03-18 18:56
@ahocevar that works the same for me at least - flickers on zoom and the map sometimes disappears, but again it stops flickering once I've placed a marker (I guess doing so triggers some sync/redraw on zoom changes that doesn't happen otherwise?).

**Comment by radokostelnik** [comment] 2024-03-18 20:45
> Thanks for all the reports so far. I suspect this is a duplicate of #15593.
> 
> I'm still not sure whether the issue has been fixed since v9.0.0 or not. Can anyone who experiences the flickering please try https://deploy-preview-15620--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html ? Thanks!

I still see random flickering on the preview-15620 page. After placing a geometry it usually stops, but after panning to another location and/or zooming in it starts again. 
Windows + Chrome or Edge, Nvidia graphics.

**Comment by ahocevar** [comment] 2024-03-18 20:50
Thanks everyone so far. Can anyone do a `git bisect` with `npm start` and a local clone of the library to find out which commit introduced the flickering?

**Comment by wjoel** [comment] 2024-03-18 20:59
`git bisect` points to 628deb063.

**Comment by ahocevar** [comment] 2024-03-18 21:45
Thanks @wjoel, this confirms my suspicion. If you have the test setup still available, can you please try if #15649 fixes the problem?

**Comment by ahocevar** [comment] 2024-03-18 21:50
If anybody else wants to test a potential fix, please try https://deploy-preview-15649--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html.

**Comment by wjoel** [comment] 2024-03-18 22:12
@ahocevar it unfortunately doesn't help, same issue. Maybe there are other changes made since that could affect this, as to my eyes your PR seems to revert the problematic change? I double checked and 9aa5f20e72 works for me, no flickering on that one.

**Comment by ahocevar** [comment] 2024-03-19 06:35
@wjoel Ok, can you try to continue bisecting and see when it broke again?

**Comment by ahocevar** [comment] 2024-03-19 07:53
@wjoel and everyone else affected by this issue, can you please test #15651: https://deploy-preview-15651--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html

**Comment by radokostelnik** [comment] 2024-03-19 08:00
@ahocevar Looks good to me, no flickering.

**Comment by ahocevar** [comment] 2024-03-19 08:26
Ok, thanks for the feedback @radokostelnik. What about https://deploy-preview-15652--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html, does that fix the issue too?

**Comment by hydrogen2oxygen** [comment] 2024-03-19 08:50
@ahocevar thank you very much, both examples works fine, no flickering before or after drawing features.

**Comment by radokostelnik** [comment] 2024-03-19 09:35
@ahocevar This is strange. I see flickering in the #15652 version, but only in Chrome (Version 122.0.6261.129 (Official Build) (64-bit)). Edge (Version 122.0.2365.92 (Official build) (64-bit)) on the same machine does not flicker.

**Comment by ahocevar** [comment] 2024-03-19 09:43
@radokostelnik So you're saying that #15651 works reliably and #15652 does not?

**Comment by radokostelnik** [comment] 2024-03-19 09:47
@ahocevar Yes, that's what I'm seeing here.

**Comment by radokostelnik** [comment] 2024-03-19 10:01
https://github.com/openlayers/openlayers/assets/2410648/7478c80a-5d4f-496b-bd29-90b2c7ad9569

@ahocevar Attached a screen capture video from the #15652 version.

**Comment by ahocevar** [comment] 2024-03-19 11:21
@radokostelnik When the test website for #15652 has been rebuilt in a few minutes, can you please try again? I made a change so the transform matrix will be the same as in #15651.

**Comment by radokostelnik** [comment] 2024-03-19 11:42
@ahocevar Tested now on https://deploy-preview-15652--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html, still seeing the flickering.

**Comment by ahocevar** [comment] 2024-03-19 11:50
@radokostelnik Did you clear the cache? And you‘re sure there is no flickering with #15651?

**Comment by radokostelnik** [comment] 2024-03-19 12:07
@ahocevar Yes, "Empty Cache and Hard Reload", multiple times, in both Chrome and Edge. I don't see flickering in 15651, I do in 15652, in both of them.
TBH, I'm not "sure" about no flickering in 15651, but based on my quick tests, I can't see it there.

**Comment by ahocevar** [comment] 2024-03-19 13:18
@radokostelnik For both versions: what’s the output of `document.querySelectorAll('.ol-layers canvas').length`?

**Comment by radokostelnik** [comment] 2024-03-19 13:29
@ahocevar `1` for 15652, `2` for 15651

**Comment by radokostelnik** [comment] 2024-03-19 15:54
@ahocevar Looks good, I can't reproduce flickering on https://deploy-preview-15652--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html.

**Comment by ahocevar** [comment] 2024-03-19 15:55
Thanks @radokostelnik, anyone else want to try?

**Comment by Dolyka** [comment] 2024-03-19 17:01
@ahocevar Confirm, looks good

**Comment by wjoel** [comment] 2024-03-19 17:15
Nice work! I can confirm, no flickering on https://deploy-preview-15651--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html or https://deploy-preview-15652--ol-site.netlify.app/en/latest/examples/draw-and-modify-features.html

**Closed** 2024-03-21 12:36 UTC
Labels: bug
