### ISSUE TITLE
RGBA Hex Color throws assertion error 14 (Invalid Color)

### ISSUE THREAD

**Issue by Siedlerchr** [openlayers/openlayers#7429] opened 2017-11-07 22:20 UTC
First of all, thanks for the great library! Really awesome.

I am coloring an Icon and I receive an error, if I specify the color code as a rgba hex value.  I get the assertion error 14, invalid color, although this is a valid rgba color.
So I tried a bit around and found that only the hex representation does not work.
Although css nowadays allows 8 digit hex codes:
https://drafts.csswg.org/css-color/

The culprit seems to be the RegEx expression in color.js
https://github.com/marcjansen/ol3/blob/8d5a8665b233a8a59d722c063c37d9b2d2c978a6/src/ol/color.js#L13

Example:
```js
  return new Style({
        image: new Icon(/** @type {olx.style.IconOptions} */ ({
            anchor: [0.5, 46],
            anchorXUnits: 'fraction',
            anchorYUnits: 'pixels',
            color: '#00AB41FF',
            offset: coords,
            size: [64, 64],
            src: 'img/icon.png'
        }))
    });

"#00AB41FF" ; //Doesnt work
rgba(0,171,65,1)  //hex to rgba 
[0,171,65,1] //works
"green" //works
```

As a workaround I found this [converter from/to hex/rgba](https://kilianvalkhof.com/2016/css-html/css-hexadecimal-colors-with-transparency-a-conversion-tool/)

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by tschaub** [comment] 2017-11-07 23:30
Although the CSS spec allows for it, not all canvas implementations support hex colors with alpha I'm seeing that it doesn't currently work on Chrome, for example (and this is odd given that `rgba` strings do work.)  There are places where we use the `color` values in a fill or stroke directly in the canvas context `fillStyle` or `strokeStyle`.  So you may get unexpected results if you use hex strings with alpha as fill or stroke color.  That said, we can update the color conversion/parsing code to support 4 or 8 digit hex colors.

**Comment by tschaub** [comment] 2017-11-07 23:34
Actually, it could just make things worse to support hex with alpha in `ol.color.fromString()` if things will just fail later when this string is used as `fillStyle` or `strokeStyle`.

**Comment by tschaub** [comment] 2017-11-07 23:55
@Siedlerchr take a look at https://codepen.io/tschaub/pen/GONRWb/ - demonstrating that (at least in Chrome) hex colors with alpha don't work in canvas.

![image](https://user-images.githubusercontent.com/41094/32524325-6a4b3b6c-c3dc-11e7-9fb2-8db6405ef5c3.png)

**Comment by Siedlerchr** [comment] 2017-11-08 09:05
Thank you for your detailed response! I am getting the hex colors from an external application in a json file. So it would be nice to have it supported in OL instead of doing my own conversion.
As the hex color is not directly supported in the canvas, my idea would have been to convert it to rgba, before applying it. (Seems like you had the same idea in the PR).

**Comment by tschaub** [comment] 2017-11-08 17:59
It looks like hex parsing with alpha was just fixed in Chrome 62 (see https://bugs.chromium.org/p/chromium/issues/detail?id=76362).  I confirmed that the [example above](https://codepen.io/tschaub/pen/GONRWb) works in Safari, Firefox, and Chrome 62.  So I think the change in #7430 makes sense.

**Closed** 2017-11-09 13:38 UTC
