### ISSUE TITLE
GeoTIFF rotation

### ISSUE THREAD

**Issue by carmenmarquez** [openlayers/openlayers#15370] opened 2023-11-24 10:06 UTC
Hello,
I'm trying to load a TIF into OpenLayers but it doesn't seem to be rotating the image.
In QGIS it is displayed correctly.
The URL is: http://ftpcdd.cnig.es/Vuelos_2015_2016/Vuelos_2015/Baleares/1.VF/1.08_PNOA_L6_2015_BAL_25cm_VF_img8c_rgb_hu31/h50_0697_fot_002-0015.tif
The projection is EPSG:25831.

Example:
const sources = [new GeoTIFF({
   convertToRGB: 'auto',
   sources: [{
     url: 'https://ftpcdd.cnig.es/Vuelos_2022/Vuelos_2022/extremadura_2022/Sur/01.VF/01.08_PNOA_2022_EXT_S_22cm_VF_img8c_rgb_hu29/h50_0752_fot_02-3221_cog.tif',
   }, ],
})];

const layer = new TileLayer({
   sources: sources,
});

I attach a screenshot of how it is displayed in QGIS and OpenLayers.

all the best
![QGIS](https://github.com/openlayers/openlayers/assets/24248099/a22ac292-0f98-4f3c-9596-785ee4f6efef)
![Ol](https://github.com/openlayers/openlayers/assets/24248099/eaf9249a-1975-4edd-915b-c53f3e257bbc)

**Comment by mike-000** [comment] 2023-11-28 14:09
Duplicate of #15294

**Comment by mike-000** [comment] 2023-12-08 19:40
It would work with #15402 https://jsfiddle.net/c9mejsLa/

**Comment by carmenmarquez** [comment] 2023-12-12 08:40
Hi Mike, thank you very much for your response.
I wanted to ask:
- Is it possible for the image to display correctly without modifying the map view?
- Is it possible not to limit the movement of the map only to the area where it is located in COG?

**Comment by mike-000** [comment] 2023-12-12 11:19
You can view it in any projection you want, but you must ensure the GeoTIFF projection is registered with proj4 https://jsfiddle.net/1xpc7t4r/

**Closed** 2024-10-10 17:55 UTC
Labels: bug
