### ISSUE TITLE
WebGL issue rendering holes in MultiPolygons

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#15089] opened 2023-09-06 17:49 UTC
I'm seeing an issue rendering MultiPolygon geometries with holes using the WebGL vector layer renderer.

See this example for a demonstration of the problem: https://codesandbox.io/s/webgl-vector-layer-forked-wqlzkx?file=/main.js

<img width="564" alt="image" src="https://github.com/openlayers/openlayers/assets/41094/4be2d7b5-15ea-4cdd-a692-057c1e4dd2ed">

This dataset represents the world oceans, with the land masses as holes in the ocean polygons.

The same dataset renders correctly using the Canvas vector layer renderer: https://codesandbox.io/s/vector-layer-forked-cpvh24?file=/main.js

The WebGL vector layer renderer works with a version of this dataset where the polygon rings are not wound according to the right-hand rule (exterior rings counterclockwise, interior rings clockwise).  Here is a working example using the WebGL vector layer renderer with a version of the data that doesn't follow the right-hand rule: https://codesandbox.io/s/webgl-vector-layer-forked-vjrxtv?file=/main.js

**Update:** I created a much simpler geometry to demonstrate the problem

 * Working version with the Canvas renderer: https://codesandbox.io/s/vector-layer-forked-2xdlqt?file=/main.js
 * Non-working version with the WebGL renderer: https://codesandbox.io/s/webgl-vector-layer-forked-hf5gg3?file=/main.js

**Comment by jahow** [comment] 2023-09-06 19:58
I'm almost certain this is a duplicate of https://github.com/openlayers/openlayers/issues/14949

I've looked into this already and the problem is that currently the right-hand rule is used to decide whether a ring is a hole or not, because the vector tile source sometimes provide polygons which actually contain both outer rings and inner rings consecutively. This works seamlessly with the Canvas API so it wasn't much of a problem until now, but with WebGL it's not so simple.

Currently my guess is that an appropriate fix would be in the vector tile source to "clean up" polygons to guarantee that they are only made of 1 outer ring and inner rings afterwards. Then the right-hand rule wouldn't be used in the webgl renderer anymore.

See: https://github.com/openlayers/openlayers/blob/14f0e9d85f4c4fbf6666df9556f36e7d373d1968/src/ol/render/webgl/MixedGeometryBatch.js#L322-L345

**Comment by tschaub** [comment] 2023-09-06 21:05
> the problem is that currently the right-hand rule is used to decide whether a ring is a hole or not, because the vector tile source sometimes provide polygons which actually contain both outer rings and inner rings consecutively

I don't think I fully understand this.

It looks to me like [the current logic](https://github.com/openlayers/openlayers/blob/14f0e9d85f4c4fbf6666df9556f36e7d373d1968/src/ol/render/webgl/MixedGeometryBatch.js#L322-L345) is backwards.  We currently assume that a clockwise ring is the start of a polygon (an exterior ring).  The right hand rule says that exterior rings are counterclockwise.

I proposed #15090 to rework this.  But this will make it so improperly oriented polygons with holes are not properly rendered.

I imagine our options are to either properly wind rings when we parse data or create features or if possible to make things more tolerant by tracking the start of rings in addition to the start of polygons.

All that said, I haven't looked that deeply at the code.  So I'm really only going off what feels like a potential mistake in the mixed renderer batch logic.

**Comment by mike-000** [comment] 2023-09-06 23:45
Isn't the underlying problem that WebGL is using `getFlatCoordinates()`

https://github.com/openlayers/openlayers/blob/main/src/ol/render/webgl/MixedGeometryBatch.js#L189
https://github.com/openlayers/openlayers/blob/main/src/ol/render/webgl/MixedGeometryBatch.js#L229

where canvas is using `getOrientedFlatCoordinates()`

https://github.com/openlayers/openlayers/blob/main/src/ol/render/canvas/PolygonBuilder.js#L169
https://github.com/openlayers/openlayers/blob/main/src/ol/render/canvas/PolygonBuilder.js#L212

**Closed** 2023-09-11 15:39 UTC
Labels: bug
