### ISSUE TITLE
"loadstart"/"loadend" event or similar for ol.source.ImageWMS

### ISSUE THREAD

**Issue by regiodata** [openlayers/openlayers#2636] opened 2014-08-27 07:00 UTC
Right now there seems to be no way to determine whether a WMS-image source is in loading-state or not.
(see https://groups.google.com/forum/#!topic/ol3-dev/qFc1Xm5_VBc; https://groups.google.com/forum/#!searchin/ol3-dev/loadend/ol3-dev/H13hTihzxwU/vaEvsG-8QdsJ)

Especially on mobile devices with poor network connectivity its really important to see whether the map is loading or not.

In my opinion and for 2.x compatibility this feature is really important for the 3.0 release.

**Comment by regiodata** [comment] 2015-01-26 07:17
As a workaround we use an custom image-load method like this:

```javascript
//global variable indicating loading-status
var int_layer_loading = 0;

//ImageLoad-method to catch image-load-events
var function_image_load = function(image, src)
{
	var int_event_id = new Date().getTime();
	
	//set loading-status
	int_layer_loading = int_event_id;
	
	//set loading message
	//...
	
	//set image source
	image.getImage().src = src;
	
	//onload-listener of image-object
	image.getImage().onload = function()
	{
		//if latest request, then reset loading status
		if (int_layer_loading == int_event_id)
		{
			int_layer_loading = 0;
			
			//unset loading message
			//...
		}
	};
}
		
//create layer
var obj_layer = new ol.layer.Image(
{
	source: new ol.source.ImageWMS(
	{
		//[...]
		imageLoadFunction: function_image_load
	 })
});
```

**Comment by davidlonjon** [comment] 2015-02-09 05:09
I have approached it that way:

I am using the precompose event of the ImageWMS layer source. I am looking at the stage of the image (1 is LOADING, 2 is READY, and 3 is ERROR). By running the debug version of OL3 and looking at the console in Chrome, I found out the image state is under "event.target.a.d.state"
 
```
layer.on('precompose', function(event) {

  var imageState = event.target.a.d.state;

  if (imageState === 1) {
    showLoader();
  }

  if (imageState === 2 || imageState === 3) {
    hideLoader();
  }

  if (imageState === 3) {
    displayErrorMessage();
  }
});
```

This is probably an hacky way but it works for me. Maybe it can help as temporary solution?

**Comment by dropyghost** [comment] 2015-03-09 22:52
@ahocevar i can implement your code, but how you make a request to retry? I can keep a track of what images is being loaded, i can put a timer so if the status is still Loading cancel and try again. Do you know how to do that?

in my case some pieces arent retrive because mapserver is too slow.
But ol3 doesnt try to download again. Even if i change zoom to other layers when i return the space is still empty. I need to wait lot of time until a time out occurs or refresh the whole page.


![image](https://cloud.githubusercontent.com/assets/10077853/6566067/e6407e08-c687-11e4-80d2-ac659aa14dbf.png)

![image](https://cloud.githubusercontent.com/assets/10077853/6566071/ed71e8b0-c687-11e4-8cd0-b82ac38ce61f.png)

![image](https://cloud.githubusercontent.com/assets/10077853/6566176/f1696aaa-c688-11e4-8f66-7d9603a868fd.png)

**Comment by bartvde** [comment] 2015-03-10 07:43
have you seen #3248 which was released in 3.3.0 ?

**Comment by dropyghost** [comment] 2015-03-11 14:59
As a visual aid is great. But still doesnt help to reload the frozen request.

I think every request should have some timeout parameter or a method to allow repeat the request.

Please let me know if this is something worth of creating a new issue. 
As you can imagine i can't have my app with those white holes. I know the issue is a combination of my slow internet and slow mapserver. But that is the usual scenario in my country.

I can tolerate 30 seconds for load (usally much faster) but 5 minutes and no way to reload unless I reload the whole page isnt.

I'm willing try to update the code if someone point me in the right direction. #3248 already handle each image to increase the progress bar. I just need to create a timer for each request. But i dont know how I restart the request.

Will have a setting like 
MaxNumberRetry = 5;
Timeout =  1000ms
FailImage = redcross.png

![mapserver2jpg](https://cloud.githubusercontent.com/assets/10077853/6598629/32cacefe-c7d7-11e4-9c7f-ce84c5f9005e.jpg)

**Comment by dropyghost** [comment] 2015-03-11 18:07
@regiodata That imageLoadFunction is only for ImageWMS? or work for TileWMS too? I try to look on the documentation and didnt found it. I try to use it on my sample and do nothing, not even show an error.

**Comment by regiodata** [comment] 2015-03-12 06:15
@dropyghost My imageLoadFunction can be used for loading one image at a time and show a loading animation. For example ol.source.ImageWMS (http://openlayers.org/en/v3.3.0/apidoc/ol.source.ImageWMS.html?unstable=true) and also ol.source.ImageMapGuide (http://openlayers.org/en/v3.3.0/apidoc/ol.source.ImageMapGuide.html?unstable=true). 
But keep in mind that the **unstable property** "imageLoadFunction" is used.

**Comment by dropyghost** [comment] 2015-03-12 14:32
@regiodata thanks for the link. Result searching imageLoadFunction in google take you to v3.1 doc and that function appear is on v3.3. There is a titleLoadFunction for TileWMS. I will try that.

**Comment by bartvde** [comment] 2017-01-06 14:52
this was done with #3248

**Closed by bartvde** 2017-01-06 14:52 UTC
