### ISSUE TITLE
Visibility of layers in a group when it is unchecked

### ISSUE THREAD

**Issue by simod** [openlayers/openlayers#6239] opened 2016-12-13 14:06 UTC
Hi all, I'd like to start a discussion about the group visibility behaviour after some feedback from @bartvde.
The default behaviour doesn't show a checked layer when its group is unchecked, this has a logic but from a user perspective I would expect to be able to uncheck the whole group then just make visible some of the layers.
As a use case, when a group contains a long list of visible layers and I'm interested in only few of them, it would be much more handy to hide all by unchecking the group and the only check them.
So the role of the group would just be check/uncheck all but not to control the visibility of a layer.

Thanks for any feedback

**Comment by bartvde** [comment] 2017-08-10 12:10
@simod I think we can close this ticket here

it seems the way ol handles it currently is by design
for layerlist grouping a separate approach not using layer groups would be the way forward I think

**Closed by bartvde** 2017-08-10 12:10 UTC
