### ISSUE TITLE
the point of having dependencies when the 'main' in package.json is dist/ol.js

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#7025] opened 2017-07-17 14:18 UTC
Hi there,

I use openlayers in a product we're building. I have lots of trouble downloading and installing all dependencies trough npm (often failures, new versions etc.) while only using the pre-compiled dist/ol.js.

Why are all those dependencies not dev dependencies?

shouldn't there be a choice?
- either you point the main to /src/ol.js, let the user compile all the code, including dependencies
- or you point the main to /dist/ol.js and remove all dependencies (exclusing ofcourse dev-dependencies)

Correct me if i'm wrong, i'm trying to grasp the concept of dependencies and packages here..

**Comment by BasieP** [comment] 2017-07-18 07:08
To further support my case:

When i install openlayers in my own project (using 'npm install openlayers --save')
I download loads of dependencies.
When i go into my node_modules, and remove all installed dependencies i am still perfectly able to run the project with my openlayers map inside it.

I have 1 node module now in my node_modules folder, 'openlayers'  which contains the 'css' folder, the 'dist' folder and a package.json.

This is because the dist/ol.js contains ALL javascript openlayers will ever need.


The downside of this (and the current way of packaging), is that dependencies of openlayers (lets say for example: 'async'), can be used by my own little project as well.
Because i use the openlayers 'bundle' (the file in 'dist' folder), i have my own little code of 'async' and also the one bundled in your 'openlayers' bundle.


This is a bad thing because it means all clients download the same code twice. the total number of bytes transfered to a browser goes up and up.
In this case it's not much, but if i use jquery and you use jquery we're gonne add the entire jquery lib twice.

On the other hand there is the versioning argument. Since versioning of packages in npm sucks hard (everybody commits code without upping there version numbers, and everybody uses the carrot for referring to a dependency) you can build the same version twice, and get totally different output.
To counter this behavior it is common practice to bundle all dependencies into 1 file, and give that specific file your own version. onces published, it doesn't change because everything is in that 1 file.

Resumé:
There are 2 options:
1 remove all dependencies from package.json (move them to dev dependencies), and point the 'main' to the 'dist/' folder
2 point to 'main' to the 'src/' folder.

Option 1 gives:
pro: 
- easily distributable
- only 1 build per version (so 4.2.0 is always the same, since you build it)
con:
- users can have larger packages if they use the same dependencies

option 2 gives:
pro:
- lower package size
- more control over dependency versions (ie: they can use a newer version of async in version 4.2.0 of openlayers)

cons:
- longer npm install times
- more chance of some morron in a deep dependency breaking your build all of a sudden

**Comment by ahocevar** [comment] 2017-07-18 14:16
Have you tried using the official [ol](https://npmjs.com/package/ol) package instead? It does not have any of these headache dependencies.

**Comment by BasieP** [comment] 2017-07-19 05:59
yes i have. The problem there is that i would like to bundle all of openlayers into our library.
when i have to do that with the 'ol' package, i have to import all of the files into the project by building my own loader.
secondly i miss the .css files. i haven't dived into that so perhaps i can generate them orso, but the last thing i want is copy-paste the /dist/ol.css from the openlayers package into my own project.
also the ol package is using babel, typescript etc, so i need to add all those dependencies as well..
(since we're building in vanilla.js)

And last, but not least:
Walking around a problem in the openlayers package is not quite my style. If i don't understand why things are they way i would like them to be i have two options:
1. understand why they are the way they are.
2. change them so they are they way i want them.

**Comment by probins** [comment] 2017-07-19 07:39
I think this is a duplicate of #3157. `dependencies` are those needed when creating custom builds; `devDependencies` are those needed for the full CI (Travis). As stated in https://github.com/openlayers/openlayers/issues/3157#issuecomment-276928266, IMO there should be a separate package with only the `dist` files.

**Comment by BasieP** [comment] 2017-07-19 20:19
Could very well be a duplicate. Point is that it's two years old. If users have this problem for the last two years and nobody fixes it (which is simple imho) then please stop calling it open source...

**Comment by ahocevar** [comment] 2017-07-24 19:42
@BasieP `ol.css` is included in the ol package. You can e.g. use the technique described in https://webpack.github.io/docs/stylesheets.html to include it in your bundle.

**Comment by tschaub** [comment] 2017-07-24 20:29
Here is an updated link for webpack 2+: https://webpack.js.org/loaders/style-loader/

> The problem there is that i would like to bundle all of openlayers into our library.

@BasieP - the ol package is useful for people who use existing module bundlers like webpack, Browserify, or Rollup.  As @ahocevar points out, the `ol.css` stylesheet is included in the package.  I've updated the [`ol-webpack` example](https://gist.github.com/tschaub/79025aef325cd2837364400a105405b8#file-main-js) to show how it can be used.  If you are using a custom bundler for your application or library, it should not be surprising that extra work will be required on your part.

The ol package currently requires a lot of explicit imports.  For example, you can't get all source types by importing `ol/source` (instead you just import what you use like `ol/source/xyz`).  In a future major release, we could support these types of aggregate imports (with more than one named export per module).  Until then, import the default export from the modules that you use.

**Closed by tschaub** 2017-07-24 20:29 UTC
