### ISSUE TITLE
Incompatibility with latest Google Maps API

### ISSUE THREAD

**Issue by JimBacon** [openlayers/openlayers#1450] opened 2015-05-27 08:12 UTC
The current experimental release of the Google Maps v3 API (3.21), which will become their next release, has introduced a change that causes a problem when used with OpenLayers 2.13.1.

A page containing a  StreetView map does not get the map tiles on page load. The map only appears when zoomed or panned. An issue has been raised with Google, https://code.google.com/p/gmaps-api-issues/issues/detail?id=8092, but they have asked that an issue be raised here.

**Comment by bartvde** [comment] 2015-05-27 08:20
I'd recommend just asking for a specific version of the GMaps API in your script tag.

**Comment by ahocevar** [comment] 2015-05-27 08:22
> I'd recommend just asking for a specific version of the GMaps API in your script tag, like they say in the referenced post.

Specific versions get phased out. This will only give you limited leeway. Your best option is to use a different base map.

**Comment by bartvde** [comment] 2015-05-27 08:30
is it known when v3 will be phased out?

**Comment by JimBacon** [comment] 2015-05-27 08:30
v3.20, which still works, will be phased out in November.

**Comment by szekerest** [comment] 2015-05-27 14:51
I'm experiencing the same issue, does anyone know a workaround?

**Comment by JimBacon** [comment] 2015-05-27 14:57
A short term work around is to specify the version of the Google Maps API that you are loading, as described in the Google issue linked above.

**Comment by szekerest** [comment] 2015-05-27 15:08
Another solution is to set the initial extent using a timeout delay, like:

setTimeout(function () { map.zoomToExtent(new OpenLayers.Bounds(...)); }, 500);

Looks like they suppress loading the tiles during the page loading phase or something.

**Comment by JimBacon** [comment] 2015-05-27 15:14
Would you like to post your findings in the Google issue as it might help them explain the problem or possibly even fix it if they consider it a bug?

**Comment by szekerest** [comment] 2015-05-27 15:21
The 3rd solution is to add the google div to the map and call resize regardless if the google mapobject was rendered. This probably triggers getting the tiles initially, so modify (lib\OpenLayers\Layer\Google\v3.js) this way:

if (!cache.rendered) {
                        var me = this;
                        google.maps.event.addListenerOnce(this.mapObject, 'tilesloaded', function() {
                            cache.rendered = true;
                            me.setGMapVisibility(me.getVisibility());
                            me.moveTo(me.map.getCenter());
                        });
                    }
                    map.div.appendChild(container);
                    cache.googleControl.appendChild(map.viewPortDiv);
                    google.maps.event.trigger(this.mapObject, 'resize');
                    
(remove the else condition)

**Comment by JimBacon** [comment] 2015-07-16 09:46
Google have closed the issue that I raised having concluded that the bug lies with OpenLayers.

**Comment by JimBacon** [comment] 2015-09-02 18:43
Google have released the next version of the Maps API which has prompted me to return to the problem. Now, if v3.21 is used, the maps no longer appear after panning or zooming. I have tried my own effort at prompting a resize after a timeout without success.

The 3rd solution, above, allows the map to appear on initial page load but it is then lost if I switch between Google Streets and Google Satellite layers. Without the 3rd solution in place, switching layers actually gets things working.

That does suggest that I might manage a workaround involve a programmatic switching of layers but I would be grateful if anyone can suggest anything better.

**Comment by fkaegi** [comment] 2015-09-02 19:12
Unfortunately we also encounter this problem again. I've initially reported it here https://code.google.com/p/gmaps-api-issues/issues/detail?id=8092 and google pointed back to openlayers. Our temporary workaround with adding V=3 to the google maps URL worked until their new version went productive now. Evtl. anybody is interested in an example page of the broken behavior: https://gango.com or https://gango.com/ask4task Switching the layers brings up the map images. We would be very grateful for any proposal of a sustainably workaround or fix to this incompatibility of latest google maps version with openlyers 2 - any idea? felix

**Comment by JimBacon** [comment] 2015-09-03 14:04
My mistake. The 3rd solution is looking good. When I first removed the else condition I did so in a way that meant the resize was included in the if(!cache.rendered) block. I repeat the suggestion above with indenting to try to help others avoid the same error.
```
if (!cache.rendered) {
    var me = this;
    google.maps.event.addListenerOnce(this.mapObject, 'tilesloaded', function() {
        cache.rendered = true;
        me.setGMapVisibility(me.getVisibility());
        me.moveTo(me.map.getCenter());
    });
}
map.div.appendChild(container);
cache.googleControl.appendChild(map.viewPortDiv);
google.maps.event.trigger(this.mapObject, 'resize');
```
Tried with v3.20, 3.21 and the current experimental version 3.22 of the Google API.

**Comment by fkaegi** [comment] 2015-09-03 16:50
Great solution and many thanx to @JimBacon - works as a charm!

For those using the compressed single OpenLayer.js file change following part of the file:
...
if(b.rendered)c.div.appendChild(e),b.googleControl.appendChild(c.viewPortDiv),google.maps.event.trigger(this.mapObject,"resize");else{var h=this;google.maps.event.addListenerOnce(this.mapObject,
"tilesloaded",function(){b.rendered=!0;h.setGMapVisibility(h.getVisibility());h.moveTo(h.map.getCenter())})}this.mapObject.setMapTypeId(d)}else
...

INTO this FIX:
...
if(!b.rendered){var h=this;google.maps.event.addListenerOnce(this.mapObject,
"tilesloaded",function(){b.rendered=!0;h.setGMapVisibility(h.getVisibility());h.moveTo(h.map.getCenter())})}c.div.appendChild(e),b.googleControl.appendChild(c.viewPortDiv),google.maps.event.trigger(this.mapObject,"resize"),this.mapObject.setMapTypeId(d)}else
...

**Comment by srfarley** [comment] 2015-09-04 18:30
I've created a fork with Jim's fix: https://github.com/v5analytics/openlayers

If you're using Bower, the dependency in `bower.json` will look like this:

    "openlayers": "git://github.com/v5analytics/openlayers.git"

**Comment by JimBacon** [comment] 2015-09-07 09:06
Credit to @szekerest for the fix, please. Also I have stopped rolling out that fix as I have encountered a problem with overlays that have not resized to match the base layer correctly.

**Comment by JimBacon** [comment] 2015-09-07 19:14
Regarding my problem with overlays mentioned above, what seems to be happening is that, when a vector layer is redrawn  as a result of a call to map.zoomToExtent, its features are not being erased so that the features appear both at the original zoom level and at the final zoom level. 

I can work around the problem by removing the layer before zooming and then adding it back in again. I don't know if this is an existing bug in OpenLayers, if we have introduced it by the fix above, or if it is just my lack of understanding about how to use OpenLayers. It is not clear to me from stepping through the code how old features should be being erased.

Any suggestions welcome.

**Comment by JimBacon** [comment] 2015-09-08 16:00
Further to the above post, I experience my problem with Google Maps 3.20 if I add the 3rd Solution whereas it is okay without the fix. I conclude that adding the 3rd Solution changes the behaviour of OpenLayers.

This means I have to alter the way in which I use OpenLayers. I have only seen it affect the initialisation process. Provided I wait until the Google 'tilesloaded' event has fired I can then proceed without problem.

**Comment by JimBacon** [comment] 2015-09-30 17:55
Okay, after much further investigation, I offer you the following.
```
if (container.parentNode !== map.div) {
    if (!cache.rendered) {
        var me = this;
        google.maps.event.addListenerOnce(this.mapObject, 'tilesloaded', function() {
            cache.rendered = true;
            me.setGMapVisibility(me.getVisibility());
            me.moveTo(me.map.getCenter());
            cache.googleControl.appendChild(map.viewPortDiv);
        });
        map.div.appendChild(container);
        google.maps.event.trigger(this.mapObject, 'resize');
    }
}
```
With the previous patch `cache.googleControl.appendChild(map.viewPortDiv);` was executed as soon as setGMapVisibility() was called which removed the OL viewPortDiv from the DOM until a callback to the GMaps script occurred. That meant that operations like resizing a vector layer failed quietly if they were executed before the GMaps callback. Moving the line in to the OL tilesloaded callback ensures the OL viewPortDiv is always in the DOM.

The minified version is

if(!b.rendered){var h=this;google.maps.event.addListenerOnce(this.mapObject,"tilesloaded",function(){b.rendered=!0;h.setGMapVisibility(h.getVisibility());h.moveTo(h.map.getCenter());b.googleControl.appendChild(c.viewPortDiv)})c.div.appendChild(e),google.maps.event.trigger(this.mapObject,"resize");}this.mapObject.setMapTypeId(d)}else


The other two lines still trigger the resize event when setGMapVisibility() is first called, as required for compatibility with Google Maps API > v20.

**Comment by JimBacon** [comment] 2015-10-07 14:15
Cancel the above. This fails when layers are made invisible and then visible again, as when switching layers. When the layer is made invisible the container is removed from the DOM and the OL viewPortDiv is moved. We have to make sure these are put back when the layer is made visible again. My new version is as follows:
```
if (container.parentNode !== map.div) {
    if (!cache.rendered) {
        var me = this;
        google.maps.event.addListenerOnce(this.mapObject, 'tilesloaded', function() {
            cache.rendered = true;
            me.setGMapVisibility(me.getVisibility());
            me.moveTo(me.map.getCenter());
            cache.googleControl.appendChild(map.viewPortDiv);
        });
    } else {
        cache.googleControl.appendChild(map.viewPortDiv);
    }
    map.div.appendChild(container);
    google.maps.event.trigger(this.mapObject, 'resize');
}
```
The minified version is 

if(!b.rendered){var h=this;google.maps.event.addListenerOnce(this.mapObject,"tilesloaded",function(){b.rendered=!0;h.setGMapVisibility(h.getVisibility());h.moveTo(h.map.getCenter());b.googleControl.appendChild(c.viewPortDiv)})}else{b.googleControl.appendChild(c.viewPortDiv)}c.div.appendChild(e),google.maps.event.trigger(this.mapObject,"resize");}
this.mapObject.setMapTypeId(d)}else

**Comment by vitalidze** [comment] 2015-11-18 05:51
According to [this thread](https://groups.google.com/forum/#!topic/google-maps-js-api-v3-notify/prpOYuTs6jk) yesterday they have removed support for 3.20. So, what will be the option to make OpenLayers 2.x working with the latest version of Google Maps API? Incorporate the fix from @JimBacon and load the custom version of OpenLayers?

**Comment by nsuprin** [comment] 2015-11-18 11:10
Thx it works fine for me.

**Comment by mattdiamond** [comment] 2015-11-18 23:40
I used @JimBacon's [latest solution](https://github.com/openlayers/openlayers/issues/1450#issuecomment-146207698) after Google Maps deprecated v3.20, and while the fix works on my local dev environment, it seems to malfunction on our staging environment. The effect is that the map tiles appear *below* the map until one zooms in/out, switches layers, etc. at which point it fixes itself. It's like the map tiles are being inserted after the map rather than within the map, if that makes sense.

I'm a bit confused why this would happen... the only difference between local and staging would be the minification process, I think. The data we use to populate the map is different too, so perhaps it's a race condition? @JimBacon, do you have any updates to your fix?

**Comment by Leogali** [comment] 2015-11-19 03:19
Same here, I also used @JimBacon's latest solution and it works as long as I use it in my local environment, but failes when used in web. Similar effects @mattdiamond reported and finally works after zoom in/out.
Left pictures is before and the right picture after zoom/in out:
![before_after](https://cloud.githubusercontent.com/assets/4803504/11261371/3b4f97ee-8e74-11e5-9649-ea5a81582352.png)

**Comment by vitalidze** [comment] 2015-11-19 07:37
FYI, I have finally replaced @JimBacon's solution with the one from @szekerest.  It works like a charm. 

@JimBacon's one was always loading the Google Maps layer below all others so even if current map layer was selected to OSM there were still a google maps somewhere. Don't know what's wrong here, but @szekerest's solution does not produce such glitches. I highly recommend it. [Here is](https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/js/openlayers/OpenLayers.js) the minified version.

**Comment by Leogali** [comment] 2015-11-19 09:32
@vitalidze yes you are right @szekerest did the job already very well. Maybe @JimBacon  mixed something up while merged the lines together. Anyway here is the working V3.js based on @szekerest solution.

**Comment by JimBacon** [comment] 2015-11-19 10:44
What I found when I was looking in to this was that there is an OpenLayers viewPortDiv, in which features get drawn, that gets moved around and ends up within the Google Maps Div.

My problem with the solution by @szekerest was that  the OL viewPortDiv was removed from the DOM until after the callback on GMaps tilesloaded. That meant that operations like resizing a vector layer failed quietly if they were executed before the GMaps callback. In simpler applications this will not be a problem.

My solution keeps the viewPortDiv in the DOM and moves it within the GMaps Div on the tilesloaded callback. If you are seeing the maps stacked as you are then this move is not happening.

If your development systems work and use the unminified version but your staging servers fail using the minified version then I'd say it is almost guaranteed that there is a mistake in creating the minified version. If this is the scenario, switching the files around would prove if this is the case.

**Comment by geofranzi** [comment] 2015-11-20 18:00
Google Layer work fine now (OpenLayers 2.13), but there is a side effect if you switch to e.g. an OSM Layer the Feature Layer no longer zoom together with the base map.

**Comment by grom358** [comment] 2015-11-30 00:13
@szekerest does not work with marker clustering:

![](https://www.dropbox.com/s/x24zendtz4tisyj/Screenshot%202015-11-30%2010.10.51.png?dl=1)

**Comment by grom358** [comment] 2015-11-30 01:38
Here is patch file https://gist.github.com/grom358/8412bbadde7e6d781ae8 using his ![latest's solution](https://github.com/openlayers/openlayers/issues/1450#issuecomment-146207698)

**Comment by JPustkuchen** [comment] 2015-11-30 09:13
The patch from #1450 solved the issue for us. Please commit it to the next stable v2 release.

**Comment by ahocevar** [comment] 2015-11-30 09:17
@JPustkuchen Please create a pull request so we can merge it into master. It is unlikely that there will be another release of OpenLayers 2, but you can always use master which is considered stable.

**Comment by JPustkuchen** [comment] 2015-11-30 09:18
@ahocevar: Sorry and a bit embarrassing but I have not created a pull request yet. I'll have to read the documentation about it. Could you perhaps help me or do it for this case? I don't want to make a mistake, this is too important, I think. Sorry and thank you very much!

**Comment by ahocevar** [comment] 2015-11-30 09:19
@asaunier Maybe you want to create a pull request?

**Comment by vitalidze** [comment] 2015-11-30 09:26
@ahocevar excuse me, but why can't you make a release of OpenLayers 2?. I believe this particular issue is a good reason for a minor (or hot fix) release (Say 2.13.2). Is there any good reason for not releasing 2.x version?

**Comment by ahocevar** [comment] 2015-11-30 09:27
This problem is not caused by an OpenLayers bug, it is caused by an api change in a 3rd party library.

**Comment by bartvde** [comment] 2015-11-30 09:29
If you're interested in sponsoring a release let us know.

**Comment by vitalidze** [comment] 2015-11-30 09:43
@ahocevar this is a compatibility issue with the google maps API. If the library says it supports the google maps, then it's an issue with the library if it does not work anymore. This is my opinion.

So if this and money as @bartvde says are the reasons for not releasing new version there is nothing to do here.

I will stick with the patched version. Anyway, thank you for your work on this project.

**Closed** 2015-12-08 12:09 UTC

**Comment by somayehzahra** [comment] 2015-12-16 10:31
Hi
I have a problem such that discussed above. but unfortunately i don't understand what can do exactly. 
my program is here. it was working one month ago well but not now. 
-----------------------------------------
<html>
<head>
    <title>OpenLayers Example</title>
    <script src="http://openlayers.org/api/OpenLayers.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
</head>
<body>
    <div id="map"></div>
    <meta charset="utf-8">
    <script type="text/javascript">
	var map = new OpenLayers.Map ("map");
		var wms = new OpenLayers.Layer.Google("Google Streets",{ numZoomLevels: 20 });
		var markers = new OpenLayers.Layer.Markers( "Markers" );
		 var lon =  24.428481;
            var lat = 40.725627;
            var lonlat = new OpenLayers.LonLat(lon, lat).transform(
                new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                new OpenLayers.Projection("EPSG:900913") // to Spherical Mercator
              );
      var zoom = 18;
      var newlonlat = new OpenLayers.LonLat(lon, lat).transform(new      OpenLayers.Projection("EPSG:4326"), map.getProjectionObject());
	    var marker = new OpenLayers.Marker(newlonlat);
	    markers.addMarker(marker);
	    map.addLayer(markers);
            map.addLayer(wms);
	    map.zoomToMaxExtent();
            map.setCenter(lonlat, zoom);
    </script>
</body>
</html>

--------------------------------

please help !!!!!

**Comment by marcjansen** [comment] 2015-12-16 11:43
The changes mentioned e.g. by @ahocevar should be in master. Can you use ol2 from master or do you need a singlefile build?

**Comment by LeandroLong** [comment] 2016-01-03 18:39
@vitalidze thx! Yes you are right @szekerest did the job already very well. Maybe @JimBacon mixed something up while he merged the lines together. Anyway here is the working V3.js (txt) based on @szekerest solution.
v3.txt

It's work!!!!!!

**Comment by trailway** [comment] 2016-02-25 16:01
bvartde stated "If you're interested in sponsoring a release let us know."

What does it cost to sponsor a release of Open Layers 2?

**Comment by bartvde** [comment] 2016-02-25 16:59
@trailway please fill in the form with your query here: http://boundlessgeo.com/about/contact-us/ TIA

**Comment by trailway** [comment] 2016-02-26 12:12
I contacted Boundless and received a very polite response which essentially said that their focus is on Open Layers 3, i.e. no interest in Open Layers 2.  FWIW, I am "stuck" on Open Layers 2 because I build on top of an open source stack in which Open Layers is a component.

**Comment by bartvde** [comment] 2016-02-26 12:38
@trailway can you contact met at bartvde [at] osgis [dot] nl ?

**Comment by marcjansen** [comment] 2016-02-26 12:40
I can check if we have resources for this the upcoming week. I'll report back here.

**Comment by mohamad723** [comment] 2016-02-27 01:46
Hi every body
i want to know what the reason of invention OpenLayers...What are the problems facing applications before it (openlayers) ... because i have to write a paper about OpenLayers and reason of invention..
any help please.... any file you device me to read ..and thank you in advance

**Comment by mohamad723** [comment] 2016-02-27 23:24
:(

**Comment by grandao0** [comment] 2016-02-29 15:49
thanks a lot @JimBacon I used your fix and it solved my problem just right!

I had to thank you cause I spent my entire morning on this =D
