### ISSUE TITLE
pixelRatio sizing broken for Canvas Immediate Icon rendering

### ISSUE THREAD

**Issue by richard-thomas** [openlayers/openlayers#12574] opened 2021-07-30 17:48 UTC
In moving from OpenLayers 6.5.0 to 6.6.1, the sizing of Icons has been broken when using Canvas Immediate rendering - as pixelRatio increases, the icons are now drawn progressively smaller. The code below demonstrates (for example when viewed in Chrome Inspector emulation of high DPI device) the problem by displaying an icon on a map and also displaying it using canvas immediate rendering. If you revert the version of OpenLayers loaded in the code to 6.5.0 you will see the icons in both return to the same size.

```
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css"
      href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css">
    <style>
      #immediate canvas {
        border: solid 1px grey;
      }
      .map {
        border: solid 1px grey;
        height: 400px;
        width: 100%;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/build/ol.js">
    </script>
  </head>
  <body>
    <h4>Map rendering:</h4>
    <div id="map" class="map"></div>
    <h4>CanvasImmediate rendering:</h4>
    <div id="immediate">
      <canvas id="testCanvas">
    </div>
    <script type="text/javascript">

      var iconStyle = new ol.style.Style({
        image: new ol.style.Icon({
          src: 'https://openlayers.org/en/latest/examples/data/icon.png'
        }),
      });

      // Map rendering
      var wkt = 'POINT(10.689 -25.092)';
      var format = new ol.format.WKT();
      var feature = format.readFeature(wkt, {
        dataProjection: 'EPSG:4326',
        featureProjection: 'EPSG:3857',
      });
      var vector = new ol.layer.Vector({
        source: new ol.source.Vector({
          features: [feature],
        }),
        style: iconStyle
      });
      var raster = new ol.layer.Tile({
        source: new ol.source.OSM(),
      });
      var map = new ol.Map({
        layers: [raster, vector],
        target: 'map',
        view: new ol.View({
          center: [2952104.0199, -3277504.823],
          zoom: 4,
        }),
      });

      // CanvasImmediate rendering
      var testCanvas = document.getElementById('testCanvas');
      var ctx = testCanvas.getContext('2d');
      var pointGeom = new ol.geom.Point([250, 125]);
      var vectorContext = ol.render.toContext(ctx, {
        size: [500, 250],
        pixelRatio: ol.has.DEVICE_PIXEL_RATIO
      });

      // Draw icon after short delay to allow image to load
      setTimeout(function() {
        vectorContext.setStyle(iconStyle);
        vectorContext.drawGeometry(pointGeom);
      }, 500);

    </script>
  </body>
</html>
```

**Comment by MoonE** [comment] 2021-07-30 22:02
Thanks for the report, there is indeed something wrong.

As a workaround you can add `color: 'white'` to the  icon image.

**Comment by richard-thomas** [comment] 2021-07-30 23:43
@MoonE - Thanks for the quick response - that fix does work in my other code as well. Unfortunately, the ol.style.Icon is defined in a third party module I am using so although hacking that works, it isn't a viable workaround. Is there a way to modify the style after it is created which will have the same effect? I tried the following hack in my code to mimic the effect I saw from hacking the third party Icon command, but it doesn't work:
```
styleRule.getImage().color_ = [255, 255, 255, 1];
```

**Comment by kjellmf** [comment] 2021-08-15 15:42
I ran into the same issue while experimenting with ol-ext feature animations (https://viglino.github.io/ol-ext/doc/doc-pages/ol.featureAnimation.html) and SVG icons. Setting `color: 'white'` works, but unfortunately the text in the SVG becomes hard to read after the animation is finished: 

![image](https://user-images.githubusercontent.com/29217/129484103-c91973ad-212b-4eb4-b59f-e7f465075aa1.png)

**Comment by richard-thomas** [comment] 2021-12-31 18:32
I was hoping this might be fixed in 6.10.0, but alas no. @MoonE - any suggestions on possible workarounds that can be applied after the icon is created (by a third party library)? And/or if you could point me at the bit of code where it is failing (and why you think your workaround works), I could try having a look at the OL code. Thanks!

**Comment by sorrowe** [comment] 2022-04-13 17:25
Just as a warning to any future travellers (since it caused me a lot of confusion):

This workaround (and potentially any images that use the 'color' option) doesn't update correctly if the base image is changed after it's used to make an instance on ol.style.Icon. e.g. because a canvas element was passed. Further more, it stays broken if you use that same base image in another Icon, due to the caching of IconImage instances.

In my case the workflow was

1. Generate canvas with placeholder image while waiting for additional information to load
2. Generate an Icon with the placeholder. This is rendered to canvas.

Because the image itself is wrapped in an instance of IconImage, but those are cached based on the Image

**Comment by richard-thomas** [comment] 2023-04-01 18:44
This issue appears to have been fixed in the transition from OL6 to OL7. Modifying the example I gave above to the last OL6 version 6.15.1 with the following still displays the bug:
`      href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/css/ol.css">
      src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js">
`
However, switching to the earliest version of & I could find on CDN (7.1.0) it works as expected giving a high resolution image on high DPR devices of the correct size:
`      href="https://cdn.jsdelivr.net/npm/ol@7.1.0/ol.css">
      src="https://cdn.jsdelivr.net/npm/ol@7.1.0/dist/ol.js">
`
As indeed it does on the latest version (currently 7.3.0):
`      href="https://cdn.jsdelivr.net/npm/ol@latest/ol.css">
      src="https://cdn.jsdelivr.net/npm/ol@latest/dist/ol.js">
`
So I'm happy for this to be closed - unless anyone else still had issues?

**Comment by ger-benjamin** [comment] 2023-04-26 07:57
I've tested, and I can confirm it's not present anymore in the version 7. The issue was in `src/ol/render/canvas/Immediate.js`, method `setImageStyle`.
This bug also affected `getVectorContext` (from `ol/render.js`) but is now fixed.

This issue can be closed, but still valid for some v6.

**Closed** 2023-05-08 19:46 UTC
Labels: bug
