### ISSUE TITLE
why multiple select interaction does not work?

### ISSUE THREAD

**Issue by boliwe** [openlayers/openlayers#9945] opened 2019-09-19 19:06 UTC
I have multiple layers in my openlayers application. So I need layer based specific select interaction. Each layer will have its own select interaction. This is my problem. I do not want to add layers in one select interaction, because it is not my solution.

[Working application is here.](https://jsfiddle.net/veung7hc/)

**Comment by TieSKey** [comment] 2019-09-20 22:30
Seems to be a design bug old enough to be on elementary school. It gets ignored every time and that stupid bot closes it...
(To the maintainers: Sorry but I don't see how closing issues with a lot of comments and no associated fixes is a good idea.)

[https://github.com/openlayers/openlayers/issues/1988](url)
[https://github.com/openlayers/openlayers/issues/4882](url)
Basically, singleClick (and maybe others) event type won't propagate.

A work around was posted here:
[https://github.com/openlayers/openlayers/issues/1988#issuecomment-531779151](url)

**Comment by jahow** [comment] 2019-09-23 09:41
Hi and thanks for your report, we are aware that the select interaction has issues especially when looking for specific behaviour depending on the selected layer.

Have you tried using the [`map.forEachFeatureAtPixel`](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#forEachFeatureAtPixel) method? That might be easier to work with for your use case.

**Comment by simonseyock** [comment] 2019-09-27 09:35
This problem should be solved with the new openlayers 6 release as the Select Interaction does not use an umanaged layer anymore.

**Comment by TieSKey** [comment] 2019-10-22 16:15
This problem is not solved with latest version 6.0.1
https://jsfiddle.net/m96hbgjL/ (same as above but with updated OL version)

**Comment by ahocevar** [comment] 2019-10-22 17:35
I think the problem is the return value of `ol/interaction/Select#handleEvent`. In my opinion, it should always return `true`.

**Comment by TieSKey** [comment] 2019-10-22 17:39
That's the workaround I'm using as proposed here:
https://github.com/openlayers/openlayers/issues/1988#issuecomment-531779151

which basically just forces the event handler to return true.

**Comment by ahocevar** [comment] 2019-10-22 17:43
@TieSKey Would you be willing to create a pull request with a change along these lines?

**Closed** 2019-10-27 21:58 UTC
Labels: pull request accepted
