### ISSUE TITLE
Can't resolve @types/ol/Map on prod building

### ISSUE THREAD

**Issue by TooPick** [openlayers/openlayers#10401] opened 2019-12-10 08:56 UTC
Hello,

I've got en error when i'm trying to build my project in prod.
I've got the following error in my console :
`Module not found: Error: Can't resolve '@types/ol/Map'`

Here is an example of a file where the error is triggered : 
```
import { Injectable } from '@angular/core';
import { UtilsService } from './utils.service';
import { WebSocketAPI } from '../websockets/websocket.api';
import { Map } from 'ol';

@Injectable({
  providedIn: 'root'
})
export class MapOverlayService {

  private utils: UtilsService;

  constructor(
    _webSocketAPI: WebSocketAPI,
    map: Map
  ) {
    this.utils = new UtilsService(map);
  }

  remove(raw_data: any) {
    var data = JSON.parse(raw_data.body);

    this.utils.deleteLayer(data.overlayId);
  }
}

```

Thank you for your help !

**Comment by jahow** [comment] 2019-12-12 13:37
The `@types/ol` package is currently not maintained by the OpenLayers organization, it is hosted here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ol

As for your error, it looks like either the package is missing, or your angular project configuration is off (as in, angular expect type definitions for `ol` but can't find any). I'll close this issue as it is clearly not a bug in the OpenLayers library.

**Closed by jahow** 2019-12-12 13:37 UTC
