### ISSUE TITLE
vectorLayer.getFeatures will create canvas on clicking th map each time the map view changed

### ISSUE THREAD

**Issue by suncl1989** [openlayers/openlayers#11033] opened 2020-05-11 11:04 UTC
I'm not sure whether it is a bug

**Describe the bug**
v6.3.1
vector.getFeatures(evt.pixel) will create an empty canvas each time the map view changed

in v6.1.0 it works well

**To Reproduce**

[https://codesandbox.io/s/draw-and-modify-features-p1stq?file=/index.js
](https://codesandbox.io/s/draw-and-modify-features-p1stq?file=/index.js
)
1. init map
2. bind click event
3. click the map

![image](https://user-images.githubusercontent.com/22719650/81554230-00361a80-93b9-11ea-864f-9ebf531984ed.png)

**if interaction is add, colorful squares in each canvas**  
![image](https://user-images.githubusercontent.com/22719650/81554849-198b9680-93ba-11ea-9f67-5e610deb5544.png)

**Comment by ahocevar** [comment] 2020-05-11 15:42
Duplicate of #11009.

**Closed by ahocevar** 2020-05-11 15:42 UTC
