### ISSUE TITLE
Selecting a feature on a VectorTile creates snapshot on page bottom

### ISSUE THREAD

**Issue by euberzouki** [openlayers/openlayers#11232] opened 2020-07-02 15:55 UTC
**Describe the bug**
When you select a feature or multiple features from a VectorTile Layer a snapshot of the map is created at the bottom of the HTML page.

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/vector-tile-selection.html'
2. Click on any feature on the map
3. See the snapshots being added to the bottom of the page at every click, and `<canvas>` being added to HTML

**Expected behavior**
Nothing should appear on the page after a selection

![image](https://user-images.githubusercontent.com/47486658/86380904-f334f980-bc8c-11ea-9025-6ea132ecc461.png)

**Comment by mike-000** [comment] 2020-07-02 17:11
Duplicate of #11128

**Closed** 2020-07-07 21:40 UTC
