### ISSUE TITLE
Wrong scale value in cloned icons

### ISSUE THREAD

**Issue by M-Bitt** [openlayers/openlayers#14575] opened 2023-03-16 06:59 UTC
**Description**
When an Icons' scale is set as a number and you clone it, the scale of the clone got an array with different values as his scale.
This happens because by calling setScale() an Icon receives an height and width. So by calling the constructor within clone() the scale is set to an array though it was set a number before. This results always in a wrong value for the scale value.
Even the documentation states that height and width can't be used with scale. This seems to be a conflict.

**Steps To Reproduce**
1. Create an Feature with an Icon without height and width
2. Scale the icon with a number Value
3. Clone the icon
4. You will see there is an array as scale value in the cloned style

**Expected behavior**
The cloned icon keeps the same scale as its original especially the same datatype.

**Comment by mike-000** [comment] 2023-03-16 11:34
Which version are you using?  I cannot reproduce that in version 7.3.0.  It should have been fixed by #14457.

**Comment by mike-000** [comment] 2023-03-16 13:22
The documentation for `setScale()` says `Set the scale and updates the width and height correspondingly.`  However the only update which would make sense would be to clear any width or height already set, in which case `setWidth()` and `setHeight()` should be available as API methods to reset them.  The alternative would be to throw the same assertion as the constructor if conflicting settings are attempted.

**Comment by M-Bitt** [comment] 2023-03-20 10:43
Yes, this would be better. If `setScale()` sets width and height it can't be used afterwards anymore.

**Comment by ahocevar** [comment] 2023-03-25 10:42
@M-Bitt Nonetheless, he cloned icon should result in the same visual result, doesn't it?

**Comment by ahocevar** [comment] 2023-03-25 11:06
@mike-000 

> The alternative would be to throw the same assertion as the constructor if conflicting settings are attempted.

This would be one way to solve the underlying problem, but I think removing `setWidth()` and `setHeight()` altogether would save us headache in the future.

**Comment by M-Bitt** [comment] 2023-03-27 07:12
@ahocevar Yes, of course the cloned icon should be the same. But when the clone gets basically a Scale of 1 it is not the same as the original and still has to be set manually after cloning, right? Why not setting the scale of the original icon?

**Comment by ahocevar** [comment] 2023-03-27 08:29
@M-Bitt This problem with the scale of 1 will be fixed by #14606.

**Closed** 2023-03-29 13:56 UTC
Labels: bug
