### ISSUE TITLE
We need to display a trail that shows the travelled path of the drone. This can be a thin perforated line drawn between every position update. This will help users identify the path that drone has taken so far in the video.

### ISSUE THREAD

**Issue by pranjalbansal787** [openlayers/openlayers#14779] opened 2023-05-24 18:23 UTC
We need to display a trail that shows the travelled path of the drone. This can be a thin perforated line drawn between every position update. This will help users identify the path that drone has taken so far in the video.

**The solution i want is : **
I want to create the path which displays the travel path of the drone.This path can be displayed with the help of thin perforated red line  Currently I have implemented some code but the code seems to give some errors . Please help me out to implement this feature as soon as possible .

Here's some implementation that I have done but it seems to give some errors 
import React, { useState, useEffect, useRef } from 'react';
import PropTypes from 'prop-types';
import { hasEmptyValue, ToggleSwitch, Text } from 'lib';

import '../../stylesheets/components/Video/VideoMap.scss';
import { Style, Stroke } from 'ol/style';
import { Vector as VectorLayer } from 'ol/layer';
import { Vector as VectorSource } from 'ol/source';
import { LineString } from 'ol/geom';
import Feature from 'ol/Feature';
import { dronetelemetry, location } from '../../assets/icons';

import Map from '../common/Map';
import FullScreenControl from '../common/Map/FullscreenControl';
import ZoomControls from '../common/Map/ZoomControls';
import BasemapControl from '../common/Map/BasemapControl';
import MarkersList from '../common/Map/MarkersList';

import coordinatesToPointFeature from '../../utils/map/coordinatesToPointFeature';

const VideoMap = ({ site, telemetry, isPaused }) => {
    const [marker, setMarker] = useState(null);
    const [isAutofocus, toggleAutofocus] = useState(false);
    const ref = useRef(0);
    const [pathLayer, setPathLayer] = useState(null);

    useEffect(() => {
        let interval;
        if (hasEmptyValue(telemetry)) {
            if (!hasEmptyValue(site)) {
                setMarker({
                    siteType: site.siteType,
                    name: site.name,
                    uuid: site.uuid,
                    geojson: !hasEmptyValue(site.demarcationGeojson)
                        ? site.demarcationGeojson
                        : coordinatesToPointFeature(site.locCoordinates),
                });
            }
        } else if (!isPaused) {
            interval = setInterval(() => {
                const geojson = coordinatesToPointFeature(telemetry[ref.current]);
                setMarker({
                    siteType: site.siteType,
                    name: site.name,
                    uuid: site.uuid,
                    geojson,
                });
                // should be removed once we get an actual file
                ref.current = ref.current === telemetry.length - 1 ? 0 : ref.current + 1;
            }, 300);
        }
        return () => clearInterval(interval);
    }, [telemetry, site, isPaused]);

    useEffect(() => {
        const pathLayer = createPathLayer();
        setPathLayer(pathLayer);
        return () => {
            if (pathLayer) {
                pathLayer.setMap(null);
            }
        };
    }, []);

    const createPathLayer = () => {
        const lineStyle = new Style({
            stroke: new Stroke({
                color: 'red',
                width: 2,
                lineDash: [5, 5],
            }),
        });
        const pathSource = new VectorSource();

        const pathLayer = new VectorLayer({
            source: pathSource,
            style: lineStyle,
        });

        return pathLayer;
    };

    const updatePathLayer = (coordinates) => {
        if (pathLayer) {
            const feature = new Feature({
                geometry: new LineString(coordinates),
            });
            pathLayer.getSource().clear();
            pathLayer.getSource().addFeature(feature);
        }
    };
    updatePathLayer();

    if (!hasEmptyValue(site) && !hasEmptyValue(marker)) {
        return (
            <div className="VideoMap">
                <Map>
                    <FullScreenControl />
                    <div>
                        <ToggleSwitch
                            name="setAutofocus"
                            checked={isAutofocus}
                            onChange={() => toggleAutofocus(!isAutofocus)}
                        />
                        <Text text="Enable/Disable Refocus on Map" />
                    </div>
                    <ZoomControls />
                    <BasemapControl />
                    <MarkersList
                        markers={[marker]}
                        textKey="siteType"
                        iconUrl={!hasEmptyValue(telemetry) ? dronetelemetry : location}
                        hoverIconUrl={!hasEmptyValue(telemetry) ? dronetelemetry : location}
                        onClick={() => { }}
                        autofocus={isAutofocus}
                    />
                </Map>
            </div>
        );
    }
    return null;
};

VideoMap.propTypes = {
    site: PropTypes.shape({
        uuid: PropTypes.string,
        name: PropTypes.string,
        siteType: PropTypes.string,
        demarcationGeojson: PropTypes.object,
        locCoordinates: PropTypes.shape({
            lat: PropTypes.number,
            lng: PropTypes.number,
        }),
    }).isRequired,
    telemetry: PropTypes.arrayOf(PropTypes.shape({
        lat: PropTypes.string,
        lng: PropTypes.string,
    })),
    isPaused: PropTypes.bool,
};

VideoMap.defaultProps = {
    telemetry: [],
    isPaused: true,
};

export default VideoMap;

The errors  I am getting are : 
Line 57:15:  'pathLayer' is already declared in the upper scope on line 25 column 12 
  Line 57:27:  'createPathLayer' was used before it was defined                        
  Line 76:15:  'pathLayer' is already declared in the upper scope on line 25 column 12
Please help me out resolve this error as soon as possible .

**Comment by ahocevar** [comment] 2023-05-24 19:10
Duplicate of #14735

**Closed by ahocevar** 2023-05-24 19:10 UTC
Labels: feature request
