### ISSUE TITLE
WMS not cached when Reprojected

### ISSUE THREAD

**Issue by flipper44** [openlayers/openlayers#9613] opened 2019-05-28 17:14 UTC
I took the animated WMSTile example, and set it up to use WMSImage instead.
and changed my Main maps coordinate system away from Spherical Mercator.
What I discovered was that the WMSImage Source would not use the already cached image when the WMS weather layer restarted its timed loop, instead it reloaded it. This does not happen when it is not reprojected.
I tried to tweak the setImageLoadFunction thinking I could bypass but no luck.
I tested on Version 4.6.5 haven't had a chance to test on newer version, perhaps this was already fixed but could not find it in a change log.

**Comment by ahocevar** [comment] 2019-05-29 11:09
You are right, we only cache tiles. Not images with arbitrary extent. Any reason for not using a tiled source?

**Comment by flipper44** [comment] 2019-05-29 13:15
I had the same problem with reprojected tiles. I liked the animation better with full frame. It's strange that they both will not request a second copy unless reprojected and that the browser doesn't accept them as cached either since not one character is changed, I couldn't see a cache expire tag in the image.
Is there something I can do in the setimageloadfunction?

**Comment by ahocevar** [comment] 2019-05-29 15:25
Maybe you should provide a live example that shows the issue. I could not think of anything that would cause different behavior when raster reprojection is on, other than different tiles (TileWMS) or extents (ImageWMS) are fetched.

**Comment by flipper44** [comment] 2019-05-29 19:26
Here is my first jsfiddle [https://jsfiddle.net/8qf6Lnm2/1/](https://jsfiddle.net/8qf6Lnm2/1/)
if you F12 to developer mode in chrome (make sure disable cache is not turned on), when you play this in the Original Indiana CS, it will  request the same WMS over and Over again as it cycles, if I set the View Projection to Spherical Mercator, it will cycle through the animation once, and then stop requesting the Cached WMS images after the 12-14th request as desired.
If you search for requests based on the timestamp for a given time, they have the exact same values, so I am surprised the browser doesn't see them as cached at least.

If you change the frameRate to 2 or 3 it can't keep up because it can't use cache and the image requests pile up

**Comment by mike-000** [comment] 2019-05-30 17:54
It's because the server doesn't return a cache-control header.  Swiss Topo WMS does and when EPSG:3857 is reprojected to EPSG:21781 with a dummy parameter alternating true/false on a 5 seconds each cycle it is cached by the browser after the first cycle https://jsfiddle.net/kvf3gosd/

**Comment by flipper44** [comment] 2019-05-30 18:04
@mike-000 
So when re-projected it relies on cache-control headers and when not projected it doesn't?
So I would need to use my own proxy that returns a cache control header if I want this to work I imagine, or is their away to amend one somehow?

**Comment by flipper44** [comment] 2019-05-30 21:34
@mike-000 
I am wondering, you are using EPSG:21781 as your projection, and Technically as far as I understand proj4js shouldn't know anything about this projection, I don't see any WKT or anything that is applied to your system other than extents. So i am not sure how this would be doing any form of re-projection.

**Comment by mike-000** [comment] 2019-05-30 21:43
It's included via https://epsg.io/21781-1753.js  Also if you comment out `projection `in the view you will see the difference between zoom 2 in EPSG:21781 and EPSG:3857.

**Comment by flipper44** [comment] 2019-05-30 23:00
@mike-000 
I saw that Line After I already posted and took the post down...Not my favorite work-aroiund but I built a proxy that changed the headers

**Comment by mike-000** [comment] 2019-05-31 09:05
What you are seeing without reprojection can be reproduced in standalone javascript

```
setInterval(function(){
  var img = new Image();
  img.src = url;
  img.onload = function(){ console.log('loaded'); img = null; };
}, 5000);
```

When the loaded url is in memory (even if the object is no longer assigned to a variable and available for garbage collection) the browser only shows two network loads (which depending on the url may be real or cached) despite being logged many times in the console.

But simulate reprojection by adding some processing to trigger garbage collection and every load will appear as network activity

```
setInterval(function(){
  var canvas = document.createElement("canvas");
  canvas.width = 1000;
  canvas.height = 1000;
  var ctx = canvas.getContext("2d");
  ctx.fillStyle = 'black';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  var data = canvas.toDataURL();
}, 1);
```

**Comment by ahocevar** [comment] 2019-05-31 12:21
Closing this. Not an OpenLayers issue.

**Closed by ahocevar** 2019-05-31 12:21 UTC
