### ISSUE TITLE
Hi, I'm using openlayers in my website and all of sudden it stopped working. When I check the console I see the following error "GET https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js net::ERR_ABORTED 403 OpenLayers working example.html:28 Uncaught ReferenceError: ol is not defined     at OpenLayers working example.html:28 (anonymous) @ OpenLayers working example.html:28"

### ISSUE THREAD

**Issue by sanathkatakam** [openlayers/openlayers#12047] opened 2021-02-18 13:11 UTC
Hi, I'm using openlayers in my website and all of sudden it stopped working. 

When I check the console I see the following error 

"GET https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js net::ERR_ABORTED 403 OpenLayers working example.html:28 Uncaught ReferenceError: ol is not defined at OpenLayers working example.html:28 (anonymous) @ OpenLayers working example.html:28"
![image](https://user-images.githubusercontent.com/45826815/108362305-938a5f00-7219-11eb-8eba-902a33ae03b8.png)

**Comment by M393** [comment] 2021-02-18 13:18
This seems to be a duplicate of #12045.

**Comment by ahocevar** [comment] 2021-02-18 13:22
Indeed a duplicate of #12045. Closing.

**Closed by ahocevar** 2021-02-18 13:22 UTC
