### ISSUE TITLE
Labels are incorrectly positioned when setting textAlign: Left in OL6

### ISSUE THREAD

**Issue by AcerLaurinum** [openlayers/openlayers#10242] opened 2019-11-01 18:12 UTC
**Describe the bug**
If you set textAlign:left on a text label in OL6 the labels are now shifted noticeably to the right. I can reproduce this issue on iOS with Google Chrome and Ubuntu with Google Chrome. It doesn't seem to happen on Android with Google Chrome

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/vector-labels.html and set Align to "Left" for points and click Refresh. 
2. Then go to https://openlayers.org/en/v5.3.0/examples/vector-labels.html and set Align to "Left" for points and click Refresh. 
3. The label position is shifted way to the right in OpenLayers 6.1.0 unlike in 5.3.0.

**Expected behavior**
The labels should be positioned in the same place in OL6 and not be shifted to the right.

**Comment by greeeg** [comment] 2019-11-01 18:38
I'm experiencing the same issue using OpenLayers `6.1.0`. Here is an example showing text labels positioned incorrectly compared to their anchor/position.

https://github.com/greeeg/open-layers-6-measurement-issue

This issue seems to be linked to the way OpenLayers measures texts using the [`measureText()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) method when the map is updated:
- when we refresh it in the examples as @AcerLaurinum was mentioning
- when moving to a different part of the map previously not shown

## To reproduce
![Screen Shot 2019-11-01 at 2 36 17 PM](https://user-images.githubusercontent.com/12447517/68047523-fc606780-fcb4-11e9-84c1-3312094e82d0.png)

When the map is first initialized, only some labels (Canal St, Houston St, etc) are visible. If you move the map to see Upper Manhattan, some labels are misaligned.

**Comment by robertpenner** [comment] 2019-11-01 18:47
I work with @greeeg; we're very excited to upgrade our project to OpenLayers v6 for the performance improvements, but this text align bug is blocking us. (We were about to file this issue but @AcerLaurinum beat us by 20 minutes.)

We found that OpenLayers' call to `CanvasRenderingContext2D.measureText()` is sometimes getting a text width of about 2.05x the normal one. Reproducing it consistently was challenging for a while, but we found that text features that are initially not in the viewport but render offscreen and pan into view, those have the buggy width.

**Comment by robertpenner** [comment] 2019-11-01 18:49
@AcerLaurinum This bug actually affects all alignments except for `'center'`.

**Comment by ahocevar** [comment] 2019-11-01 19:59
According to `git biset`, 5616c535b0f17c5773e6426c322693887c6cc698 is the first bad commit
```
commit 5616c535b0f17c5773e6426c322693887c6cc698
Author: ahocevar <andreas.hocevar@gmail.com>
Date:   Thu Jul 4 16:10:28 2019 +0200

    Clean up properly when clearing label cache
```

**Comment by greeeg** [comment] 2019-11-01 20:54
@ahocevar Looks like this commit was an attempt to improve text rendering by limiting access to context object but it's causing a regression issue on the labels. Should we consider reverting this update to fix label positioning? (supposing that it's the real cause of this issue)

**Comment by ahocevar** [comment] 2019-11-01 21:07
#10243 fixes this regression.

**Comment by robertpenner** [comment] 2019-11-05 16:46
@ahocevar Although #10243 fixed the example @AcerLaurinum cited, the alignment problem still occurs in our case. I put @greeeg's example into a CodeSandbox reproducing it:

https://codesandbox.io/s/openlayers-611-measurement-issue-wnfev

**Comment by robertpenner** [comment] 2019-11-05 17:36
@ahocevar When I change `measureTextWidth` back to what it was before the [bisected commit](https://github.com/openlayers/openlayers/commit/b4306da7bb2461fda24e6a54bc8194993bea1e86) you found, the issue is resolved:
```
export function measureTextWidth(font, text) {
    var measureContext = getMeasureContext();
    if (font != measureContext.font) {
        measureContext.font = font;
    }
    return measureContext.measureText(text).width;
}
```

**Comment by ahocevar** [comment] 2019-11-05 17:57
Changing that back has a significant performance impact, that’s why we changed it in the first place.

This needs deeper investigation.

**Comment by ahocevar** [comment] 2019-11-06 17:21
See #10256 for a fix.

**Closed** 2019-11-07 09:30 UTC
Labels: regression
