### ISSUE TITLE
Large image does not load in Static Image Layer

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#10868] opened 2020-04-03 08:28 UTC
I made several tests on different PCs using same extra large PNG file (7021px x 4967px) A0.  On my own PC it works 100% (Windows 64bit - 32Gb Ram), but on another PC (Windows 32bit - 4Gb Ram) it does not load and Openlayers gives an error on the decode promise when trying to decode the image (See below).  When I resize the image to 5000px or less, it works.

NOTICE THE LINE: **error = DOMException: The source image cannot be decoded**

```
function listenImage (image, loadHandler, errorHandler) {
	var img =
      /** @type {HTMLImageElement} */
      image;

	if (img.src && IMAGE_DECODE) {
		var promise = img.decode();
		var listening_1 = true;

		var unlisten = function () {
			listening_1 = false;
		};

		promise.then(function () {
			if (listening_1) {
				loadHandler();
			}
		}).catch(function (error) {   // **error = DOMException: The source image cannot be decoded**  
			if (listening_1) {
				// FIXME: Unconditionally call errorHandler() when this bug is fixed upstream:
				//        https://bugs.webkit.org/show_bug.cgi?id=198527
				if (error.name === 'EncodingError' && error.message === 'Invalid image type.') {
					loadHandler();
				} else {
					errorHandler();
				}
			}
		});
		return unlisten;
	}

	var listenerKeys = [listenOnce(img, EventType.LOAD, loadHandler), listenOnce(img, EventType.ERROR, errorHandler)];
	return function unlisten () {
		listenerKeys.forEach(unlistenByKey);
	};
}
```

**Comment by mike-000** [comment] 2020-04-03 09:13
It's a browser limitation, see #10252

**Comment by 1Map** [comment] 2020-04-03 09:24
Agree, but then at least Openlayers should push through the correct error information (DOMException: The source image cannot be decoded), as I cannot inspect this type of errors, without looking at the Opensource Code (function listenImage).  It just does a errorHandler().  How can I inspect the type of error / error message in my Source's imageloaderror?  Currently I have:

```
		me.imgSource.on('imageloaderror', function (e) {
			Ext.MessageBox.show({
				title: 'Image Load Error',
				msg: 'Unable to load your image!',
				buttons: Ext.Msg.OK,
				icon: Ext.Msg.ERROR
			});
		});
```

**Comment by ahocevar** [comment] 2020-04-03 10:30
@1Map Thanks for mentioning "DOMException: The source image cannot be decoded". If that's the error, then It looks like this issue has to do with `Image.prototype.decode`. To test if this is the case, try to set
```js
Image.prototype.decode = null;
```
This has to run before OpenLayers is loaded, e.g. in a `<script>` element that is executed before OpenLayers.

Let us know if that works.

**Comment by 1Map** [comment] 2020-04-03 11:22
Ok, I tested as you suggested, but now **imageLoadFunction, imageloadend or imageloaderror** never gets called.

```
		me.pageSource = new ol.source.ImageStatic({
			attributions: '© 1map',
			url: '/api/apps/lodgement/file/' + fileId,
			projection: me.imgProjection,
			imageExtent: me.imgExtent,
			imageSize: [iW, iH],
			imageLoadFunction: function (image, src) {
				// NEVER GET CALLED
				image.setImage(me.lastLoadedPageImg);
			}
		});
		me.pageSource.on('imageloadend', function (e) {
				// NEVER GET CALLED
		});
		me.pageSource.on('imageloaderror', function (e) {
				// NEVER GET CALLED
		});
```

**Comment by ahocevar** [comment] 2020-04-03 11:34
I think these functions are only called when `Image.prototype.decode` is available. But the important question is: is the map rendered correctly?

**Comment by 1Map** [comment] 2020-04-03 11:37
No, image does not get drawn.  See my updated question above.

**Comment by 1Map** [comment] 2020-04-03 11:48
Just figured out that it does go into my `imageLoadFunction`, but after that it does not call `imageloadend` or `imageloaderror`.  It also does not draw the image.  Note that I am using a custom `imageLoadFunction` where I set the image myself. Before making the change to `Image.prototype.decode = null;` it use to work

**Comment by 1Map** [comment] 2020-04-03 11:57
What Openlayers should do is:
When **IMAGE_DECODE** is available, then **try** and **decode**.  If it gives an error of "DOMException: The source image cannot be decoded", then return image as not decoded (**loadHandler**) and do not return **errorHandler**.

**Comment by 1Map** [comment] 2020-04-03 13:10
I had to update my imageLoadFunction as follow for it to work:

```
imageLoadFunction: function (image, src) {
	image.setImage(me.lastLoadedPageImg);
	if (image.resolution === undefined) {
		image.resolution = ol.extent.getHeight(image.extent) / image.image_.height;
	}
	image.state = 2; // ImageState.LOADED;
	image.unlistenImage_();
	image.changed();
}
```

**Comment by ahocevar** [comment] 2020-04-03 13:12
Did you monkey patch Image.prototype.decode before ol/has/IMAGE_DECODE is calculated? That’s important. You can also hard Code that value to false if you want to modify the OpenLayers code for testing this.

**Comment by 1Map** [comment] 2020-04-03 13:15
I did yes.

**Comment by ahocevar** [comment] 2020-04-03 13:22
Ok, so it looks like the error also occurs when we're not using `Image.prototype.decode`. So there is really nothing we can do to solve this in the library. But your suggestion to pass the error to the error handler is a good one. Would you mind creating a pull request?

**Comment by razvananton21** [comment] 2020-12-11 16:48
I have a similar problem in 6.3.1. I have a an Image layer with a static image source. It works on web (any browser). However, the problem is on mobile devices. On iOS, the image source is loaded most of the time. However, on Android very few images are loaded. I think this mostly has to do with the image size, but I'm not sure because I was not able to reproduce it every time. Some images are working, and some (that are the same size) are not. 

Anyone encountered something like this? I have tried every single workaround and trick that I found related to this problem, from tweaking the resolution, to loading the image as blob, to modifying the pixel ratio of the map or the layer. Nothing worked.

**Comment by rooby** [comment] 2021-08-23 01:43
I am seeing a similar thing. I add an image layer and have callbacks on 'postrender' and 'error' of the layer to handle the loading indicator the user sees.
With sufficiently large images, neither postrender or error events are ever fired. The image is also never drawn on the map, although if I look at the network traffic in dev tools it looks like the image download did eventually finish.
In this test case it is a ~670mb image downloading in around 2 minutes.

In firefox I see this error: "Error: Promised response from onMessage listener went out of scope".
Seems like if there is an issue then the error event should be fired at some stage.

**Comment by rooby** [comment] 2021-08-23 01:59
Also, it appears that the issue mentioned in the code comment
```
// FIXME: Unconditionally call errorHandler() when this bug is fixed upstream:
//        https://bugs.webkit.org/show_bug.cgi?id=198527
```
has been fixed now.

**Comment by ahocevar** [comment] 2021-08-23 07:41
@rooby That comment is only relevant for svg images. There are several reasons why large images could fail. The first thing to check is whether the generated url can be downloaded stand-alone without error (e.g. with curl, or directly by pasting it into the browser's address bar. Another problem could be missing CORS headers, but that would also affect small images. And when the download finishes correctly, there is still a chance that the canvas needed to render the image gets bigger than the size supported by the browser and device.

The last mentioned problem is related to #9578. At least on devices with a low device pixel ratio, it could improve the situation when fixed.

**Comment by zhassler** [comment] 2021-11-24 21:21
@rooby Could you post your solution using load event functions?  Could anyone else post a good example?  I cant get mine to work.

**Comment by ahocevar** [comment] 2021-12-02 07:41
#13073 should fix this, with no more application level workarounds necessary.

**Closed** 2021-12-03 06:19 UTC
Labels: pull request accepted
