### ISSUE TITLE
Blurred text for fractional zoom levels (Zoomify source)

### ISSUE THREAD

**Issue by eciuli** [openlayers/openlayers#6474] opened 2017-02-09 10:32 UTC
Hello all, 

We have a OL 3.13 integration, using Zoomify for the source of the tiles and the matter we are encountering is that for fractional zoom levels the text is blurred. 
We noticed that in this case the tiles with a lower z index are up-scaled to fit the image that we want to display. For this particular case we would like to try to have the tiles with a higher z index down-scaled to fit the display view. 
We separately tested (on debug OL version) the upscale and downscale of tiles and for the downscale case the text would be sharper.

Is it possible to set a threshold when to trigger upscale or downscale? If not, can you please guide us on the possibilities to extend the current behavior and decide the z index of the tiles for this particular fractional zoom?

For completion, please find the integration code that we use is as follows:

    var source = new ol.source.Zoomify({
       url: url,
       size: [imgWidth, imgHeight],
       crossOrigin: crossOrigin
     });
     var olLayerTile = new ol.layer.Tile({
       source: source
     });

     var proj = new ol.proj.Projection({
       code: 'ZOOMIFY',
       units: 'pixels',
       extent: [0, 0, imgWidth, imgHeight]
     });
       map = new ol.Map({
         layers: [olLayerTile],
         target: 'map',
         view: new ol.View({
           projection: proj,
           center: imgCenter,
           minZoom: minZoom,
           maxZoom: maxZoom,
         }),

         interactions: ol.interaction.defaults({
           shiftDragZoom: false,
           altShiftDragRotate: false,
           pinchRotate: false,
           dragPan: false,
           mouseWheelZoom: false
         }).extend([
           new ol.interaction.DragPan({kinetic: false}),
           new ol.interaction.MouseWheelZoom({duration: 0}),
           new ol.interaction.Select()
         ])
       });

Thank you for your time and assistance with this matter

Regards.

**Comment by anzeznidarsic** [comment] 2017-03-30 08:20
I would also be interested in this solution.

**Comment by ahocevar** [comment] 2017-04-05 16:45
Duplicate of #1953.

**Closed by ahocevar** 2017-04-05 16:45 UTC
