### ISSUE TITLE
Default generic type of VectorSource not compatible with VectorLayer

### ISSUE THREAD

**Issue by KyllianGautier** [openlayers/openlayers#15833] opened 2024-05-16 13:26 UTC
**Describe the bug**
The default generic type of a VectorSource is not compatible with a VectorLayer

**To Reproduce**
`new VectorLayer<VectorSource>({ /** options **/ })`

This causes build errors:
![image](https://github.com/openlayers/openlayers/assets/12836335/5854d7df-3da4-4dfb-be5f-62a254b4ab88)

We have to specify the required generic type to avoid the error, instead of using the default type:
`new VectorLayer<VectorSource<FeatureLike>>({ /** options **/ })`

![image](https://github.com/openlayers/openlayers/assets/12836335/1ca7cb00-d398-4b20-adb6-519e89d5312b)

**Expected behavior**
The default generic type is compatible with the required type by VectorLayer

**Comment by ahocevar** [comment] 2024-05-16 13:31
Duplicate of #15830

**Closed by ahocevar** 2024-05-16 13:31 UTC
Labels: bug

**Comment by ahocevar** [comment] 2024-05-16 13:41
@KyllianGautier When fixed, you can simply do
```ts
new VectorLayer({ /** options **/ })
```

**Comment by tschaub** [comment] 2024-05-16 18:51
You can get the fix in the `ol@9.2.1` release.
