### ISSUE TITLE
the height of the background is not fit with text when text style set with backgrounFill

### ISSUE THREAD

**Issue by Frank-Chan** [openlayers/openlayers#15715] opened 2024-04-09 12:00 UTC
**Describe the bug**
I'm setting a text label for a feature on a vector layer, and giving it a background fill to visually separate it from the background.
However, when I set the background fill, it does not span the entire height of the text label.The more lines, the greater the height of the background from the actual height.
![image](https://github.com/openlayers/openlayers/assets/8639688/5a356e71-cdcc-46d5-ae03-d2ff9f04a30f)

**To Reproduce**
You can see the issued demo to [codesandbox](https://codesandbox.io/p/devbox/rich-text-labels-fontstyle-forked-pc9dmd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu7sv1tz00062a66664iq60k%2522%252C%2522sizes%2522%253A%255B82.95215869311552%252C17.04784130688448%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu7sv1ty00022a66ik1y2yp3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu7sv1tz00042a66k2g2jkx5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu7sv1tz00052a66yslk6l7x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu7sv1ty00022a66ik1y2yp3%2522%253A%257B%2522id%2522%253A%2522clu7sv1ty00022a66ik1y2yp3%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu7sv1tz00052a66yslk6l7x%2522%253A%257B%2522id%2522%253A%2522clu7sv1tz00052a66yslk6l7x%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cluauczsg01w02a66qfw48hfh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluauczsg01w02a66qfw48hfh%2522%257D%252C%2522clu7sv1tz00042a66k2g2jkx5%2522%253A%257B%2522id%2522%253A%2522clu7sv1tz00042a66k2g2jkx5%2522%252C%2522activeTabId%2522%253A%2522clu7svhzb00c22a66pwuz6hh9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu7sv1ty00032a66r4l35cu4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu7szyls000cdcguecv75id0%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clu7svhzb00c22a66pwuz6hh9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

**Expected behavior**
The background height equal to the text height .

**Comment by tschaub** [comment] 2024-04-09 12:56
I’ll close this one as a duplicate of #15716 

if there is detail here that is missing from #15716, that ticket can be edited.

**Closed by tschaub** 2024-04-09 12:56 UTC
Labels: bug
