### ISSUE TITLE
ol.Collection with ol.source.Cluster performance

### ISSUE THREAD

**Issue by 10lojzo** [openlayers/openlayers#6492] opened 2017-02-14 18:01 UTC
I am displaying 1000+ features on the map. Every n seconds I'm making an ajax request for brand new set of data, clearing everything on the map and then adding new features. Before I used plain js array as container for the features and everything worked ok. Then I decided to use ol.Collection instead. The performance dropped drastically from few milliseconds to few seconds. The most weird part is, that everything works fine at first load, then after ol.Collection.clear() it goes down. I tried different ways of clearing the source as well as collection, but to no avail. As a source I am using ol.source.Cluster. The worst scenario is using ol.Collection together with ol.source.Cluster. Much better, but not perfect is using ol.Collection with ol.source.Vector. This last scenario takes roughly tens of milliseconds. So I thing that the primary cause of the problem is the ol.Collection, but ol.source.Cluster is significantly spicing the things up and the UI is stuck for several seconds. Test cases with console output are provided below.

plain array + ol.source.Cluster (working well)
http://jsfiddle.net/aj0bmaqr/1/

ol.Collection + ol.source.Cluster (huge performance hit)
http://jsfiddle.net/5zfw49gz/2/

Note: You need to zoom in to see more features, then the performance is worst.

**Comment by crisley2016** [comment] 2017-02-17 18:25
Each time the ol.Collection is changed (i.e. items are added or removed) then ol.source.Cluster will re-run the cluster operation.  If you  clear() an ol.Collection that is used by an ol.source.Cluster() it will perform a cluster operation once for each item that is being removed.  This does not happen when you use a plain array since it does not fire any events on additions or removals.

**Comment by 10lojzo** [comment] 2017-02-17 21:50
The performance issue is not when the ol.Collection is clearing. It's exactly when it is filled again, either by push method for each feature or by extend of temp plain array. But not when it is filled for the first time, only each time afterwards. There is a console with output, you can see that the time measured in milliseconds is only computed for adding feature to collection. And for the first time it takes couple of milliseconds but then it goes to several seconds.

**Comment by silviu-negoita** [comment] 2017-06-08 13:26
I have a similar  problem when i make a lot of push/remove/geometry edit on ol.Collection combined with ol.source.Cluster. I think the problem is because for **every single(one by one)** mentioned action, ol.Colection triggers an event(add, remove, change) which is caught by the cluster which makes an internal extensive task - `ol.source.Cluster.prototype.refresh_()`. A solution is to add methods which doesn't  trigger these events or capabilities to remove the default events, and let the user to manual make a refresh after all operations are made. In this case all changes are processed at once, not one by one.
There is a related question asked by me on stackoverflow : [https://stackoverflow.com/questions/44257236/disable-ol4-some-default-event-listeners?noredirect=1#comment75567490_44257236](url)

**Comment by 10lojzo** [comment] 2017-06-08 13:43
I recreated the issue over a month ago with more specific description and fiddle usecases. 

I can get along with the fact, that the collection gets slower with each new item in it. But this is not what bothers me that much.  You can completely clear the collection and it still gets slower. It is ridiculous. There must be some object-event leak undetected by clear method. The only solution is to create completely new collection and that requires you to recreate also the cluster.

**Comment by silviu-negoita** [comment] 2017-06-08 13:57
I have this problem also, and i might have an explanation for it too. When your create a new cluster, and add elements, it might not be yet attached to map when you do those operations(in your case clear), thus all events are ignored or easy to pass. Keep in mind that when you do ol.Collection.clear(), you will end up triggering an event for **each removed element** (see `
this.dispatchEvent(new ol.Collection.Event(ol.CollectionEventType.REMOVE, prev))` from ol.Collection.removeAt() which is called from .clear method for each element) which leads to my previous mentioned issues.

**Comment by ahocevar** [comment] 2017-06-09 07:06
Closing in favor of #6768. My advice: Don't use `ol.Collection` on an `ol.source.Vector` when all you need to do is replace the whole set of features. Do the following:
```js
cluster.getSource().clear();
cluster.getSource().addFeatures(newFeatures);
```

**Closed by ahocevar** 2017-06-09 07:06 UTC
