### ISSUE TITLE
ol.layer.Heatmap does not support gradient in webgl rendering mode

### ISSUE THREAD

**Issue by ponceta** [openlayers/openlayers#3608] opened 2015-04-21 14:47 UTC
Using webgl renderer, there's no color (black) on the ol.layer.heatmap, the gradient is not taken into account.

![image](https://cloud.githubusercontent.com/assets/8614223/7255073/4b7931b2-e847-11e4-9a59-c9d620c054d9.png)

**Comment by fredj** [comment] 2015-04-21 15:01
`ol.layer.Heatmap` only works with canvas renderer. This should be enforced by the code

**Comment by ponceta** [comment] 2015-04-21 15:04
Ok, so this is a won't fix? Because I had the feeling that my animated heatmap was more stable on webgl than on canvas.

**Comment by fredj** [comment] 2015-04-21 15:15
Not a *won't fix* but a *patch welcome* !

**Comment by fredj** [comment] 2015-04-29 12:28
@ponceta  By "stable on webgl" you mean "faster on webgl" ?

The heatmap computation could probably be speeded up by used [webworkers](http://www.html5rocks.com/en/tutorials/workers/basics/)

**Comment by ponceta** [comment] 2015-04-29 14:00
Since I'm adding many features dynamically, the computation seems to be faster on webgl.

I use text/event stream to add/remove these elements progressively with time.

**Comment by Type1J** [comment] 2015-07-16 11:56
I really need this feature as well. Mobile devices can't handle HeatMap well except with WebGL.

**Comment by Type1J** [comment] 2015-07-22 12:55
I've tried to work this into the WebGL renderer, but I haven't gotten very good results. Basically, I added a second texture to be a color palette that's refreshed when the gradient changes, and I added a fragment shader looks at it for the color value.

However, a heatmap really needs to be rendered to it's own buffer, and then the result is what needs to be paletted. The reason that my results are bad are that each point in the heatmap renders the canvas generated image (a blurred circle), and only that is colored. Only the final composted image should be paletted, so I need to render the vectors to a texture, and then use that texture as input to the result that will be composted. I know how to do that with WebGL, but it seems that OpenLayers 3 only has a way to render single pass graphics. Is there a "right way" to render to an FBO and composite it (or several textures) to the map?

**Comment by fredj** [comment] 2018-03-05 15:15
Closing due to lack of activity.

**Closed by fredj** 2018-03-05 15:15 UTC

**Comment by Type1J** [comment] 2018-03-05 21:30
I really would like this issue fixed. I had to work around it at the time. The canvas renderer was way too slow, and the WebGL renderer with my patches did work after some optimization. What I have described here isn't hard to reproduce. I don't have access to that source anymore, but this issue may come up for me again at some point soon.
