### ISSUE TITLE
OverLay的positioning设置为有包含‘center'的属性时，会有延迟效果，需要在地图上点击才可以实现

### ISSUE THREAD

**Issue by zhangquans** [openlayers/openlayers#8634] opened 2018-09-14 09:08 UTC
var faultDiv=document.getElementById("faultDiv");
    var layer = new ol.layer.Vector({
        source: new ol.source.Vector()
    });
    var myView= new ol.View({
        projection: 'EPSG:4326',
        center: [104, 30],
        zoom: 10
    });
    var map = new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            }),
            layer
        ],
        target: 'map',
        view:myView
    });

    var anchor = new ol.Feature({
        geometry: new ol.geom.Point([104, 30]),
    });

   anchor.setStyle(new ol.style.Style({
        image: new ol.style.Icon({
            src: '/on-line.png',
        })
    }));
    layer.getSource().addFeature(anchor);
    function  getDiv(){
        var imagediv=" <div id='deviqi'><img src='/on-line.png' ></div>";

            faultDiv.innerHTML=imagediv;
            var overlay1=new ol.Overlay({
                element:document.getElementById("deviqi"),
                position:[104,30],
                positioning:"bottom-center"
            });
            map.addOverlay(overlay1);

    }

    setInterval("getDiv()",3000);

**Comment by ahocevar** [comment] 2018-09-14 09:10
Duplicate of #8632.

**Closed by ahocevar** 2018-09-14 09:10 UTC
