### ISSUE TITLE
undefined usedTiles leads to exception

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#6271] opened 2016-12-17 04:00 UTC
Faced with the similar bug as described [here](https://github.com/openlayers/ol3/issues/2646). It hard to reproduce with one layer, but in our project with 10 VectorTile layers when we start quickly zooming out we get error in console:

```
ol-debug.js Uncaught TypeError: Cannot use 'in' operator to search for '16' in undefined
```

Using debugger we have found that cause of this issue is `undefied` value of `usedTiles` [here](https://github.com/openlayers/ol3/blob/master/src/ol/tilecache.js#L43).

**Comment by ahocevar** [comment] 2016-12-17 14:28
Do you have a JSFiddle that helps to reproduce the problem? Or at least a full stack trace?

**Comment by drnextgis** [comment] 2016-12-17 14:54
What I've got from browser console:

```
ol-debug.js:72136 Uncaught TypeError: Cannot use 'in' operator to search for '11' in undefined
ol.TileCache.expireCache @ ol-debug.js:72136
ol.source.Tile.expireCache @ ol-debug.js:72235
(anonymous function) @ ol-debug.js:25763
ol.Map.handlePostRender @ ol-debug.js:41833
```

**Comment by ahocevar** [comment] 2016-12-17 16:27
I tried to reproduce this with the [`osm-vector-tiles.html`](https://openlayers.org/en/latest/examples/osm-vector-tiles.html) example, which loads 3 vector tile layers, but did not run into the issue.

**Comment by drnextgis** [comment] 2016-12-17 16:48
Trying to make JSFiddle example.

**Comment by drnextgis** [comment] 2016-12-18 06:12
Hard to reproduce with JSFiddle. Using debugger I've found that issue comes from [here](https://github.com/openlayers/ol3/blob/master/src/ol/renderer/layer.js#L164):

```
> tileSourceKey
< "36"
> Object.keys(frameState.usedTiles)
< ["1", "30", "32", "34", "38", "40", "42"]
```

As you can see `tileSourceKey` is not in `frameState.usedTiles`. Also (may be important) layer with "36" source should not be visible on zoom level when I get an error because it has `maxResolution` settings.

**Comment by tschaub** [comment] 2016-12-20 15:41
Not on a device where I can get to the code, but this sounds like it could be caused by the check that bypasses composition if the frame budget is blown.

**Comment by ahocevar** [comment] 2016-12-20 19:24
> it could be caused by the check that bypasses composition if the frame budget is blown.

To see if this is the case, can you test something for me please @drnextgis? Take a copy of `ol-debug.js` from v3.20.0, and remove `!(this.renderedResolution && Date.now() - frameState.time > 16 &&` in line 26515. Then try again. Does it make a difference?

**Comment by JelmerBaas** [comment] 2017-09-27 13:42
What is the status of this issue? Is this fixed in 3.20 or higher? We're still at 3.18 (yikes) and I'm seeing this error occasionally. Can't seem to reproduce it with an OSM layer, though, so I'm wondering if this is worth an update.

**Comment by ahocevar** [comment] 2017-09-27 14:29
As far as I can tell, we never were able to fix this issue because noone was able to provide instructions or a code pen to reproduce it.

**Comment by fredj** [comment] 2018-03-07 09:13
Closing due to lack of activity.

**Closed by fredj** 2018-03-07 09:13 UTC
