### ISSUE TITLE
only one scaling direction for fractional zoom

### ISSUE THREAD

**Issue by danielpce** [openlayers/openlayers#6672] opened 2017-04-05 12:47 UTC
![compareupscalingwithdownscaling](https://cloud.githubusercontent.com/assets/2607231/24705878/5e2e0ab4-1a16-11e7-888a-83e700bf5c3c.png)

We have high resolution images loaded with openlayers v4.0.1 using ol.source.Zoomify source. We handle fractional zoom and we have an issue with blurred text for fractional zoom. Attached image is the comparison of tiles rendered as it is in openlayers (in red boxes) and how it could be (in green boxes) if they would be rendered with next better resolution tiles.

It seems that if the browser tries to guess the pixels from a lower resolution image is not as good if it makes a scaling from a higher resolution image. 

How can we add a resolution constrain to use the tiles from better resolution layer in case of any fractional zoom?

**Comment by ahocevar** [comment] 2017-04-05 16:46
Duplicate of #1953.

**Closed by ahocevar** 2017-04-05 16:46 UTC

**Comment by ahocevar** [comment] 2017-04-05 16:59
> How can we add a resolution constrain to use the tiles from better resolution layer in case of any fractional zoom?

You could configure your PinchZoom and MouseWheelZoom interactions with `constrainResolution: true`. The latter is not yet available, but will be [soon](https://github.com/openlayers/openlayers/pull/6671).
