### ISSUE TITLE
I hope the Zoom Slider Control behavior of OpenLayers version 4 return to as in version 3.

### ISSUE THREAD

**Issue by astroace** [openlayers/openlayers#7485] opened 2017-11-18 12:48 UTC
Since the time Openlayers change from version 3 to version 4, the zoom slider control became difficult to use.

The behavior of the zoom slider of version 4.0.0 or later is as follows.

(Start reproduction)
First, drag the toggle of the zoom slider, and while holding down the mouse button, and move the mouse pointer outside of the Zoom Slider Control range. (The toggle remains within the range of the Zoom Slider Control)
Next, release the mouse button in area of outside of the Zoom Slider Control range.
Next, with the mouse button released, move the mouse pointer into the range of the Zoom Slider Control.
And then, the zoom slider toggle suddenly starts to move. At the same time, the zoom level is changed without permission.
(Reproduction end)

I am suffering from this Zoom Slider Control behavior. So please.
I want the behavior of Zoom Slider Control of OpenLayers version 4 to return as in version 3.
To that end, I would like to ask to restore the "dragListenerKeys_" and the related codes (in zoomslider.js) which existed up to version 3.20.1.

that's all, thank you.

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ o] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ o] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ o] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ o] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment] 2017-11-19 12:57
Please submit a pull request with the suggested fix.

**Comment by marcjansen** [comment] 2017-11-20 16:26
If you need any help providing the PR, just drop a line here.

**Comment by astroace** [comment] 2017-11-22 14:38
Thank you for your replies.

Specifically, it is as follows.

In the following, (+) means row addition.

(Excerpt by current codes in the "zoomslider.js(version 4.5.0)")
     /**
      * @type {boolean}
      * @private
      */
     this.dragging_;

     /**
      * @type {number}
      * @private
      */
     this.heightLimit_ = 0;

(My proposal referring codes "zoomslider.js (version 3.20.1)".)
     /**
      * @type {boolean}
      * @private
      */
     this.dragging_;

(+)  /**
(+)   * @type {!Array.<ol.EventsKey>}
(+)   * @private
(+)   */
(+)  this.dragListenerKeys_ = [];

     /**
      * @type {number}
      * @private
      */
     this.heightLimit_ = 0;

(Excerpt by current codes in the "zoomslider.js(version 4.5.0)")
/**
 * Handle dragger end events.
 * @param {ol.pointer.PointerEvent|Event} event The drag event.
 * @private
 */
ol.control.ZoomSlider.prototype.handleDraggerEnd_ = function(event) {
  if (this.dragging_) {
    var view = this.getMap().getView();
    view.setHint(ol.ViewHint.INTERACTING, -1);

    view.animate({
      resolution: view.constrainResolution(this.currentResolution_),
      duration: this.duration_,
      easing: ol.easing.easeOut
    });

    this.dragging_ = false;
    this.previousX_ = undefined;
    this.previousY_ = undefined;
  }
};

(My proposal referring codes "zoomslider.js (version 3.20.1)".)
   /**
    * Handle dragger end events.
    * @param {ol.pointer.PointerEvent|Event} event The drag event.
    * @private
   */
   ol.control.ZoomSlider.prototype.handleDraggerEnd_ = function(event) {
     if (this.dragging_) {
       var view = this.getMap().getView();
       view.setHint(ol.View.Hint.INTERACTING, -1);

       view.animate({
         resolution: view.constrainResolution(this.currentResolution_),
         duration: this.duration_,
         easing: ol.easing.easeOut
       });

       this.dragging_ = false;
       this.previousX_ = undefined;
       this.previousY_ = undefined;
(+)    this.dragListenerKeys_.forEach(ol.events.unlistenByKey);
(+)    this.dragListenerKeys_.length = 0;
     }
   };

(Excerpt by current codes in the "zoomslider.js(version 4.5.0)")
   /**
    * Handle dragger start events.
    * @param {ol.pointer.PointerEvent} event The drag event.
    * @private
    */
   ol.control.ZoomSlider.prototype.handleDraggerStart_ = function(event) {
     if (!this.dragging_ &&
         event.originalEvent.target === this.element.firstElementChild) {
       this.getMap().getView().setHint(ol.View.Hint.INTERACTING, 1);
       this.previousX_ = event.clientX;
       this.previousY_ = event.clientY;
       this.dragging_ = true;
     }
   };

(My proposal referring codes "zoomslider.js (version 3.20.1)".)
   /**
    * Handle dragger start events.
    * @param {ol.pointer.PointerEvent} event The drag event.
    * @private
    */
   ol.control.ZoomSlider.prototype.handleDraggerStart_ = function(event) {
     if (!this.dragging_ &&
         event.originalEvent.target === this.element.firstElementChild) {
       this.getMap().getView().setHint(ol.View.Hint.INTERACTING, 1);
       this.previousX_ = event.clientX;
       this.previousY_ = event.clientY;
       this.dragging_ = true;
(+)    if (this.dragListenerKeys_.length === 0) {
(+)      var drag = this.handleDraggerDrag_;
(+)      var end = this.handleDraggerEnd_;
(+)      this.dragListenerKeys_.push(
(+)        ol.events.listen(document, ol.events.EventType.MOUSEMOVE, drag, this),
(+)        ol.events.listen(document, ol.events.EventType.TOUCHMOVE, drag, this),
(+)        ol.events.listen(document, ol.pointer.EventType.POINTERMOVE, drag, this),
(+)        ol.events.listen(document, ol.events.EventType.MOUSEUP, end, this),
(+)        ol.events.listen(document, ol.events.EventType.TOUCHEND, end, this),
(+)        ol.events.listen(document, ol.pointer.EventType.POINTERUP, end, this)
(+)      );
(+)    }
     }
   };

that's all, thank you.

**Comment by iray-tno** [comment] 2018-01-17 08:58
@astroace Reverting 7b687be9e0352c1f39afd2d489916e73a1715957 might cause regression of #5526.

**Comment by tr00st** [comment] 2018-09-21 14:54
Currently implementing a system here and heavily impacted by this issue, so I'm going to look to write a proper Pull Request for this. Looks like it'll need to be a case of reverting 7b687be (given it's _literally_ removing support for the required mouse events) then putting together a proper fix for #5526.

**Comment by ahocevar** [comment] 2018-09-24 11:16
Fixed with #8698.

**Closed by ahocevar** 2018-09-24 11:16 UTC
Labels: pull request accepted
