### ISSUE TITLE
SVG ol.style.Icon does not working  in IOS

### ISSUE THREAD

**Issue by RoronoaZoro325** [openlayers/openlayers#9643] opened 2019-06-04 11:19 UTC
```
new Style({
      image: new Icon(
        /** @type {module:ol/style/Icon~Options} */
        ({
          src: 'data:image/svg+xml;utf8,<svg width="0.41em" height="0.8em" style= "padding-left:1" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><polygon points="2.5,0 0,12 5,12" style="fill:' + $Stores.mapParams.colorbdxt + ';stroke:rgb(0,0,0);stroke-width:0.35"></polygon></svg>',
          scale: 2,
          anchor: [0.5, 0.5],
          anchorXUnits: "fraction",
          anchorYUnits: "fraction",
          rotation: 0
        })
      )
    })
```
This works on android, but not on IOS.</br>
The icon does not appear in IOS.

**Comment by fredj** [comment] 2019-06-04 11:22
Thanks for the bug report @RoronoaZoro325 , this is a known issues that will be fixed soon.
Duplicate of #9628

**Closed by fredj** 2019-06-04 11:22 UTC
