### ISSUE TITLE
Improve text placement on lines

### ISSUE THREAD

**Issue by yaugenka** [openlayers/openlayers#8104] opened 2018-04-21 16:38 UTC
The screenshot below showns river ways with labels as vector features. Each river is presented as a single line. The lines are very curvy. The labels are styled with placement: 'line', maxAngle: 0.5, overflow: true.

1. When maxAngle is defined some charactures start overlapping. It would be better to prevent such overlapping by taking the angle of adjacent charactures into account.
2. Although the length of the line is enough to fit the entire label, it may sometimes be placed beyond the line. It would be better to keep labels within the line if it is long enough to fit them.
3. One and the same label instances are sometimes rendered overlapping each other. It would be better to prevent such overlapping.
4. Label instances are sometimes rendered too close to each other in which case they look cluttered. It would be nice to add some paramether to control the number of instances a label is rendered on the current map view.
![screenshot_3](https://user-images.githubusercontent.com/14937001/39086474-9c27633c-459a-11e8-98d4-e751aabf4288.png)

**Comment by venugopal-rao** [comment] 2018-06-27 05:11
Can anyone help me to align the text along with the orientation of the line

**Comment by ahocevar** [comment] 2018-06-27 07:42
Duplicate of #8236, which has more detail on the problem.

**Closed by ahocevar** 2018-06-27 07:42 UTC
