### ISSUE TITLE
Bug in Example of CodeSandbox

### ISSUE THREAD

**Issue by gabriell273** [openlayers/openlayers#10714] opened 2020-02-20 14:38 UTC
today, I went to see the example of LineString Arrows, on the OpenLayers website it works perfectly, but in the codesandbox the arrows are not placed on the lines

[Exemple of OpenLayers](https://openlayers.org/en/latest/examples/line-arrows.html)

[Example of CodeSandbox](https://codesandbox.io/s/p2ty0)

**Comment by ahocevar** [comment] 2020-02-20 15:00
The problem is that relative `data/` paths are not converted to absolute paths or data resources when sending the code to the codesandbox.

**Comment by mike-000** [comment] 2021-03-02 13:34
This was fixed by #11569

**Closed** 2021-06-27 14:55 UTC
Labels: bug
