### ISSUE TITLE
Request to make abortDrawing_() public in Draw interaction?

### ISSUE THREAD

**Issue by jeremy-smith-maco** [openlayers/openlayers#10642] opened 2020-02-12 06:49 UTC
I want to be able to abort a drawing that is in progress. I know I can call abortDrawing_() in my code but it is supposed to be private so is it possible to make it a public method? I know it has been brought up in #7261 and a PR was even submitted for it at #6526 but it was never acknowledged or anything of the sort. Is there some reason for that?

**Comment by ahocevar** [comment] 2020-02-12 10:40
ping @fredj - you wanted to review #6526 back then.

**Comment by ahocevar** [comment] 2020-02-12 10:41
Duplicate of #7261.

**Closed by ahocevar** 2020-02-12 10:41 UTC
