### ISSUE TITLE
ScaleBar issue or Bad coding?

### ISSUE THREAD

**Issue by flipper44** [openlayers/openlayers#8057] opened 2018-04-04 20:06 UTC
I am having scale bar issues upgrading to ol 4.6.5 on many levels.

My Code:
//Check if a coordinate System Override is present i.e. if it is Override the WKT that came from Mapguide
if (display_srs !== undefined && display_srs !== null && display_srs != '') {
	Mapguide.Wkt = Map_display_srs;
}
```
var tempproj = 'EPSG:' + Mapguide.EpsgCode;
//First see if Mapguide EPSG code is recognized
var csproj = ol.proj.get(tempproj);
if (csproj === undefined || csproj === null) {
	// Not recognized
	proj4.defs('Custom', Mapguide.Wkt);
	var x = proj4.defs('Custom');
	var newProj = ol.proj.get('Custom');
	ol.proj.addProjection(newProj);
	Map_display_srs = 'Custom';
	newProj.setGetPointResolution(function (resolution) { return resolution; });
}
else {
	//Proj4js Recognized the Mapguide EPSG Code
	csproj.setGetPointResolution(function (resolution) { return resolution; });
	Model.Config.general.display_srs = Model.MapguideSrs = tempproj
}
```
This Reads the Coordinate System from a Mapguide layer source and determines if the user has set an override WKT and if Mapguide EEPSG code is not in proj4js it creates one from the Mapguide WKT or Override WKT. This worked fine in my old open layers.

if I don't use newProj.setGetPointResolution(function (resolution) { return resolution; });
i get these results for a scale bar next to a 1 mile Square.

![image](https://user-images.githubusercontent.com/16003063/38331475-f4a866b2-3818-11e8-9381-02fb886523d5.png)
Spherical Mercator ^ (correct)

![image](https://user-images.githubusercontent.com/16003063/38331584-36276016-3819-11e8-975d-800a7b3e9b17.png)
State Plane ^ (incorrect)

after adding newProj.setGetPointResolution(function (resolution) { return resolution; });

![image](https://user-images.githubusercontent.com/16003063/38331707-8efad4b6-3819-11e8-8278-73876f56ac4c.png)
Spherical Merc ^ (incorrect)

![image](https://user-images.githubusercontent.com/16003063/38331755-b6ce8d66-3819-11e8-946e-209826912e95.png)
State Plane ^ (correct)

**Comment by flipper44** [comment] 2018-04-04 20:14
Also wonder if this is why my printing and Buffer code are all messed up as well.
Buffer:
```
_getResolutionFactor: function(){
	var resolutionAtEquator = Map.getView().getResolution();
	var center = Map.getView().getCenter();
	var pointResolution = Map.getView().getProjection().getPointResolution(resolutionAtEquator, center) * Model.Map.getView().getProjection().getMetersPerUnit();
	var resolutionFactor = resolutionAtEquator / pointResolution;
	return resolutionFactor;
},
_formatDist: function(){
	var dist = $('.inputDist')[0].value;
	$('.inputDist')[0].value = '';
	var resFactor = this._getResolutionFactor();
	switch(bufferModel.unitSelect.value){
		case 'Miles':
			return (( dist * (ol.proj.METERS_PER_UNIT.ft * 5280)) * resFactor);
		case 'Kilometers':
			return (( dist * ol.proj.METERS_PER_UNIT.m) * 1000) * resFactor;
		case 'Feet':
			return (( dist * (ol.proj.METERS_PER_UNIT.ft))) * resFactor;
		case  'Meters':
			return (( dist * (ol.proj.METERS_PER_UNIT.m))) * resFactor;
		case 'Yards':
			return (( dist * (ol.proj.METERS_PER_UNIT.ft) * 3)) * resFactor;
		case 'Nautical Miles':
			return (( dist / (ol.proj.METERS_PER_UNIT.degrees)) * 1852) * resFactor;
		default:
			return (( dist * (ol.proj.METERS_PER_UNIT.m))) * resFactor;
	}
}
```

**Comment by flipper44** [comment] 2018-04-04 20:16
OOPS re: buffer and printing I am using  Map.getView().getProjection().getPointResolution and this is no longer available I forgot.
How can't figure out how to use this new resolution tool setGetPointResolution to solve all of these problems (i.e. calculating an accurate buffer, scale bar, and printing to scale for all coord systems) Am i missing something here or is there a code issue in OL?

**Comment by fredj** [comment] 2018-06-19 07:16
This is probably a duplicate of #7700

**Closed by fredj** 2018-06-19 07:16 UTC
