### ISSUE TITLE
Unable to pan after Android updates

### ISSUE THREAD

**Issue by aizzo73** [openlayers/openlayers#6242] opened 2016-12-14 08:49 UTC
After recent updates to my Android 5.1.1 on nexus10 I'm unable to drag any map. I tested same app on Android 4.x and 6.x, and it is still working correctly; Before updates, application was working also on 5.1.1. I 'tried upgrading ol.js to last version: this works in 5.1.1, but not in 4.x less than 4.4.
Can anyone help me?

**Comment by sweco-semara** [comment] 2017-01-04 13:43
Seems that Chrome 55 with Pointer Events [1] broke pan in both OpenLayers 2 and 3. OpenLayers 2 have filed a bug [2] and a pull-request that fixes the issues [3]. There is a Chromium issue tracking this [4]. The methods used in openlayers/ol2#1511 should be able to fix this in OL3 as well.
[1] https://developers.google.com/web/updates/2016/11/nic55#pointer-events
[2] https://github.com/openlayers/ol2/issues/1510
[3] https://github.com/openlayers/ol2/pull/1511
[4] https://bugs.chromium.org/p/chromium/issues/detail?id=670942

**Comment by ahocevar** [comment] 2017-01-04 14:07
Just tested with Chrome 55 and Nexus 10 emulation and cannot reproduce this issue for OpenLayers 3 (but I can for OpenLayers 2).

Also, the pointer events shim in OpenLayers 2 works exactly the other way around as in OpenLayers 3.

**Comment by sweco-semara** [comment] 2017-01-04 14:48
Sorry, my test concerns an older OL3 build - problem should be gone by upgrading to latest release. I will try to fix it by backporting and reporting what causes this in older builds ~= OL3 v3.4.0. Thanks for clarifying the shim.

**Comment by ahocevar** [comment] 2017-01-04 14:50
Thanks for the clarification @sweco-semara. So can we close this issue?

**Comment by sweco-semara** [comment] 2017-01-04 14:53
@ahocevar Don't know what version or build of OpenLayers 3 OP is using - ping @aizzo73? But for my part, yes.

**Comment by aizzo73** [comment] 2017-01-04 22:09
I can confirm what I said in my comment: recent openlayers3 builds (for example 3.19.1) fix the issue, which is present for example in 3.9.0. But I confirm also that recent builds can't be used in Android pre 4.4. So, yes, the issue can be closed, but the final question is unanswered: how to deploy an app that can be run both on older an newer Android version?

**Comment by ahocevar** [comment] 2017-01-05 09:03
For Android pre 4.4 with recent OpenLayers versions, you will need the polyfills we have in the source code of our official examples:
```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
```
If that does not work, please open a separate ticket.

**Closed by ahocevar** 2017-01-05 09:03 UTC

**Comment by sweco-semara** [comment] 2017-01-12 09:12
@aizzo73 On v3.4.0 we added the OL2 CSS work-around to the DOM element containing the OpenLayers 3 map object, like so:
```
#map {
    // ...
    -ms-touch-action: none;  
    touch-action: none;
    // ...
}
```
Works with Chrome v54 on Android 4.3 and 4.4 and recent Chrome v55 on Anroid 5 and 6.

**Comment by aizzo73** [comment] 2017-01-12 10:50
Great!

Tested on android 5.1.1/chrome 55 and android 4.3/browser 4.3. Works like a charm.

Thanks.
