### ISSUE TITLE
I am unable to render gif image as marker. Can any one Help me on this

### ISSUE THREAD

**Issue by AnilKumaRLotla** [openlayers/openlayers#9447] opened 2019-04-19 08:38 UTC
Below is sample code 

let iconStyle = new ol.style.Style({
                        image: new ol.style.Icon({
                            anchor: [0.6, 32],
                            anchorXUnits: 'fraction',
                            anchorYUnits: 'pixels',
                            opacity: 0.9,
                            //color: 'green',
                            src: 'https://articulate-heroes.s3.amazonaws.com/uploads/rte/kgrtehja_DancingBannana.gif',
                            fill: new ol.style.Fill({
                                color: 'green'
                            }),
                            stroke: new ol.style.Stroke({
                                color: 'white',
                                width: 1,
                                lineJoin: 'round'
                            })
                        })
                    })

                    var marker = new ol.Feature({
                        type: 'click',
                        geometry: new ol.geom.Point(ol.proj.transform([113.07244346533638, 3.2778962754115213], 'EPSG:4326', 'EPSG:3857')),
                    });
                
                    var markers = new ol.source.Vector({

                        features: [marker]
                    });

                    this.swotMarker = new ol.layer.Vector({
                        source: markers,
                        style: iconStyle
                    });

**Comment by fredj** [comment] 2019-04-23 08:46
Please provide a links to a minimal example (using https://codesandbox.io or similar) that demonstrates the issue? Thanks

**Comment by mike-000** [comment] 2019-04-30 10:49
If you are wanting the gif to animate see this stackoverflow. question https://stackoverflow.com/questions/43277959/can-openlayers-3-render-the-animated-marker-using-gif

**Comment by AnilKumaRLotla** [comment] 2019-05-02 09:10
> If you are wanting the gif to animate see this stackoverflow. question https://stackoverflow.com/questions/43277959/can-openlayers-3-render-the-animated-marker-using-gif
Hi, Goodday,
Thanks for your response.
I already gone through this example, but my requirement is  multiple markers on fly. My provided example initialize multiple markers on fly, but i am unable to use gif file instead of png

please refer this link, my requirement to develop animation multiple markers dynamically.
https://codepen.io/shevawen/pen/xwYxrV

**Comment by mike-000** [comment] 2019-05-02 13:34
You can do it dynamically by creating elements and styling them on the fly https://jsfiddle.net/fan85g34/

**Comment by fredj** [comment] 2019-05-17 10:10
Duplicate of #7753

**Closed by fredj** 2019-05-17 10:10 UTC
