### ISSUE TITLE
Error loading mapbox vector tiles (vector.pbf)

### ISSUE THREAD

**Issue by slavas62** [openlayers/openlayers#7232] opened 2017-09-07 09:30 UTC
Hi, In the new version OL3-Cesium v1.31, the vector tiles of the mapbox (format PBF) are not loaded in 2D mode (Error: Unimplemented type: 3 olcesium-debug.js: 65364). In the previous version of OL3-Cesium v1.30 in 2D mode everything was loaded without problems.

**Comment by ahocevar** [comment] 2017-09-07 10:02
Can you isolate the issue with a minimal OpenLayers map, without ol-cesium?

**Comment by slavas62** [comment] 2017-09-07 10:34
Without ol-cesium, unfortunately, I can not isolate the problem. My project only works on ol-cesium. -- С уважением,Вячеслав Серебряков   07.09.2017, 13:03, "Andreas Hocevar" <notifications@github.com>:Can you isolate the issue with a minimal OpenLayers map, without ol-cesium?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ahocevar** [comment] 2017-09-07 10:40
In this case I'd assume the issue is related to ol-cesium, so I'm closing this. Feel free to create a new ticket if you manage to isolate the problem.

**Closed by ahocevar** 2017-09-07 10:40 UTC
