### ISSUE TITLE
Clipped VectorTile rendering with renderMode: 'image' when browser is zoomed

### ISSUE THREAD

**Issue by mshubin** [openlayers/openlayers#10553] opened 2020-01-20 10:44 UTC
**Describe the bug**
I have a similar issue which has been raised [here](https://github.com/openlayers/openlayers/issues/3909) but this time with VectorTile using renderMode: 'image'.

When user zoomed the browser (with Ctrl-+ for example) it makes tiles clipped as in animation below:
![clipped-tiles](https://user-images.githubusercontent.com/2290300/72719209-b01c1980-3b77-11ea-8955-54e50695b729.gif)
.. there is a some kind of 'clip' between tiles.

The bug doesn't occur when:
* Browser is 100%
* imageMode is 'hybrid'

**To Reproduce**
1. Go to https://codesandbox.io/s/clipped-mvt-rendering-with-browser-zoom-ecocl?fontsize=14&hidenavigation=1&theme=dark
2. Zoom your browser (I reproduced with 150%)
3. Reload the url (otherwise it will work)
4. Zoom to left from 'Juranville' city
5. On level 19 you'll see the output as in animation

**Expected behavior**
The rendering as when the browser is not zoomed.

Thank you in advance and have a nice day,

**Comment by jeroenvheel** [comment] 2020-03-23 20:47
I also have the same problem !! I’m going to turn off image rendering tomorrow and see if it’s working.

**Comment by jeroenvheel** [comment] 2020-03-24 05:38
When using _Image_ / _hybrid_ or _vector_ i still git the clipped vector

![image](https://user-images.githubusercontent.com/228655/77391853-0be26900-6d9a-11ea-8cfc-4721ddcc9cd9.png)

**Comment by jeroenvheel** [comment] 2020-03-25 19:13
I fixed this by adding a bigger buffer to the tile vector

**Comment by Benjaki2** [comment] 2020-04-23 02:21
I am having this problem as well.

**Comment by ahocevar** [comment] 2020-04-24 07:52
The screenshot that @jeroenvheel looks like the vector tile source might have polygons with the wrong winding order. That could be fixed by configuring the `MVT` format with `ol/Feature` as `featureClass`:
```
import VectorTileSource from 'ol/source/VectorTile';
import MVT from 'ol/format/MVT';
import Feature from 'ol/Feature';

new VectorTileSource({
  format: new MVT({
    featureClass: Feature
  }),
})

**Comment by Benjaki2** [comment] 2020-04-28 22:58
Here are some examples:

**OL-latest** 
![ol-point](https://user-images.githubusercontent.com/3605988/80545398-39b26300-8981-11ea-9deb-0c1c9b232aff.gif)


**OL5.3.0** ✅ 
![ol5-point](https://user-images.githubusercontent.com/3605988/80545764-1cca5f80-8982-11ea-8b59-3e711a1cd386.gif)



**Code example**
https://codepen.io/benjaki/pen/zYvzGxd

**Comment by ahocevar** [comment] 2020-04-29 07:10
@Benjaki2 Your issue is caused by an invalid tilegrid. Probably due to #10974.

**Comment by ahocevar** [comment] 2020-04-29 15:55
@Benjaki2 Your issue is fixed with #10398 

@mshubin's issue looks similar, so I think that should also be fixed. Not sure about @jeroenvheel's issue though. Can you please test with the fix applied and report back?

**Closed** 2020-04-30 06:44 UTC

**Comment by mshubin** [comment] 2020-05-07 09:19
@ahocevar I confirm, I've tested it in my codesandbox example with last 6.3.2-dev and the issue doesn't occur anymore :+1: Can't wait to integrate it in our app.

Thank you very much !

**Comment by Benjaki2** [comment] 2020-05-07 17:15
Looks great. Thank you! @ahocevar
