### ISSUE TITLE
Issue while downloading Closure_util through npm

### ISSUE THREAD

**Issue by raviindrapandey** [openlayers/openlayers#6821] opened 2017-05-17 10:42 UTC
Getting below error While Downloading closure through OpenLayers

25876 verbose stack Error: closure-util@1.20.0 postinstall: node ./bin/closure-util.js update
25876 verbose stack Exit status 1
25876 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
25876 verbose stack at emitTwo (events.js:106:13)
25876 verbose stack at EventEmitter.emit (events.js:191:7)
25876 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
25876 verbose stack at emitTwo (events.js:106:13)
25876 verbose stack at ChildProcess.emit (events.js:191:7)
25876 verbose stack at maybeClose (internal/child_process.js:886:16)
25876 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
25877 verbose pkgid closure-util@1.20.0
25878 verbose cwd D:\Work\OL4BuildKit\openlayers
25879 error Windows_NT 10.0.10586
25880 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "-g" "closure-util"
25881 error node v6.10.3
25882 error npm v3.10.10
25883 error code ELIFECYCLE
25884 error closure-util@1.20.0 postinstall: node ./bin/closure-util.js update
25884 error Exit status 1
25885 error Failed at the closure-util@1.20.0 postinstall script 'node ./bin/closure-util.js update'.
25885 error Make sure you have the latest version of node.js and npm installed.
25885 error If you do, this is most likely a problem with the closure-util package,
25885 error not with npm itself.
25885 error Tell the author that this fails on your system:
25885 error node ./bin/closure-util.js update
25885 error You can get information on how to open an issue for this project with:
25885 error npm bugs closure-util
25885 error Or if that isn't available, you can get their info via:
25885 error npm owner ls closure-util
25885 error There is likely additional logging output above.
25886 verbose exit [ 1, true ]

**Comment by fredj** [comment] 2017-05-22 07:55
duplicate of https://github.com/openlayers/closure-util/issues/336

**Closed by fredj** 2017-05-22 07:55 UTC

**Comment by BasieP** [comment] 2017-07-17 13:03
when are we accually fixing this? love pointing too other issues, but it still isn't fixed
