### ISSUE TITLE
WrapX on Heatmap with wrapX true onVectorSource NOT wrapping

### ISSUE THREAD

**Issue by BeGj** [openlayers/openlayers#13330] opened 2022-02-04 15:33 UTC
**Describe the bug**
Tiles are wrapped, but not the heat map. Even if wrapX is set to true on the vectorsource.
Try looking at a heatmap where you look at both Hawait and new Zealand. Good luck, because it is impossible.

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/heatmap-earthquakes.html'
2. scroll the map to the RIGHT to australia. Look at missing heatmap east of the fijis.
3. Now scroll the map LEFT to australia. Now there is heatmap on the fijis, but not on australia.
3. 

**Expected behavior**
Expects Heatmap layer to wrapX.

I thought this was fixed in latest ol version. https://github.com/openlayers/openlayers/pull/13226
But maybe I read it wrong. May be duplicate of #11131

**Comment by ahocevar** [comment] 2022-02-05 00:48
Duplicate of #11131 and #11136

**Closed** 2022-02-05 00:48 UTC
Labels: bug
