### ISSUE TITLE
Export PDF examples sometimes does not reset map extend and zoom 

### ISSUE THREAD

**Issue by bernhardreiter** [openlayers/openlayers#9235] opened 2019-02-18 16:16 UTC
## Description
The official [Export PDF example](https://openlayers.org/en/latest/examples/export-pdf.html) (tested with 5.3.1 - current as of time of writing) does not always reset the map to the previous extend and zoom.

## Reproduction
1. Go to the example https://openlayers.org/en/latest/examples/export-pdf.html
2. Zoom and move and then try to export a pdf.
3. Look at the map, if it is the same as before, try 2. again. Usually it takes a few zoom and move operations to see the problem and the map is not the same as before. It can be triggered in all cases after zooming and moving around enough.

Tested with chromium on Debian GNU/Linux Stretch
Architecture: amd64
Source: chromium-browser
Version: 71.0.3578.80-1~deb9u1

## Expected behavior
The map extend should always be the same after the pdf was generated.

## related issues
Search on Stackoverflow and Github issues and pull requests did not reveal a similiar report.

**Comment by umbe1987** [comment] 2019-02-18 17:25
I can confirm this.
I guess it's because the zoom level is changed after `map.getView().fit(extent, {size: printSize});`.
When enetering the `rendercomplete` part, `map.getView().fit(extent, {size: size});` is supposed to set the map to the extent which had before pressing the Export to PDF button. It works fine, but the zoom level is changed.

Tried to log to console with `console.log(map.getView().getZoom());` to understand this.

**Comment by umbe1987** [comment] 2019-02-18 21:17
Just created a PR which should fix this.

**Comment by bernhardreiter** [comment] 2019-02-19 08:35
@umbe1987 thanks for confirmation and the patch, I'll check into it. 

Any idea why the zoom is sometimes correctly reset and sometimes off?

**Comment by umbe1987** [comment] 2019-02-19 09:22
I guess it might be becasue when changing the extent to fit the page size sometimes this does not change the zoom level and sometimes it does.

**Comment by ahocevar** [comment] 2019-02-19 09:25
> I guess it might be becasue when changing the extent to fit the page size sometimes this does not change the zoom level and sometimes it does.

This can be fixed by configuring `ol/View#fit()` with `constrainResolution: false`.

**Comment by umbe1987** [comment] 2019-02-19 09:42
Just added a new commit with @ahocevar suggestion, but the ci/circleci: build seems to have failed...

**Comment by bernhardreiter** [comment] 2019-02-19 10:23
Here is a stand-a-lone version how to reliable reproduce the problem.
(It uses ol 5.3.0 and an old version of jsPDF though, because I've recycled it, but the versions shall not make a difference for the problem at hand).

The important part is the added fixed initial place that shows the problem right away, once you press "Export PDF":
```javascript
let initialSize = [566, 283];
    map.setSize(initialSize);
    map.getView().fit(
            [3593340, -1689172, 6362195, -304744],
            {size: initialSize,  constrainResolution: false}
    );
```

complete file `ol-export-pdf-issue9235.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Export PDF example</title>
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js" integrity="sha384-iQkGyyH4ioz3m+maM3s9MX1Oq67mACa4B9Z3ovUv3Sv37LJ96fx3WnZfLoiC3Wfl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css" integrity="sha384-C7SzZySesoxngSK5V0BaD1DUap0LPZGWZpnXQGoIwvBXFc8G21y4s1QYvyr84FNa" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.debug.js" integrity="sha384-THVO/sM0mFD9h7dfSndI6TS0PgAGavwKvB5hAxRRvc0o9cPLohB0wb/PTA7LdUHs" crossorigin="anonymous"></script>

    <style>
      .map {
        max-width: 566px;
      }
    </style>
  </head>
  <body>
    <div class="row-fluid">
      <div class="span12">
        <div id="map" class="map"></div>
      </div>
    </div>
    <form class="form">
      <label>Page size </label>
      <select id="format">
        <option value="a0">A0 (slow)</option>
        <option value="a1">A1</option>
        <option value="a2">A2</option>
        <option value="a3">A3</option>
        <option value="a4" selected>A4</option>
        <option value="a5">A5 (fast)</option>
      </select>
      <label>Resolution </label>
      <select id="resolution">
        <option value="72">72 dpi (fast)</option>
        <option value="150">150 dpi</option>
        <option value="300">300 dpi (slow)</option>
      </select>
    </form>
    <button id="export-pdf">Export PDF</button>
    <script>
      let Map = ol.Map;
      let View = ol.View;
      let WKT = ol.format.WKT;
      let TileLayer = ol.layer.Tile;
      let VectorLayer =  ol.layer.Vector;
      let OSM = ol.source.OSM;
      let VectorSource = ol.source.Vector;

      var raster = new TileLayer({
        source: new OSM()
      });

      var format = new WKT();
      var feature = format.readFeature(
        'POLYGON((10.689697265625 -25.0927734375, 34.595947265625 ' +
              '-20.1708984375, 38.814697265625 -35.6396484375, 13.502197265625 ' +
              '-39.1552734375, 10.689697265625 -25.0927734375))');
      feature.getGeometry().transform('EPSG:4326', 'EPSG:3857');

      var vector = new VectorLayer({
        source: new VectorSource({
          features: [feature]
        })
      });


      var map = new Map({
        layers: [raster, vector],
        target: 'map',
        view: new View({
          center: [0, 0],
          zoom: 2
        })
      });

    // to be able to reproduce
    // https://github.com/openlayers/openlayers/issues/9235
    let initialSize = [566, 283];
    map.setSize(initialSize);
    map.getView().fit(
            [3593340, -1689172, 6362195, -304744],
            {size: initialSize,  constrainResolution: false}
    );

      var dims = {
        a0: [1189, 841],
        a1: [841, 594],
        a2: [594, 420],
        a3: [420, 297],
        a4: [297, 210],
        a5: [210, 148]
      };

      var exportButton = document.getElementById('export-pdf');

      exportButton.addEventListener('click', function() {

        exportButton.disabled = true;
        document.body.style.cursor = 'progress';

        var format = document.getElementById('format').value;
        var resolution = document.getElementById('resolution').value;
        var dim = dims[format];
        var width = Math.round(dim[0] * resolution / 25.4);
        var height = Math.round(dim[1] * resolution / 25.4);
        var size = /** @type {module:ol/size~Size} */ (map.getSize());
        var extent = map.getView().calculateExtent(size);

        console.log("size =", size);
        console.log("extent =", extent);

        map.once('rendercomplete', function(event) {
          var canvas = event.context.canvas;
          var data = canvas.toDataURL('image/jpeg');
          var pdf = new jsPDF('landscape', undefined, format);
          pdf.addImage(data, 'JPEG', 0, 0, dim[0], dim[1]);
          pdf.save('map.pdf');
          // Reset original map size
          map.setSize(size);
          map.getView().fit(extent, {size: size});
          exportButton.disabled = false;
          document.body.style.cursor = 'auto';
        });

        // Set print size
        var printSize = [width, height];
        map.setSize(printSize);
        map.getView().fit(extent, {size: printSize});

      }, false);
    </script>
  </body>
</html>
```

**Comment by bernhardreiter** [comment] 2019-02-19 10:28
Using 
```javascript
 map.getView().fit(extent, {size: size, constrainResolution: false});
```
as suggested works!
Thanks @umbe1987 and @ahocevar!

**Closed** 2019-02-19 10:46 UTC
