### ISSUE TITLE
Memory leak with WMS time source with reprojection

### ISSUE THREAD

**Issue by ch08532** [openlayers/openlayers#6987] opened 2017-07-05 19:32 UTC
It appears there is a memory leak in Chrome when using a WMS source with a different projection ('EPSG:4326' reprojected to 'EPSG:3857').   

I've created a code pen using the WMS time example and just swapped it with our WMS feed.  

https://codepen.io/ch08532/pen/NgBWdM?editors=0010#0

Play the example and watch the memory jump and eventually crash Chrome.  I've tested in Firefox and it leaks as well.

**Comment by ch08532** [comment] 2017-07-06 03:00
Ran a heap profiler and compared a few snapshots and did notice a lot of detached DOM tree elements for Image and HTMLCanvasElement constructors.

Each Image constructor references image_ in ol.ImageTile and sourceTiles_ in ol.reproj.Tile



![snapshot](https://user-images.githubusercontent.com/16633974/27893731-9c9070a6-61d5-11e7-94fe-1affd769f691.png)

**Comment by ahocevar** [comment] 2017-07-06 08:15
I'd be interested if the situation improves when you configure a smaller `cacheSize` (e.g. `1024`) for the WMS source.

**Comment by ch08532** [comment] 2017-07-06 12:05
cacheSize did not make a difference.  Lowest cacheSize I could go was 64.  

This issue looks similar to issue [#6940](https://github.com/openlayers/openlayers/issues/6940) which you closed.  

Our application is served in two different projections and we reproject WMS/WMTS layers.  It appears that reprojected tiles leak memory when panning/zooming (which causes new tiles to be fetched).  Memory is in the GB size after 10 minutes of normal use.

**Comment by ahocevar** [comment] 2017-07-07 07:03
@petrsloup - do you have any idea?

**Comment by ch08532** [comment] 2017-07-07 09:54
@ahocevar, I was playing with the code in src/ol/source/tileimage.js where it instantiates a new reproj.Tile and determined that if I commented out the line
      
271	        newTile.interimTile = tile;

The memory leak stopped and did not see any detached objects on my heap snapshot. I did loose the "smoothness" interimTile provides (it basically acted like I wipped the layer clean and displayed the new set of tiles).

**Comment by petrsloup** [comment] 2017-07-07 10:10
@ch08532 Yes, the issue is probably that the new tile always starts with a reference to the interimTile and this reference is never released.

I think we should be able to safely clear the `interimTile` reference after the new tile is ready and reprojected, right?

**Comment by ahocevar** [comment] 2017-07-07 10:18
Sounds like the right fix @petrsloup. Are you or @ch08532 able to provide a pull request?

**Comment by ch08532** [comment] 2017-07-07 11:40
For fun, I added the following code after line 271:
 newTile.interimTile.sourceTiles_.length = 0;
         newTile.interimTile.triangulation_ = null;

doing so reduced the leak and in turn removed those detached references in my heap snapshot...but I believe it has to do with the chaining of interimTiles and holding on the canvas_ (HTMLCanvasELement) references.

**Comment by ch08532** [comment] 2017-07-07 17:11
Ok I believe I've figured it out.   As discussed, the collection of interimTile for the reproj.Tile was never being cleaned up and thus the references would still hang around.  The fix is to perform:

newTile.refreshInterimChain();

after

newTile.interimTile = tile (on line 271)

The refreshInterimChain is only done inside the creation of a reproj.Tile (called within getTileInternal) for an ol.ImageTile.  It wasn't being done on the created reproj.Tile.

Been running my codepen example of the WMS time @ 20Hz and memory is stable.

I'll push a PR shortly.

**Comment by ahocevar** [comment] 2017-07-10 11:02
Fixed with #6987.

**Closed by ahocevar** 2017-07-10 11:02 UTC
Labels: pull request accepted
