### ISSUE TITLE
call VectorLayer.getFeatures add to page body canvas

### ISSUE THREAD

**Issue by bochkov-vi** [openlayers/openlayers#11290] opened 2020-07-18 10:58 UTC
**Describe the bug**
each call to getFeatures adds a visible canvas element to the body of the page

**To Reproduce**
open examples https://openlayers.org/en/latest/examples/image-vector-layer.html
move mouse over map to highlight features
scroll page down you can see new element canvas
zoom map in or out, move mouse over map
scroll page down
one more block will be added
this happens every time the map is redrawn and the method getFeatures(pixel) is called

**Expected behavior**
everyone understands that this behavior is not acceptable

**Comment by mike-000** [comment] 2020-07-18 11:15
Duplicate of #11128 and fixed https://openlayers.org/en/main/examples/image-vector-layer.html

**Closed** 2020-07-21 19:24 UTC
