### ISSUE TITLE
Clone style doesn't work for ol.style.Icon using Internet Explorer 11

### ISSUE THREAD

**Issue by mstrop** [openlayers/openlayers#6583] opened 2017-03-11 15:33 UTC
I have my style defined as  (simplified):
```js
var style = new ol.style.Style({
                    image: new ol.style.Icon({
                        src: 'images/preview_nomove_point.png',
                        anchor: [0.5, 0.5],
                        anchorXUnits: "fraction",
                        anchorYUnits: "fraction",
                        anchorOrigin: "top-left",
                        rotation: 0,
                        scale: 0.5
                    })
                });

return style;
```

In case I return it from my style function like this, it works fine. In case I return

style.clone();

the icon is not visible on the map.

**Comment by ahocevar** [comment] 2017-03-16 13:38
Cannot reproduce. See https://codepen.io/anon/pen/qrVWPQ?&editors=1110.

**Comment by nexiss** [comment] 2017-05-16 15:10
Same for me but using Chrome Versión 58.0.3029.110 (64-bit)

`var myStyle = new ol.style.Style({
    image: new ol.style.Icon({
        src: 'img/myIconpath.png',
        scale: 1,
        anchor: [0.5, 1]
    })
});
var mySecondStyle = myStyle.clone();`

then mySecondStyle.getImage().getSrc() returns '70' (as string) instead of 'img/myIconpath.png'

**Comment by ahocevar** [comment] 2017-05-16 15:52
I just tried with Chrome 58.0.3029.110 (64-bit, MacOS), and I get `'img/myIconPath.png'`, as expected.

**Comment by cs09g** [comment] 2017-05-17 01:31
IE 11 returns the same string as @ahocevar

**Comment by ahocevar** [comment] 2017-05-17 07:17
Can we close this?

**Comment by nexiss** [comment] 2017-05-17 08:10
I initialize the map

```
var map = new ol.Map({
	target: 'map',
	layers: [
		new ol.layer.Tile({
			source: new ol.source.OSM()
		})
	],
	view: new ol.View({
		center: ol.proj.transform([35, 35], 'EPSG:4326', 'EPSG:3857'),
		zoom: 2,
		maxZoom: 19
	})
});
```

Then I set my data into it

```
(function setData()
{
	var myData =[{coordinates: [[1, 4.1], [3.2, 4], [-7.4, 2.5]], color: '#FFFFFF', id:'id1'},
			 {coordinates: [[5, 2], [7, 7], [-4, 3]], color: '#CCCCCC', id:'id1'},
			 {coordinates: [[6, 3.9], [6, 2], [-1, 2]], color: '#AAAAAA', id:'id1'}];

	for(var i=0, len=myData.length; i<len ; i++)			 
	{
		var d = myData[i];
		var allCoordinates = d.coordinates;
		var color= d.color;
		var id = d.id;
		
		var features = [];
		var iconStyle = new ol.style.Style({
			image: new ol.style.Icon({
				src: 'lib/img/myImage.png',
				scale: 1,
				anchor: [0.5, 1],
				color: color
			})
		})
		for(var j=0, len2=allCoordinates.length ; j<len2 ; j++)
		{
			var coordinates = allCoordinates[j];
			
			var iconFeature = new ol.Feature({
				geometry: new ol.geom.Point(ol.proj.transform(coordinates, 'EPSG:4326', 'EPSG:3857'))
			});
			console.log("iconStyle: "+iconStyle.getImage().getSrc());
			var nextIconStyle = iconStyle.clone();
			console.log("nextIconStyle: "+nextIconStyle.getImage().getSrc());
			iconFeature.setStyle(nextIconStyle);
			features.push(iconFeature);
		}
				
		var layer = new ol.layer.Vector({
			id: id,
			source : new ol.source.Vector({
				features: features	
			})
		});

		map.addLayer(layer);
	}
})();
```
The output console is this:

```
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
iconStyle: lib/img/maps/myImage.png
nextIconStyle: lib/img/maps/myImage.png
```

Now, when the user makes an interaction, I wanna clear all layers but the OSM one (the first one).

```
(function clearMap(){
	var lyrs = map.getLayers().getArray();
	if(1<lyrs.length)
	{
		for(var i=1 ; i<lyrs.length ; i++)
		{
			map.removeLayer(lyrs[i]);
			i--;
		}
		var extent = [-60,-60,60,60];
		var extrTrans = ol.proj.transformExtent(extent, 'EPSG:4326', 'EPSG:3857');
		var view = map.getView();
		view.fit(extrTrans);
		var zoom = view.getZoom();
		if(13<zoom)
			view.setZoom(13);
	}
})();
```
And now, when I try to set my data again into the map, The layer is displayed, the features number of each layer is correct but the mapa looks empty and the output console is this:
```
iconStyle: lib/img/maps/myImage.png
74
iconStyle: lib/img/maps/myImage.png
77
iconStyle: lib/img/maps/myImage.png
80
iconStyle: lib/img/maps/myImage.png
85
iconStyle: lib/img/maps/myImage.png
88
iconStyle: lib/img/maps/myImage.png
91
iconStyle: lib/img/maps/myImage.png
96
iconStyle: lib/img/maps/myImage.png
99
iconStyle: lib/img/maps/myImage.png
102
```

**Comment by nexiss** [comment] 2017-05-17 08:11
Note that this only happens when the browser can find the image at: "lib/img/maps/myImage.png"
If that file does not exist, the output console is perfect (the .clone() works) but obviously the map will look empty because there is no image to show. However, if the file exists, its when this happens to me

**Comment by simonseyock** [comment] 2017-09-04 16:18
@ahocevar, i was able to pin this error a little more down.

I am able to observe the error if all of this 4 conditions are met:
1. The browser needs to be internet explorer or microsoft edge
1. It needs to be an icon with a relative url.
1. a style function must be used
1. the style function must return a clone of the style

This does not exactly match with what nexiss did, but with the others. 

With this code i can reproduce this error:

```
      var feat = new ol.Feature(new ol.geom.Point([0, 0]));

      var iconStyle = new ol.style.Style({
        image: new ol.style.Icon({
          //src: 'https://openlayers.org/en/v4.0.1/examples/data/icon.png'
          src: 'images/icon.png'
        })
      });

      var styleFunction = function () {
        return iconStyle.clone();
      };

      var map = new ol.Map({
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          }),
          new ol.layer.Vector({
            source: new ol.source.Vector({
              features: [feat]
            }),
            style: styleFunction
          })
        ],
        target: document.getElementById('map'),
        view: new ol.View({
          center: [0, 0],
          zoom: 3
        })
      });
```

for me the src of the icon style stays correct, but the icon is not displayed.

A colleague of me can observe the same problem.

**Comment by simonseyock** [comment] 2017-09-04 16:28
This error happens with version v4.3.1 and also with v3.19.0 where the clone functionality was introduced.

**Comment by simonseyock** [comment] 2017-09-04 16:42
I tried to debug openlayers a little bit here and found out that
ol.renderer.canvas.VectorLayer.prototype.prepareFrame is called and calls the style function.
ol.renderer.vector.renderFeature detects that the image is not loaded
ol.renderer.canvas.VectorLayer.prototype.handleStyleImageChange_ is called when the image is loaded
this results in another call to ol.renderer.canvas.VectorLayer.prototype.prepareFrame and the style function is called again,
but even if the style gets called again and another clone is created, ol.renderer.vector.renderFeature detects as it should that the image is loaded. Is here maybe the problem that ie can not show the image because the original image object got discarded?

**Comment by simonseyock** [comment] 2017-09-04 17:02
If my theory is correct this should also happen if the style function returns a new style. I will check that tomorrow.

**Comment by simonseyock** [comment] 2017-09-05 10:00
I found the problem: It is the use of .cloneNode on the img. https://github.com/openlayers/openlayers/blob/master/src/ol/style/icon.js#L188

This apparently does not work correctly in internet explorer.

See this code to reproduce:
```
      var feat = new ol.Feature(new ol.geom.Point([0, 0]));

      var img = document.createElement('img');
      img.src = 'images/icon.png';

      var map = new ol.Map({
        layers: [
          new ol.layer.Vector({
            source: new ol.source.Vector({
              features: [feat]
            }),
            style: new ol.style.Style({
              image: new ol.style.Icon({
                //src: 'http://localhost/iconietest/images/icon.png'
                img: img.cloneNode(true),
                imgSize: [32, 37]
              })
            })
          })
        ],
        target: document.getElementById('map'),
        view: new ol.View({
          center: [0, 0],
          zoom: 3
        })
      });
```

**Comment by simonseyock** [comment] 2017-09-05 10:12
If you google "cloneNode internet explorer" you find several posts indicating that it is indeed somehow broken.

**Comment by simonseyock** [comment] 2017-09-05 10:18
cloneNode is used in another code fragment in the openlayers code, too:
https://github.com/openlayers/openlayers/blob/master/src/ol/image.js#L85

Might be necessary to write an own image clone method or an own clone dom element method.

**Comment by simonseyock** [comment] 2017-09-05 10:31
One more thing :) :
the cloneNode method works if the img gets append to the dom one time.

**Comment by simonseyock** [comment] 2017-09-06 13:53
The following piece of code does reveal that cloning a img and drawing it to a canvas does not work as expected in ie/edge.

```
    <canvas id="cnvs" width="100" height="100"></canvas>
    <script>
      var img = document.createElement('img');
      img.src = 'images/icon.png';
      
      var canvas = document.getElementById('cnvs');
      var context = canvas.getContext('2d');
      
      img.addEventListener('load', () => {
        var clone = img.cloneNode(true);
        //document.body.appendChild(clone); //after uncommenting this line it works
        context.drawImage(clone, 0, 0);
      });
    </script>
```

This clearly is a bug in ie / edge. I might file it at microsoft, but nevertheless we should use a working solution for openlayers.

Do you think it might be enough to copy the properties `src`, `height`, `width`? This works and I could definitely provide a PR for this.
The other image properties do not seem to be important, am I right?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement

**Comment by ahocevar** [comment] 2017-09-06 14:23
I think the right thing to do would be to not have a different code path for 'IMG' elements. Just always render the old image to a canvas and use that as `img` is the way to go. Can you create a pull request for that?

The other occurrence of `Image.prototype.cloneNode()` can be removed, it's a leftover from the time when we still had a dom renderer. I'll create a pull request for that.

**Comment by mstrop** [comment] 2017-09-07 07:30
I have the same problem. In case clone is not used, everything work  fine.

**Comment by simonseyock** [comment] 2017-09-08 10:47
Sure that is no problem.

Just some thougts:
Is it really needed to clone the underlying image? For me the normal use-case of using the clone method is to just change some ol.style properties.
Not cloning the image would make the cloning faster and might make a difference if it is used in every call of a style function. Also thinkable is a boolean parameter for the clone method.

**Comment by simonseyock** [comment] 2017-09-08 10:58
We could make it clear in the comments that the image is not cloned and if the user wants to manipulate the underlying image programmatically he could clone it by himself. To help someone with this we could add a cloneImage method to the ol.style.IconImage that will return a new canvas.

**Comment by ahocevar** [comment] 2017-09-08 11:18
> For me the normal use-case of using the clone method is to just change some ol.style properties.

Good point since there is no setter for `img` or `src` on `ol.style.Icon`. @simonseyock, please create a pull request as you suggested, with a note in the docs, but without a cloneImage method.

One more thing to consider: inside a style function, if you just want to change a few properties, there is no need to clone the style. Just set the properties you want to set, and it will just be used for the feature that the style function was called with.

**Comment by simonseyock** [comment] 2017-09-08 11:27
Ok.

But if the style is created outside the style function and if I want to change a parameter just for certain cases, I will have to clone the style.

**Closed** 2017-09-12 11:15 UTC
Labels: pull request accepted
