### ISSUE TITLE
movestart event - for map panning fluidity on processing intensive web applications

### ISSUE THREAD

**Issue by wayofthefuture** [openlayers/openlayers#6306] opened 2016-12-27 15:32 UTC
Please let me know a donation amount to get the "movestart" added to map events. We really need a movestart event, and would be willing to donate to get it.

The reason: we have a heavy processing ajax refresh that updates the map with data. When the user is panning the map, if this ajax refresh will sometimes fire in the middle of the pan, and it makes the pan feel choppy thereby decreasing the user experience.

In OL2, we set a boolean on the movestart event and unset it on the moveend event. The ajax data result processing would wait until this boolean is unset on the moveend event before firing the request. This way when the user pans the map it always feels smooth and fluid. The instant they lift their finger the request fires and usually finishes before their finger lands back on the map to continue panning. It's these minor tweaks that really can make huge gains in user experience.

Thanks for your help.

**Comment by ahocevar** [comment] 2017-01-04 13:15
Duplicate of #3985. @wayofthefuture, please contact me by PM.

**Closed by ahocevar** 2017-01-04 13:15 UTC

**Comment by wayofthefuture** [comment] 2017-01-09 23:00
PM ? Private Message?

**Comment by wayofthefuture** [comment] 2017-05-28 19:59
I looked for a way to contact you but was unable to find one. I looked through your web page, boundless geo and github. No luck :(.

**Comment by ahocevar** [comment] 2017-05-30 11:20
You'll find my contact information [here](https://www.wkoecg.at/Web/Ecg.aspx?FirmaID=fc1150d0-b795-460d-82fa-54a4cf6da862).
