### ISSUE TITLE
Snap not working in 6.5.0

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#11976] opened 2021-02-02 18:54 UTC
**Describe the bug**
Snapping does not work correctly in 6.5.0 - Works 100% in 6.4.3

**To Reproduce**
Drag line (starting some distance from line), then drag to point and snap.  You will see that snap occurs on point at the same distance that dragging started from line.  Maybe to do with delta_ in ol/interaction/Modify:

```
Modify.prototype.handleDragEvent = function (evt) {
        this.ignoreNextSingleClick_ = false;
        this.willModifyFeatures_(evt, this.dragSegments_);
        var vertex = [
            evt.coordinate[0] + this.delta_[0],
            evt.coordinate[1] + this.delta_[1],
        ];
```

See Code and video below

Video:

https://user-images.githubusercontent.com/1152458/106648236-aa358280-6598-11eb-80fb-b18868f2e536.mp4

Code:

```
import "ol/ol.css";
import Map from "ol/Map";
import View from "ol/View";
import GeoJSON from "ol/format/GeoJSON";
import { Modify, Snap } from "ol/interaction";
import { Vector as VectorSource } from "ol/source";
import { Vector as VectorLayer } from "ol/layer";
import { transform } from "ol/proj";

var vector1 = new VectorLayer({
  source: new VectorSource({
    format: new GeoJSON(),
    features: new GeoJSON().readFeatures({
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          geometry: {
            type: "LineString",
            coordinates: [
              [2059761.8846943479, -4001987.9903377485],
              [2059183.3271955752, -4002069.1811360097]
            ]
          },
          properties: {}
        }
      ]
    })
  })
});

var vector2 = new VectorLayer({
  source: new VectorSource({
    format: new GeoJSON(),
    features: new GeoJSON().readFeatures({
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: [2059524.189759539, -4002117.2223334215]
          },
          properties: {}
        }
      ]
    })
  })
});

var map = new Map({
  layers: [vector1, vector2],
  target: "map",
  view: new View({
    center: transform(
      [18.50310560948664, -33.799754138117294],
      "EPSG:4326",
      "EPSG:3857"
    ),
    zoom: 17
  })
});

var ExampleModify = {
  init: function () {
    this.modify = new Modify({
      source: vector1.getSource()
    });
    map.addInteraction(this.modify);
  },
  setActive: function (active) {
    this.modify.setActive(active);
  }
};
ExampleModify.init();

ExampleModify.setActive(true);

// The snap interaction must be added after the Modify and Draw interactions
// in order for its map browser event handlers to be fired first. Its handlers
// are responsible of doing the snapping.
var snap = new Snap({
  source: vector2.getSource()
});
map.addInteraction(snap);

```

Test:

https://codesandbox.io/s/snap-forked-g2dge

**Expected behavior**
Should snap correctly

**Comment by MoonE** [comment] 2021-02-02 19:34
Thanks for the report.

This is likely caused by #11769 and the change to the dragged features position under the mouse pointer.
The placement under the mouse pointer used to be the center of the point, with 6.5.0 it was changed to the position it was clicked on.
The version on codesandbox for this change is `6.4.4-dev.1607296357109`.

**Comment by 1Map** [comment] 2021-02-02 19:38
Ok, so how would I go about for the above code to work in 6.5.0 ?

**Comment by MoonE** [comment] 2021-02-02 20:08
This is an unintentional regression.

I gave it a first shot with https://github.com/MoonE/openlayers/commit/63e0a7dec113c66d76abfe312843e5afdf54f33e, but the snap distance is not working correctly this way because the origin of the snap tolerance measurement is the mouse pointer, and not the vertex center, like it should be.

**Comment by 1Map** [comment] 2021-02-02 20:26
Did you take the code example above and tested it with 6.4.3 and then again with 6.5.0?  You will see that in 6.4.3 it works as expected, but not in 6.5.0.  You are correct that the mouse pointer should be used to measure the snap tolerance, and it works that way when starting the drag. The problem is when you snap after a drag to an existing point, then it does not snap to the target point, but rather with the same offset when the drag started (on the source point).

**Comment by MoonE** [comment] 2021-02-02 23:06
I did test it with both versions and with my commit above it should snap to the correct position. 
But if the mouse and vertex center are different the snap tolerance is larger to the side where the mouse pointer is.

The problem with implementing this correctly now is that there is kind of a circular dependency.
`Snap` depends on `Modify` to use the correct snap tolerance center point from the dragged vertex.
`Modify` depends on `Snap` to get the correct coordinate.

Not sure how to best resolve this.

**Comment by ahocevar** [comment] 2021-02-03 07:22
Not sure if it is a solution in your case @1Map, but the problem goes away when you also make the source geometry also a snap target, which is e.g. the case in https://openlayers.org/en/latest/examples/snap.html.

@MoonE: the problem you're describing regarding vertex center vs mouse position must have existed prior to the introduction of the delta calculation in `ol/interaction/Snap` as well.

Going forward, I think the best option is to make the delta calculation optional. `ol/interaction/Modify` could get a new option `snapToPointer`. When set to `true`, no delta between vertex/point and pointer will be calculated and applied.

**Comment by 1Map** [comment] 2021-02-03 07:33
Hi @ahocevar 

The problem does go away when the source geometry is also a snap target, but this will not solve my problem as in my case I want to prohibit users to snap to certain features.

The real problem here is as follow:

You use delta (cursor position to feature position) when start dragging a snappped feature (which is 100% correct and also works 100%).  The problem now is, because that code lives in Modify it does the same logic when a dragged feature is snapped to a target feature.  Here the feature do get snapped, but with the new calculated delta (cursor position to target snap feature), which is wrong as we want the feature to snap to exactly the centroid of the target feature.  So, the code should only use delta if you start dragging, but not when you drop the feature.

**Comment by ahocevar** [comment] 2021-02-03 07:59
@1Map Yes, I do understand the problem. Please test with ba4077237b, and configure the `Modify` interaction with `snapToPointer: true`.

**Comment by 1Map** [comment] 2021-02-03 08:19
Hi @ahocevar 

Thanks, this works perfect.  Will this change be in the next release, and when can the public expect this?

**Comment by ahocevar** [comment] 2021-02-03 09:10
I'm going to finalize a pull request with the above change. Once that is reviewed and merged, you can use it with `npm install ol@dev`, and it will also be in the next release.

**Comment by ahocevar** [comment] 2021-02-03 09:56
#11978 is the pull request that introduces the `snapToPointer` option mentioned in https://github.com/openlayers/openlayers/issues/11976#issuecomment-772295018.

**Closed** 2021-02-06 11:57 UTC
