### ISSUE TITLE
Uncaught Invalid GIF 87a/89a header. openlayers6. VueJS2.x. help me .thanks!

### ISSUE THREAD

**Issue by kongjun0320** [openlayers/openlayers#12210] opened 2021-04-13 03:12 UTC
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Comment by ahocevar** [comment] 2021-04-13 07:00
Duplicate of #12209.

**Closed by ahocevar** 2021-04-13 07:00 UTC
Labels: bug
